-- Generated by scripts/generate-seed.mts. Do not edit by hand.

truncate public.winners, public.challenges, public.news_posts, public.modules, public.sesi, public.registration_rounds restart identity cascade;

insert into public.modules (id, minggu, judul, rilis, tentor_pj, koordinator, ringkasan, berkas_url, tenggat) values
  ($ksp$mod-01$ksp$, 1, $ksp$Flowchart 1$ksp$, $ksp$2026-09-21$ksp$, array[$ksp$Sabrina$ksp$, $ksp$Eldha$ksp$]::text[], $ksp$Michelle$ksp$, $ksp$Simbol-simbol flowchart dan alur urut: terminal, proses, masukan dan keluaran, serta cara membaca diagram dari atas ke bawah.$ksp$, null, null),
  ($ksp$mod-02$ksp$, 2, $ksp$Flowchart 2$ksp$, $ksp$2026-09-28$ksp$, array[$ksp$Sabrina$ksp$, $ksp$Eldha$ksp$]::text[], $ksp$Michelle$ksp$, $ksp$Percabangan dan perulangan di flowchart: simbol keputusan, alur yang kembali ke atas, dan menelusuri diagram dengan tabel jejak.$ksp$, null, null),
  ($ksp$mod-03$ksp$, 3, $ksp$Tipe Data$ksp$, $ksp$2026-10-05$ksp$, array[$ksp$Boby$ksp$, $ksp$Kley$ksp$]::text[], $ksp$Kley$ksp$, $ksp$Aturan penamaan variabel, tipe data dasar di C, dan program sekuensial pertama dengan printf dan scanf.$ksp$, null, null),
  ($ksp$mod-04$ksp$, 4, $ksp$Pemilihan$ksp$, $ksp$2026-11-02$ksp$, array[$ksp$Dwi$ksp$, $ksp$Andrew$ksp$]::text[], $ksp$Kley$ksp$, $ksp$if, else if, else, dan switch — memilih jalur program berdasarkan kondisi.$ksp$, null, null),
  ($ksp$mod-05$ksp$, 5, $ksp$Perulangan 1$ksp$, $ksp$2026-11-09$ksp$, array[$ksp$Ardhya$ksp$, $ksp$Beto$ksp$]::text[], $ksp$Rena$ksp$, $ksp$for dan while: menghitung, menjumlahkan, dan menentukan kapan sebuah perulangan berhenti.$ksp$, null, null),
  ($ksp$mod-06$ksp$, 6, $ksp$Perulangan 2$ksp$, $ksp$2026-11-16$ksp$, array[$ksp$Doni$ksp$, $ksp$Rena$ksp$]::text[], $ksp$Rena$ksp$, $ksp$do-while, perulangan bersarang, serta break dan continue.$ksp$, null, null),
  ($ksp$mod-07$ksp$, 7, $ksp$Prosedur 1$ksp$, $ksp$2026-11-23$ksp$, array[$ksp$Richard$ksp$, $ksp$Petra$ksp$]::text[], $ksp$Richard$ksp$, $ksp$Memecah program menjadi prosedur: deklarasi, pemanggilan, dan parameter masukan.$ksp$, null, null),
  ($ksp$mod-08$ksp$, 8, $ksp$Prosedur 2$ksp$, $ksp$2027-03-01$ksp$, array[$ksp$Adit$ksp$, $ksp$Tristan$ksp$]::text[], $ksp$Richard$ksp$, $ksp$Parameter keluaran: kenapa nilai yang diubah di dalam prosedur tidak ikut kembali, dan cara memperbaikinya dengan pointer.$ksp$, null, null),
  ($ksp$mod-09$ksp$, 9, $ksp$Fungsi$ksp$, $ksp$2027-03-15$ksp$, array[$ksp$Nathan$ksp$, $ksp$Stella$ksp$]::text[], $ksp$Michelle$ksp$, $ksp$Fungsi yang mengembalikan nilai, return, dan kapan memilih fungsi daripada prosedur.$ksp$, null, null),
  ($ksp$mod-10$ksp$, 10, $ksp$Array$ksp$, $ksp$2027-04-26$ksp$, array[$ksp$Albert$ksp$, $ksp$Nadya$ksp$]::text[], $ksp$Audrey$ksp$, $ksp$Array satu dimensi: indeks, perulangan atas array, pencarian, dan nilai terbesar atau terkecil.$ksp$, null, null),
  ($ksp$mod-11$ksp$, 11, $ksp$Record$ksp$, $ksp$2027-05-03$ksp$, array[$ksp$Jolie$ksp$, $ksp$Epun$ksp$]::text[], $ksp$Audrey$ksp$, $ksp$struct sebagai record: mengelompokkan data yang saling berkaitan dan mengakses tiap field-nya.$ksp$, null, null),
  ($ksp$mod-12$ksp$, 12, $ksp$Array of Record$ksp$, $ksp$2027-05-18$ksp$, array[$ksp$Adit$ksp$]::text[], $ksp$Audrey$ksp$, $ksp$Menggabungkan keduanya: array berisi struct untuk data berbentuk tabel, seperti daftar nilai satu kelas.$ksp$, null, $ksp$2027-05-23T23:59$ksp$);

insert into public.sesi (id, judul, rilis, pj, ringkasan) values
  ($ksp$sesi-games$ksp$, $ksp$Games$ksp$, $ksp$2026-11-30$ksp$, $ksp$PH$ksp$, $ksp$Sesi santai di akhir semester ganjil: permainan dan kuis seputar materi yang sudah dipelajari. Tanpa modul dan tanpa tugas.$ksp$),
  ($ksp$sesi-review$ksp$, $ksp$Review Materi$ksp$, $ksp$2027-02-22$ksp$, $ksp$PH$ksp$, $ksp$Mengulang materi semester ganjil sebelum lanjut ke prosedur dan fungsi. Tanpa modul dan tanpa tugas.$ksp$);

insert into public.news_posts (id, slug, judul, tanggal, kategori, cover, excerpt, penulis, body_mdx, tags) values
  ($ksp$n-15$ksp$, $ksp$sepuluh-fakta-lain-bahasa-c$ksp$, $ksp$Sepuluh Fakta Lain tentang Bahasa C$ksp$, $ksp$2026-09-26$ksp$, $ksp$fakta$ksp$, $ksp$https://bgrgkqrolpgcmbdlruzt.supabase.co/storage/v1/object/public/media/berita/e0bb080d-d8d1-4f5b-91c4-f69644675b08.jpg$ksp$, $ksp$Huruf yang sebenarnya angka, nol di depan yang mengubah arti, sampai lomba menulis kode paling membingungkan. Sepuluh kejutan kecil lagi dari bahasa C.$ksp$, $ksp$Tim KSP$ksp$, $ksp$Tujuh fakta sebelumnya ternyata belum cukup. Bahasa C masih menyimpan banyak
kejutan kecil, dan beberapa di antaranya justru sering menjebak pemula. Berikut
sepuluh fakta lagi, lengkap dengan contoh yang bisa kamu coba langsung di
Dev-C++.

## 1. Unix ditulis ulang dengan C

Pada 1973, sistem operasi Unix ditulis ulang dengan C. Itu menjadikannya salah
satu sistem operasi pertama yang ditulis dengan bahasa tingkat tinggi, bukan
bahasa mesin. Sejak saat itu, C dan Unix tumbuh bersama.

## 2. Penciptanya memenangkan "Nobel"-nya ilmu komputer

Dennis Ritchie dan Ken Thompson menerima Turing Award pada 1983 atas karya
mereka membangun Unix. Turing Award sering disebut sebagai penghargaan
tertinggi di bidang ilmu komputer.

## 3. `printf` bukan bagian inti bahasa C

`printf` berasal dari pustaka standar, bukan dari bahasa C itu sendiri. Itu
sebabnya kita harus menulis `#include <stdio.h>` di awal program: baris itu
yang memberi tahu compiler bahwa `printf` ada.

## 4. Huruf sebenarnya adalah angka

Di dalam komputer, setiap karakter disimpan sebagai angka. Huruf `A` adalah 65,
dan kamu bahkan bisa menjumlahkannya:

```c
printf("%c %d\n", 'A' + 1, 'A');
```

Keluarannya `B 65`. Satu setelah `A` adalah `B`.

## 5. Nol di depan angka mengubah artinya

Coba tebak keluaran program ini:

```c
printf("%d\n", 010);
```

Jawabannya bukan 10, tapi **8**. Angka yang diawali `0` dibaca C sebagai
bilangan oktal (basis 8). Jadi hati-hati saat menulis angka seperti `007`.

## 6. Pembagian bilangan bulat membuang sisanya

```c
printf("%d %d %.1f\n", 7 / 2, 7 % 2, 7.0 / 2);
```

Keluarannya `3 1 3.5`. Kalau kedua angkanya bilangan bulat, hasil pembagiannya
juga bulat dan sisanya dibuang. Sisanya bisa diambil dengan `%`. Kalau butuh
hasil pecahan, salah satu angkanya harus desimal, seperti `7.0`.

## 7. Semua angka selain nol dianggap benar

C versi awal tidak punya tipe `true` dan `false`. Aturannya sederhana: `0`
berarti salah, angka lain apa pun berarti benar.

```c
if (5) printf("benar\n");
```

Baris itu selalu mencetak `benar`, karena 5 bukan nol.

## 8. `=` dan `==` itu sangat berbeda

`=` artinya "isi dengan", sedangkan `==` artinya "apakah sama dengan". Menulis
yang pertama di dalam `if` adalah bug klasik:

```c
if (x = 0) printf("tidak pernah tercetak\n");
```

Baris ini tidak memeriksa apakah `x` sama dengan 0. Ia *mengisi* `x` dengan 0,
lalu memeriksa hasilnya, yang selalu salah. Kalau `-Wall` menyala, compiler
akan memberi peringatan `suggest parentheses around assignment used as truth
value`, tanda bahwa kemungkinan besar kamu bermaksud menulis `==`.

## 9. Satu titik koma bisa mengosongkan perulangan

```c
for (i = 0; i < 3; i++);
printf("i = %d\n", i);
```

Perhatikan titik koma di akhir baris `for`. Titik koma itu dianggap sebagai
isi perulangan yang kosong, jadi `printf` di bawahnya hanya jalan **sekali**,
setelah perulangan selesai, dan mencetak `i = 3`.

## 10. Ada lomba menulis kode C yang paling membingungkan

Sejak 1984 ada International Obfuscated C Code Contest, lomba untuk menulis
program C yang sesulit mungkin dibaca tapi tetap berjalan dengan benar.
Pesertanya membuat program yang bentuk kodenya menyerupai gambar, atau
program yang bisa mencetak kodenya sendiri. Menghibur untuk dilihat, tapi
jangan ditiru di tugasmu.$ksp$, array[$ksp$fakta$ksp$, $ksp$bahasa-c$ksp$, $ksp$pemula$ksp$]::text[]),
  ($ksp$n-16$ksp$, $ksp$kenapa-array-dimulai-dari-nol$ksp$, $ksp$Kenapa Array Dimulai dari Nol?$ksp$, $ksp$2026-09-25$ksp$, $ksp$fakta$ksp$, $ksp$https://bgrgkqrolpgcmbdlruzt.supabase.co/storage/v1/object/public/media/berita/b3429625-9b95-4714-bc36-97d234c16e6d.jpg$ksp$, $ksp$Elemen pertama array bukan nomor 1, melainkan 0. Ternyata alasannya masuk akal sekali, dan paham ini menyelamatkanmu dari bug paling umum saat memakai array.$ksp$, $ksp$Tim KSP$ksp$, $ksp$Salah satu hal pertama yang membingungkan saat belajar array: elemen pertama
bukan nomor 1, melainkan nomor **0**. Kenapa begitu? Ternyata alasannya masuk
akal sekali.

## Contoh sederhana

```c
int nilai[3] = {80, 75, 90};
printf("%d %d %d\n", nilai[0], nilai[1], nilai[2]);
```

Keluarannya `80 75 90`. Array berisi tiga elemen, dan nomornya 0, 1, dan 2.
Tidak ada `nilai[3]`.

## Indeks adalah jarak dari awal

Anggap array seperti deretan loker yang berjejer. Indeks bukan "loker
ke berapa", melainkan "berapa langkah dari loker pertama".

- Loker pertama berjarak **0 langkah** dari awal, jadi indeksnya 0.
- Loker kedua berjarak 1 langkah, jadi indeksnya 1.
- Dan seterusnya.

Komputer menyimpan isi array berderet di memori. Untuk mencari `nilai[2]`,
komputer cukup mengambil alamat awal array lalu melompat dua kali ukuran
satu elemen. Dengan indeks mulai dari 0, perhitungan ini jadi sesederhana
mungkin, tanpa perlu dikurangi satu setiap saat.

## Akibatnya untuk perulangan

Karena indeks terakhir adalah jumlah elemen dikurangi satu, perulangan untuk
array biasanya ditulis seperti ini:

```c
int i;
for (i = 0; i < 3; i++) {
    printf("nilai[%d] = %d\n", i, nilai[i]);
}
```

Perhatikan dua hal: mulai dari `i = 0`, dan kondisinya `i < 3`, **bukan**
`i <= 3`.

## Hati-hati melewati batas

Kalau kamu menulis `nilai[3]` pada array berisi tiga elemen, C tidak akan
menghentikanmu. Program tetap berjalan, tapi yang dibaca adalah memori di
luar array, dan hasilnya bisa berupa angka acak atau program yang tiba-tiba
berhenti. Kesalahan ini disebut *out of bounds*, dan salah satu cara paling
umum terjadinya adalah memakai `<=` di kondisi perulangan.

## Bukan hanya C

Hampir semua bahasa populer, seperti Java, Python, dan JavaScript, juga
memulai indeks dari 0. Jadi kebiasaan ini akan terus berguna, bahasa apa pun
yang kamu pelajari berikutnya.$ksp$, array[$ksp$fakta$ksp$, $ksp$array$ksp$, $ksp$pemula$ksp$]::text[]),
  ($ksp$n-17$ksp$, $ksp$mengenal-tipe-data-dasar-c$ksp$, $ksp$Mengenal Tipe Data Dasar di C$ksp$, $ksp$2026-09-23$ksp$, $ksp$tutorial$ksp$, $ksp$https://bgrgkqrolpgcmbdlruzt.supabase.co/storage/v1/object/public/media/berita/be2529a9-3c44-4009-a3a3-f65c54740c8f.jpg$ksp$, $ksp$int, float, double, dan char: kapan dipakai, cara mencetaknya, dan dua jebakan yang paling sering menjebak pemula.$ksp$, $ksp$Tim KSP$ksp$, $ksp$Setiap variabel di C harus punya tipe. Tipe menentukan jenis nilai yang bisa
disimpan, berapa banyak memori yang dipakai, dan cara nilainya dicetak. Ada
empat tipe dasar yang akan kamu pakai hampir setiap hari.

## Empat tipe dasar

| Tipe | Untuk menyimpan | Contoh | Format printf |
| --- | --- | --- | --- |
| `int` | bilangan bulat | `18`, `-5` | `%d` |
| `float` | bilangan pecahan | `170.5` | `%f` |
| `double` | bilangan pecahan yang lebih teliti | `3.75` | `%f` |
| `char` | satu karakter | `'A'` | `%c` |

Contoh pemakaiannya:

```c
int umur = 18;
float tinggi = 170.5;
double ipk = 3.75;
char huruf = 'A';

printf("%d\n", umur);
printf("%f\n", tinggi);
printf("%.2f\n", ipk);
printf("%c\n", huruf);
```

Keluarannya:

```
18
170.500000
3.75
A
```

Perhatikan bahwa `%f` secara bawaan mencetak enam angka di belakang koma.
Pakai `%.2f` kalau hanya butuh dua.

## `float` atau `double`?

Keduanya untuk bilangan pecahan, tapi `double` menyimpan angka dengan
ketelitian sekitar dua kali lipat `float`. Di komputer yang biasa dipakai
sekarang, `float` memakai 4 byte dan `double` 8 byte. Untuk tugas kuliah,
`double` biasanya pilihan yang lebih aman.

## Jebakan: `scanf` untuk `double`

Saat mencetak, `double` memakai `%f`. Tapi saat **membaca** dengan `scanf`,
`double` harus memakai `%lf`:

```c
double ipk;
scanf("%lf", &ipk);
```

Kalau kamu memakai `%f` di `scanf` untuk variabel `double`, nilai yang
tersimpan akan kacau. Ini salah satu kesalahan paling sering di awal belajar.

## Jebakan: pembagian bilangan bulat

```c
printf("%d\n", 5 / 2);
```

Hasilnya `2`, bukan `2.5`. Kalau kedua angkanya `int`, hasilnya juga `int` dan
angka di belakang koma dibuang. Kalau butuh hasil pecahan, jadikan salah satu
angkanya pecahan, misalnya `5.0 / 2`.

## Satu karakter, bukan kata

`char` hanya menyimpan **satu** karakter, dan ditulis dengan tanda kutip
tunggal: `'A'`. Tanda kutip ganda seperti `"A"` adalah teks (string), dan itu
hal yang berbeda.$ksp$, array[$ksp$tutorial$ksp$, $ksp$tipe-data$ksp$, $ksp$pemula$ksp$]::text[]),
  ($ksp$n-18$ksp$, $ksp$for-while-do-while$ksp$, $ksp$for, while, do-while: Kapan Pakai yang Mana?$ksp$, $ksp$2026-09-21$ksp$, $ksp$tips$ksp$, $ksp$https://bgrgkqrolpgcmbdlruzt.supabase.co/storage/v1/object/public/media/berita/8722d7b2-5102-4d06-81ba-1201096035d0.jpg$ksp$, $ksp$Tiga jenis perulangan yang bisa saling menggantikan, tapi masing-masing paling cocok untuk situasi yang berbeda. Begini cara memilihnya.$ksp$, $ksp$Tim KSP$ksp$, $ksp$C punya tiga jenis perulangan: `for`, `while`, dan `do-while`. Ketiganya bisa
dipakai untuk mengulang, tapi masing-masing paling cocok untuk situasi yang
berbeda. Memilih yang tepat membuat kodemu lebih mudah dibaca.

## `for`: jumlah ulangannya sudah diketahui

Pakai `for` kalau kamu tahu persis berapa kali perulangan harus berjalan.

```c
int i;
for (i = 1; i <= 3; i++) {
    printf("%d ", i);
}
```

Keluarannya `1 2 3`. Semua pengaturan perulangan (nilai awal, kondisi, dan
perubahan) ada di satu baris, jadi mudah dilihat sekilas.

Ingat, di Dev-C++ variabel `i` harus dideklarasikan di luar `for`.

## `while`: berhenti saat kondisi tertentu terpenuhi

Pakai `while` kalau jumlah ulangannya belum diketahui, dan perulangan harus
berjalan **selama** suatu kondisi masih benar.

```c
i = 10;
while (i > 0) {
    i = i / 2;
    printf("%d ", i);
}
```

Keluarannya `5 2 1 0`. Kita tidak menentukan jumlah ulangannya di awal.
Perulangan berhenti sendiri saat `i` tidak lagi lebih dari 0.

Karena kondisinya diperiksa di awal, isi `while` bisa saja tidak dijalankan
sama sekali kalau kondisinya sudah salah sejak awal.

## `do-while`: jalan minimal sekali

`do-while` memeriksa kondisinya di akhir, jadi isinya **pasti** dijalankan
paling tidak satu kali. Ini paling cocok untuk meminta input sampai valid:

```c
int angka;
do {
    printf("Masukkan angka positif: ");
    scanf("%d", &angka);
} while (angka <= 0);
```

Program akan terus bertanya sampai pengguna memasukkan angka yang lebih dari
nol. Pertanyaannya harus muncul minimal sekali, dan `do-while` menjamin itu.

Jangan lupa titik koma setelah `while (...)` di akhir `do-while`.

## Ringkasnya

| Situasi | Pilihan |
| --- | --- |
| Jumlah ulangan sudah pasti | `for` |
| Ulang selama kondisi benar, bisa nol kali | `while` |
| Harus jalan minimal sekali | `do-while` |

Ketiganya sebenarnya bisa saling menggantikan. Tapi memilih yang paling cocok
membuat maksud kodemu langsung terbaca oleh orang lain, termasuk oleh dirimu
sendiri seminggu kemudian.$ksp$, array[$ksp$tips$ksp$, $ksp$perulangan$ksp$, $ksp$pemula$ksp$]::text[]),
  ($ksp$n-19$ksp$, $ksp$scanf-melewati-input-karakter$ksp$, $ksp$Kenapa scanf Melewati Input Karakter?$ksp$, $ksp$2026-09-18$ksp$, $ksp$tips$ksp$, $ksp$https://bgrgkqrolpgcmbdlruzt.supabase.co/storage/v1/object/public/media/berita/338cbe57-20a0-4e82-bd5f-b97f2468a3ed.jpg$ksp$, $ksp$Pertanyaan kedua langsung terlewat tanpa sempat dijawab? Ada karakter tersembunyi dari tombol Enter yang tertinggal. Perbaikannya cuma satu spasi.$ksp$, $ksp$Tim KSP$ksp$, $ksp$Kamu menulis program yang meminta umur, lalu bertanya "Lanjut? (y/n)". Tapi
saat dijalankan, pertanyaan kedua langsung terlewat tanpa sempat kamu jawab.
Programnya tidak rusak. Ada karakter tersembunyi yang tertinggal.

## Programnya

```c
int umur;
char jawab;

printf("Umur: ");
scanf("%d", &umur);
printf("Lanjut? (y/n): ");
scanf("%c", &jawab);
printf("[%c] kode %d\n", jawab, jawab);
```

Kalau kamu mengetik `18` lalu menekan Enter, program langsung selesai dan
mencetak kurung yang kosong, diikuti `kode 10`.

## Apa yang terjadi

Saat kamu mengetik `18` lalu Enter, yang masuk sebenarnya tiga karakter: `1`,
`8`, dan karakter **baris baru** dari tombol Enter.

`scanf("%d")` mengambil angka `18`, tapi berhenti tepat sebelum baris baru.
Karakter baris baru itu tertinggal, menunggu dibaca. Lalu `scanf("%c")`
datang dan dengan senang hati mengambilnya, karena bagi `%c`, baris baru juga
sebuah karakter. Angka `10` di keluaran adalah kode karakter baris baru itu.

## Perbaikannya satu spasi

Tambahkan satu spasi sebelum `%c`:

```c
scanf(" %c", &jawab);
```

Spasi di dalam format `scanf` artinya "lewati semua spasi, tab, dan baris
baru yang ada". Setelah itu barulah satu karakter dibaca. Sekarang program
menunggu jawabanmu dengan benar.

## Kenapa `%d` tidak mengalami ini?

Format seperti `%d`, `%f`, dan `%s` secara otomatis melewati spasi dan baris
baru sebelum membaca. Hanya `%c` yang tidak, karena tugasnya memang membaca
karakter apa pun, termasuk spasi.

Jadi aturannya mudah diingat: **setiap kali membaca `%c` setelah membaca
input lain, beri spasi di depannya.**$ksp$, array[$ksp$tips$ksp$, $ksp$scanf$ksp$, $ksp$input$ksp$]::text[]),
  ($ksp$n-20$ksp$, $ksp$flowchart-sebelum-ngoding$ksp$, $ksp$Flowchart: Rencanakan Dulu, Ngoding Kemudian$ksp$, $ksp$2026-09-14$ksp$, $ksp$tips$ksp$, $ksp$https://bgrgkqrolpgcmbdlruzt.supabase.co/storage/v1/object/public/media/berita/a7686b60-e44a-4b23-a3bb-3d2539b2580c.jpg$ksp$, $ksp$Daripada langsung mengetik lalu berputar-putar, gambar dulu alurnya. Kalau alurnya sudah benar, kodenya tinggal mengikuti.$ksp$, $ksp$Tim KSP$ksp$, $ksp$Banyak pemula langsung membuka Dev-C++ dan mulai mengetik begitu membaca
soal. Hasilnya sering berputar-putar: kode ditulis, dihapus, ditulis ulang.
Ada cara yang lebih tenang: gambar dulu alurnya dengan flowchart.

## Apa itu flowchart?

Flowchart adalah diagram yang menggambarkan langkah-langkah penyelesaian
masalah, dari awal sampai akhir. Setiap bentuk punya arti:

| Bentuk | Arti |
| --- | --- |
| Oval | mulai atau selesai |
| Persegi panjang | proses, misalnya menghitung |
| Jajaran genjang | input atau output |
| Belah ketupat | keputusan, jawabannya ya atau tidak |
| Panah | arah alur |

## Contoh: menentukan lulus atau tidak

Soalnya: baca nilai, lalu cetak "lulus" kalau nilainya minimal 60.

Alurnya dalam flowchart:

1. **Mulai** (oval)
2. **Baca nilai** (jajaran genjang)
3. **Apakah nilai lebih dari atau sama dengan 60?** (belah ketupat)
4. Kalau **ya**, cetak "lulus". Kalau **tidak**, cetak "tidak lulus" (jajaran genjang)
5. **Selesai** (oval)

Setelah alurnya jelas, menerjemahkannya ke C hampir seperti menyalin:

```c
int nilai;
scanf("%d", &nilai);
if (nilai >= 60) {
    printf("lulus\n");
} else {
    printf("tidak lulus\n");
}
```

## Kenapa ini membantu

- **Memisahkan dua masalah.** Memikirkan *apa* yang harus dilakukan dan
  *bagaimana* menulisnya di C adalah dua hal berbeda. Flowchart membuatmu
  menyelesaikan yang pertama dulu.
- **Kesalahan logika terlihat lebih awal.** Jalur yang lupa ditangani, atau
  perulangan yang tidak pernah berhenti, lebih mudah terlihat di gambar
  daripada di tengah puluhan baris kode.
- **Tidak bergantung bahasa.** Flowchart yang sama bisa diterjemahkan ke C,
  Java, atau bahasa apa pun.

Itu sebabnya kelas KSP dimulai dari flowchart sebelum menyentuh kode. Kalau
alurnya sudah benar, kodenya tinggal mengikuti.$ksp$, array[$ksp$tips$ksp$, $ksp$flowchart$ksp$, $ksp$pemula$ksp$]::text[]),
  ($ksp$n-21$ksp$, $ksp$apa-itu-algoritma$ksp$, $ksp$Apa Itu Algoritma? Kamu Sudah Memakainya Setiap Hari$ksp$, $ksp$2026-09-10$ksp$, $ksp$fakta$ksp$, $ksp$https://bgrgkqrolpgcmbdlruzt.supabase.co/storage/v1/object/public/media/berita/c3ddce61-de37-4ac0-b010-839db30d468d.jpg$ksp$, $ksp$Dari resep mi instan sampai mencari nama di daftar hadir. Algoritma tidak serumit namanya, dan asal-usul katanya pun menarik.$ksp$, $ksp$Tim KSP$ksp$, $ksp$Kata "algoritma" sering terdengar rumit, seolah hanya dipahami ilmuwan
komputer. Padahal kamu sudah menjalankan algoritma setiap hari, jauh sebelum
belajar pemrograman.

## Algoritma adalah langkah-langkah

Algoritma adalah urutan langkah yang jelas untuk menyelesaikan suatu masalah.
Syaratnya sederhana: setiap langkah harus jelas, urutannya tepat, dan
langkah-langkah itu harus berakhir.

Resep memasak mi instan adalah contoh algoritma:

1. Rebus air sampai mendidih.
2. Masukkan mi, tunggu tiga menit.
3. Tiriskan, lalu campur dengan bumbu.
4. Sajikan.

Kalau urutannya ditukar, misalnya bumbu dicampur sebelum air mendidih,
hasilnya berantakan. Begitu juga dengan program.

## Dari mana namanya?

Kata "algoritma" berasal dari nama **Al-Khwarizmi**, matematikawan Persia
abad ke-9. Tulisannya tentang cara berhitung dengan angka memperkenalkan
sistem bilangan yang kita pakai sekarang ke dunia Barat, dan namanya lama-lama
berubah menjadi istilah untuk langkah-langkah penyelesaian masalah.

## Satu masalah, banyak algoritma

Untuk satu masalah, biasanya ada lebih dari satu algoritma. Misalnya mencari
nama "Rena" di daftar hadir yang tidak berurutan:

- **Cara pertama:** baca nama satu per satu dari atas sampai ketemu.
- **Cara kedua:** kalau daftarnya sudah urut abjad, buka bagian tengah, lihat
  apakah "Rena" ada di sebelum atau sesudahnya, lalu ulangi pada separuh yang
  tersisa.

Cara kedua jauh lebih cepat untuk daftar yang panjang, tapi hanya bisa dipakai
kalau daftarnya sudah terurut. Memilih algoritma yang tepat untuk situasi
yang tepat adalah salah satu keterampilan terpenting seorang programmer.

## Algoritma dan program

Algoritma adalah **ide** langkah-langkahnya. Program adalah algoritma yang
**ditulis** dalam bahasa yang dimengerti komputer, seperti C. Itu sebabnya
belajar memrogram sebenarnya adalah belajar dua hal: menyusun langkah yang
benar, lalu menuliskannya dengan tepat.$ksp$, array[$ksp$fakta$ksp$, $ksp$algoritma$ksp$, $ksp$dasar$ksp$]::text[]),
  ($ksp$n-22$ksp$, $ksp$bug-pertama-serangga-sungguhan$ksp$, $ksp$Bug Pertama di Dunia Adalah Serangga Sungguhan$ksp$, $ksp$2026-09-06$ksp$, $ksp$fakta$ksp$, $ksp$https://bgrgkqrolpgcmbdlruzt.supabase.co/storage/v1/object/public/media/berita/d5456aed-1982-4fcc-99fb-1ff88653c2c8.jpg$ksp$, $ksp$Tahun 1947, sebuah komputer bermasalah karena seekor ngengat terjepit di dalamnya. Kisah di balik istilah bug dan debugging.$ksp$, $ksp$Tim KSP$ksp$, $ksp$Kita menyebut kesalahan di program sebagai *bug*, yang artinya serangga. Tapi
dari mana istilah itu berasal? Ada satu kejadian terkenal yang sampai sekarang
sering diceritakan.

## Ngengat di dalam komputer

Pada 9 September 1947, tim yang mengoperasikan komputer Harvard Mark II di
Amerika Serikat menemukan masalah pada mesin mereka. Setelah diperiksa,
penyebabnya ternyata seekor **ngengat** yang terjepit di salah satu relai
komputer.

Ngengat itu diambil, lalu ditempel dengan selotip di buku catatan kerja tim,
disertai tulisan yang kurang lebih berarti "kasus pertama bug yang benar-benar
ditemukan". Halaman catatan itu masih disimpan sampai sekarang di museum
Smithsonian.

## Istilahnya sebenarnya sudah ada lebih dulu

Ada satu hal yang sering terlewat: kata *bug* untuk menyebut gangguan pada
mesin sudah dipakai para insinyur jauh sebelum 1947, bahkan sejak zaman
Thomas Edison. Justru karena istilahnya sudah umum, tim itu merasa lucu
menemukan "bug" yang benar-benar berupa serangga.

Kisah ini sering dikaitkan dengan **Grace Hopper**, salah satu pelopor
pemrograman yang bekerja dengan komputer Mark, dan dialah yang membuat cerita
ini terkenal.

## Dari *bug* ke *debugging*

Dari istilah itu lahir kata **debugging**: proses mencari dan membuang bug
dari program. Kalau kamu pernah menambahkan `printf` di tengah kode untuk
melihat nilai variabel, kamu sudah melakukan debugging.

Bedanya, bug zaman sekarang tidak bisa diambil dengan pinset. Kebanyakan bug
berasal dari hal kecil: titik koma yang salah tempat, `=` yang seharusnya
`==`, atau indeks array yang kelebihan satu. Tapi prinsipnya tetap sama
seperti tahun 1947: periksa dengan teliti sampai penyebabnya ketemu.$ksp$, array[$ksp$fakta$ksp$, $ksp$sejarah$ksp$, $ksp$debugging$ksp$]::text[]),
  ($ksp$n-23$ksp$, $ksp$bilangan-biner-cara-komputer-menghitung$ksp$, $ksp$Bilangan Biner: Cara Komputer Menghitung$ksp$, $ksp$2026-09-04$ksp$, $ksp$fakta$ksp$, $ksp$https://bgrgkqrolpgcmbdlruzt.supabase.co/storage/v1/object/public/media/berita/7dc7a100-ef37-4cce-a218-9d781555fb71.jpg$ksp$, $ksp$Semua yang ada di komputer pada akhirnya hanyalah deretan 0 dan 1. Begini cara membacanya, dan cara mengubah angka biasa menjadi biner.$ksp$, $ksp$Tim KSP$ksp$, $ksp$Semua yang ada di komputer, mulai dari angka, huruf, foto, sampai video,
pada akhirnya disimpan sebagai deretan **0 dan 1**. Sistem bilangan yang hanya
memakai dua angka ini disebut bilangan biner.

## Kenapa hanya 0 dan 1?

Komputer dibangun dari jutaan komponen elektronik kecil yang hanya punya dua
keadaan: mengalirkan listrik atau tidak. Dua keadaan itu paling mudah dan
paling andal dibedakan, jadi dipakailah dua angka: 1 untuk "ada listrik" dan
0 untuk "tidak ada".

## Membaca bilangan biner

Di bilangan desimal yang biasa kita pakai, setiap posisi bernilai sepuluh
kali posisi di kanannya: satuan, puluhan, ratusan. Di biner, setiap posisi
bernilai **dua kali** posisi di kanannya:

| Posisi | 8 | 4 | 2 | 1 |
| --- | --- | --- | --- | --- |
| Biner `1101` | 1 | 1 | 0 | 1 |

Jumlahkan nilai posisi yang berisi 1: 8 + 4 + 1 = **13**. Jadi `1101` dalam
biner sama dengan 13 dalam desimal.

## Mengubah desimal ke biner

Caranya: bagi terus dengan 2, catat sisanya, lalu baca dari bawah ke atas.
Contoh untuk 13:

| Pembagian | Hasil | Sisa |
| --- | --- | --- |
| 13 ÷ 2 | 6 | 1 |
| 6 ÷ 2 | 3 | 0 |
| 3 ÷ 2 | 1 | 1 |
| 1 ÷ 2 | 0 | 1 |

Dibaca dari bawah: `1101`. Cocok dengan contoh sebelumnya.

Langkah ini juga bisa jadi latihan perulangan di C: gunakan `% 2` untuk
mengambil sisa dan `/ 2` untuk membagi, ulangi sampai angkanya habis.

## Bit dan byte

Satu angka biner disebut **bit**. Delapan bit disebut satu **byte**. Dengan
delapan bit, ada 256 kombinasi berbeda, dari `00000000` sampai `11111111`,
cukup untuk menyimpan satu huruf. Itu sebabnya ukuran berkas dihitung dalam
byte, kilobyte, megabyte, dan seterusnya.

Jadi saat kamu menyimpan tugas berukuran 2 kilobyte, sebenarnya kamu
menyimpan sekitar enam belas ribu angka 0 dan 1.$ksp$, array[$ksp$fakta$ksp$, $ksp$biner$ksp$, $ksp$dasar$ksp$]::text[]),
  ($ksp$n-24$ksp$, $ksp$compiler-vs-interpreter$ksp$, $ksp$Compiler vs Interpreter: Apa Bedanya?$ksp$, $ksp$2026-09-01$ksp$, $ksp$fakta$ksp$, $ksp$https://bgrgkqrolpgcmbdlruzt.supabase.co/storage/v1/object/public/media/berita/f4d660ef-b55f-4474-bd7b-4794ce38d1f6.jpg$ksp$, $ksp$Kenapa C harus di-compile sementara Python bisa langsung dijalankan? Dua cara komputer menerjemahkan kode, dijelaskan dengan analogi buku.$ksp$, $ksp$Tim KSP$ksp$, $ksp$Komputer sebenarnya hanya mengerti bahasa mesin, yaitu deretan angka yang
nyaris mustahil dibaca manusia. Kode yang kita tulis di C atau Python harus
diterjemahkan lebih dulu. Ada dua cara utama melakukannya: dengan
**compiler** atau dengan **interpreter**.

## Compiler: terjemahkan semuanya dulu

Compiler membaca **seluruh** kode programmu, lalu menerjemahkannya sekaligus
menjadi program yang siap dijalankan. Di Windows, hasilnya berupa berkas
`.exe`.

Itulah yang terjadi saat kamu menekan **Compile** di Dev-C++. Kalau ada
kesalahan di mana pun, compiler menolak dan menampilkan daftar error. Kalau
berhasil, berkas `.exe` bisa dijalankan berkali-kali tanpa perlu
diterjemahkan ulang.

Bahasa yang umumnya memakai compiler: **C**, C++, dan Go.

## Interpreter: terjemahkan sambil jalan

Interpreter membaca kode **baris demi baris**, menerjemahkan, lalu langsung
menjalankannya. Tidak ada berkas `.exe` yang dihasilkan. Kalau ada kesalahan
di baris ke-50, program tetap berjalan sampai baris ke-49, lalu berhenti.

Bahasa yang umumnya memakai interpreter: **Python**, JavaScript, dan PHP.

## Seperti menerjemahkan buku

Bayangkan kamu punya buku berbahasa asing.

- **Compiler** seperti penerjemah yang menerjemahkan seluruh buku dulu,
  baru memberikannya kepadamu. Butuh waktu di awal, tapi setelah itu kamu bisa
  membacanya dengan lancar kapan saja.
- **Interpreter** seperti penerjemah yang duduk di sebelahmu dan
  menerjemahkan kalimat demi kalimat sambil kamu membaca. Bisa langsung mulai,
  tapi setiap kali membaca ulang, semuanya harus diterjemahkan lagi.

## Mana yang lebih baik?

Tidak ada yang lebih baik secara mutlak.

| | Compiler | Interpreter |
| --- | --- | --- |
| Kecepatan program | umumnya lebih cepat | umumnya lebih lambat |
| Menemukan kesalahan | sebelum program jalan | saat baris itu dijalankan |
| Mencoba kode kecil | harus compile dulu | bisa langsung dicoba |

Program C terkenal cepat salah satunya karena sudah diterjemahkan penuh ke
bahasa mesin sebelum dijalankan. Sementara Python disukai pemula karena kodenya
bisa langsung dicoba tanpa proses compile.

Batasnya pun kini tidak lagi setegas dulu. Java, misalnya, memakai gabungan
keduanya. Tapi memahami dua cara dasar ini akan membantumu mengerti apa yang
sebenarnya terjadi setiap kali kamu menekan tombol Compile.$ksp$, array[$ksp$fakta$ksp$, $ksp$compiler$ksp$, $ksp$dasar$ksp$]::text[]),
  ($ksp$n-25$ksp$, $ksp$tips-belajar-ngoding-tidak-cepat-menyerah$ksp$, $ksp$Tips Belajar Ngoding Supaya Tidak Cepat Menyerah$ksp$, $ksp$2026-08-27$ksp$, $ksp$tips$ksp$, $ksp$https://bgrgkqrolpgcmbdlruzt.supabase.co/storage/v1/object/public/media/berita/b1f5e90a-d433-4fbd-b903-528ce17d9b90.jpg$ksp$, $ksp$Error tidak habis-habis dan teman terasa jauh di depan? Tujuh kebiasaan kecil supaya semester pertama pemrograman terasa lebih ringan.$ksp$, $ksp$Tim KSP$ksp$, $ksp$Hampir semua orang pernah merasa ingin berhenti di minggu-minggu awal belajar
pemrograman. Errornya tidak habis-habis, soalnya terasa asing, dan teman lain
kelihatannya sudah jauh di depan. Kabar baiknya: perasaan itu normal, dan ada
cara untuk melewatinya.

## 1. Ketik sendiri, jangan hanya dibaca

Membaca contoh kode terasa mudah. Mengetiknya sendiri ternyata lain cerita.
Saat mengetik, kamu akan menemukan detail yang terlewat saat membaca: titik
koma, tanda kurung, atau huruf besar-kecil. Detail-detail itulah yang
membangun pemahaman.

## 2. Pecah soal jadi bagian kecil

Soal yang panjang terasa menakutkan kalau dilihat utuh. Pecah jadi langkah
kecil: baca input dulu, pastikan benar dengan mencetaknya, baru lanjut ke
perhitungan. Setiap langkah kecil yang berhasil memberi semangat untuk
langkah berikutnya.

## 3. Error itu petunjuk, bukan kegagalan

Programmer berpengalaman pun melihat error setiap hari. Bedanya, mereka
membaca pesannya dengan tenang. Setiap error yang berhasil kamu perbaiki
adalah hal yang tidak akan membuatmu bingung lagi di lain waktu.

## 4. Coba dulu 20 menit, baru bertanya

Berusaha sendiri itu penting, tapi terjebak berjam-jam tidak ada gunanya.
Coba dulu sekitar 20 menit. Kalau masih buntu, tanyakan ke teman atau tentor,
sambil menjelaskan apa yang sudah kamu coba. Sering kali, saat menjelaskan
masalahnya, kamu justru menemukan jawabannya sendiri.

## 5. Sedikit tapi rutin

Belajar 30 menit setiap hari jauh lebih efektif daripada lima jam sekaligus
sekali seminggu. Otak butuh waktu untuk mencerna, dan kebiasaan kecil yang
rutin lebih mudah dipertahankan.

## 6. Bandingkan dengan dirimu yang kemarin

Setiap orang punya titik awal yang berbeda. Ada yang sudah belajar sejak SMA,
ada yang baru pertama kali melihat kode. Yang penting bukan seberapa jauh kamu
dibanding orang lain, tapi seberapa jauh kamu dibanding dirimu minggu lalu.

## 7. Jangan belajar sendirian

Belajar bersama teman membuat kesulitan terasa lebih ringan. Itu juga alasan
KSP ada: supaya tidak ada yang harus melewati semester pertama pemrograman
sendirian.$ksp$, array[$ksp$tips$ksp$, $ksp$belajar$ksp$, $ksp$pemula$ksp$]::text[]),
  ($ksp$n-14$ksp$, $ksp$kebiasaan-kecil-kode-c-rapi$ksp$, $ksp$Lima Kebiasaan Kecil Supaya Kode C Lebih Rapi$ksp$, $ksp$2026-09-24$ksp$, $ksp$tips$ksp$, $ksp$https://bgrgkqrolpgcmbdlruzt.supabase.co/storage/v1/object/public/media/berita/1ab11745-52ea-45a8-88aa-ec7bc33a2e59.jpg$ksp$, $ksp$Kode yang rapi lebih mudah dibaca, lebih mudah diperiksa, dan lebih mudah kamu perbaiki sendiri. Lima kebiasaan kecil yang dampaknya besar.$ksp$, $ksp$Tim KSP$ksp$, $ksp$Kode yang rapi bukan soal gaya-gayaan. Kode yang rapi lebih mudah dibaca, lebih
mudah diperiksa tentor, dan yang paling penting, lebih mudah kamu perbaiki
sendiri saat ada yang salah. Berikut lima kebiasaan kecil yang dampaknya besar.

## 1. Indentasi yang konsisten

Setiap kali masuk ke dalam blok kurung kurawal, geser ke kanan satu tingkat.
Dengan begitu, kamu bisa melihat sekilas bagian mana yang ada di dalam `if` dan
mana yang di dalam perulangan.

```c
for (i = 0; i < n; i++) {
    if (nilai[i] > 70) {
        lulus++;
    }
}
```

Bandingkan kalau semuanya ditulis rata kiri. Mencari kurung yang lupa ditutup
jadi jauh lebih sulit.

## 2. Nama variabel yang menjelaskan isinya

`jumlahMahasiswa` lebih jelas daripada `jm`, apalagi `x`. Nama yang jelas membuat
kode bisa dibaca seperti kalimat, dan kamu tidak perlu mengingat-ingat arti
setiap singkatan. Pengecualiannya adalah variabel penghitung perulangan seperti
`i` dan `j`, yang memang sudah umum dipakai.

## 3. Beri nilai awal pada variabel

Di C, variabel yang dibuat di dalam fungsi tanpa nilai awal isinya acak, bukan
nol.

```c
int total;      // isinya tidak bisa ditebak
int total = 0;  // aman
```

Lupa memberi nilai awal adalah salah satu penyebab paling umum hasil
penjumlahan yang tiba-tiba aneh.

## 4. Komentar untuk menjelaskan "kenapa"

Kode sudah menunjukkan *apa* yang dilakukan. Komentar paling berguna saat
menjelaskan *kenapa* kamu melakukannya:

```c
// dikali 1.0 supaya hasilnya pecahan, bukan pembagian bulat
double rata = total * 1.0 / n;
```

## 5. Biarkan compiler membantumu

Nyalakan `-Wall` supaya compiler memperingatkan hal-hal yang mencurigakan,
misalnya variabel yang dibuat tapi tidak pernah dipakai. Di Dev-C++, buka
**Tools → Compiler Options**, centang **Add the following commands when calling
the compiler**, lalu isi dengan `-Wall`.

Anggap setiap warning sebagai pekerjaan rumah yang harus diselesaikan, bukan
tulisan yang boleh diabaikan.$ksp$, array[$ksp$tips$ksp$, $ksp$pemula$ksp$, $ksp$gaya-kode$ksp$]::text[]),
  ($ksp$n-13$ksp$, $ksp$debugging-pakai-printf$ksp$, $ksp$Debugging Pakai printf: Cara Paling Sederhana Menemukan Bug$ksp$, $ksp$2026-09-20$ksp$, $ksp$tips$ksp$, $ksp$https://bgrgkqrolpgcmbdlruzt.supabase.co/storage/v1/object/public/media/berita/00111d5a-7bbe-4182-a423-23cd0e53f258.jpg$ksp$, $ksp$Programnya jalan tapi hasilnya salah, dan tidak ada pesan error. Cetak isi variabelnya, dan lihat sendiri apa yang sebenarnya terjadi.$ksp$, $ksp$Tim KSP$ksp$, $ksp$Programmu sudah bisa dikompilasi, tapi hasilnya salah. Tidak ada pesan error, dan
kamu tidak tahu harus mulai dari mana. Di sinilah teknik paling sederhana dan
paling sering dipakai programmer berguna: **mencetak isi variabel untuk melihat
apa yang sebenarnya terjadi.**

## Idenya sederhana

Bug terjadi karena ada perbedaan antara apa yang kamu *kira* dikerjakan program
dan apa yang *benar-benar* dikerjakannya. Dengan menambahkan `printf` di
tempat-tempat penting, kamu bisa melihat langsung nilainya, alih-alih menebak.

## Contoh: jumlah yang salah

Misalnya program ini seharusnya menjumlahkan 1 sampai 5, tapi hasilnya tidak
sesuai harapan:

```c
int i;
int total = 0;
for (i = 1; i < 5; i++) {
    total += i;
}
printf("%d\n", total);
```

Tambahkan satu baris di dalam perulangan:

```c
for (i = 1; i < 5; i++) {
    total += i;
    printf("i = %d, total = %d\n", i, total);
}
```

Keluarannya langsung memperlihatkan masalahnya: `i` berhenti di 4, bukan 5.
Kondisinya seharusnya `i <= 5`.

## Tips supaya lebih efektif

1. **Beri label.** Tulis `printf("i = %d\n", i)`, bukan hanya `printf("%d\n", i)`.
   Kalau ada banyak baris keluaran, kamu tahu mana yang mana.
2. **Cetak sebelum dan sesudah.** Kalau curiga pada satu bagian, cetak nilainya
   sebelum dan sesudah bagian itu. Dari situ kelihatan di mana nilainya mulai
   salah.
3. **Selalu akhiri dengan `\n`.** Keluaran tanpa baris baru kadang tertahan dan
   tidak langsung muncul, apalagi kalau programnya berhenti mendadak.
4. **Persempit sedikit demi sedikit.** Mulai dari beberapa titik, lalu tambah
   `printf` di sekitar bagian yang mencurigakan sampai ketemu baris penyebabnya.

## Jangan lupa dihapus

Setelah bugnya ketemu, hapus lagi semua `printf` tambahan. Kalau programmu
dinilai dari keluarannya, satu baris ekstra saja bisa membuat jawaban yang
sebenarnya benar dianggap salah.$ksp$, array[$ksp$tips$ksp$, $ksp$debugging$ksp$, $ksp$printf$ksp$]::text[]),
  ($ksp$n-12$ksp$, $ksp$trik-printf-yang-jarang-diketahui$ksp$, $ksp$Trik printf yang Jarang Diketahui$ksp$, $ksp$2026-09-16$ksp$, $ksp$tips$ksp$, $ksp$https://bgrgkqrolpgcmbdlruzt.supabase.co/storage/v1/object/public/media/berita/566f4709-6d64-494e-9d98-9de42229c288.jpg$ksp$, $ksp$Mengatur lebar kolom, mengisi dengan nol, mencetak tanda persen, sampai fakta bahwa printf ternyata mengembalikan nilai.$ksp$, $ksp$Tim KSP$ksp$, $ksp$`printf` adalah fungsi pertama yang dipelajari hampir semua orang. Tapi banyak
yang hanya memakai `%d` dan `%s`, padahal `printf` bisa melakukan jauh lebih
banyak. Berikut beberapa trik yang berguna, terutama untuk soal yang meminta
format keluaran tertentu.

## Mengatur lebar kolom

Angka di antara `%` dan huruf format menentukan lebar minimal:

```c
printf("[%5d]\n", 42);   // [   42]
printf("[%-5d]\n", 42);  // [42   ]
printf("[%05d]\n", 42);  // [00042]
```

- `%5d` menambah spasi di kiri sampai lebarnya 5 karakter.
- `%-5d` sama, tapi rata kiri.
- `%05d` mengisi dengan nol, cocok untuk nomor urut seperti `00042`.

Trik ini sangat membantu saat membuat tabel yang kolomnya harus lurus.

## Membatasi angka di belakang koma

```c
printf("[%.2f]\n", 3.14159);   // [3.14]
printf("[%8.2f]\n", 3.14159);  // [    3.14]
```

`%.2f` mencetak tepat dua angka di belakang koma dan sudah membulatkan sendiri.
Keduanya bisa digabung: `%8.2f` berarti lebar 8, dengan dua angka desimal.

## Mencetak tanda persen

Karena `%` punya arti khusus, untuk mencetak tanda persen yang sebenarnya, tulis
dua kali:

```c
printf("diskon 50%%\n");  // diskon 50%
```

## Lebar kolom dari variabel

Kalau lebarnya baru diketahui saat program berjalan, pakai `*`:

```c
int lebar = 6;
printf("[%*d]\n", lebar, 42);  // [    42]
```

## Bonus: angka dalam bentuk lain

```c
printf("%x %o\n", 255, 8);  // ff 10
printf("%c\n", 65);         // A
```

`%x` mencetak bilangan heksadesimal, `%o` oktal, dan `%c` mencetak karakter
dari kode ASCII-nya. Ternyata huruf `A` di komputer disimpan sebagai angka 65.

## `printf` juga mengembalikan nilai

Jarang ada yang tahu bahwa `printf` mengembalikan jumlah karakter yang dicetak:

```c
int n = printf("halo\n");
printf("%d\n", n);  // 5
```

Hasilnya 5: empat huruf ditambah satu karakter baris baru.$ksp$, array[$ksp$tips$ksp$, $ksp$printf$ksp$, $ksp$format$ksp$]::text[]),
  ($ksp$n-11$ksp$, $ksp$membaca-pesan-error-compiler$ksp$, $ksp$Membaca Pesan Error Compiler Tanpa Panik$ksp$, $ksp$2026-09-12$ksp$, $ksp$tips$ksp$, $ksp$https://bgrgkqrolpgcmbdlruzt.supabase.co/storage/v1/object/public/media/berita/3e9f10a7-259c-41ee-b11f-abda21917f6a.jpg$ksp$, $ksp$Pesan error itu teman: compiler memberi tahu letak masalahnya. Begini cara membacanya di Dev-C++, termasuk error for loop yang sering bikin bingung.$ksp$, $ksp$Tim KSP$ksp$, $ksp$Pertama kali melihat daftar pesan error itu menakutkan. Tapi pesan error
sebenarnya adalah teman: compiler sedang memberi tahu di mana masalahnya. Kamu
hanya perlu tahu cara membacanya. Contoh di artikel ini memakai Dev-C++, aplikasi
yang dipakai di kelas.

## Di mana pesan error muncul

Saat kamu menekan **Compile** (F9) dan ada yang salah, Dev-C++ membuka tab
**Compiler** di bagian bawah jendela. Isinya tabel dengan empat kolom:

| Line | Col | File | Message |
| --- | --- | --- | --- |
| 5 | 5 | galat.c | [Error] expected ';' before 'return' |

- **Line** adalah nomor baris tempat masalahnya ditemukan.
- **Col** adalah posisi kolomnya di baris itu.
- **Message** adalah penjelasannya. Awalan `[Error]` artinya program tidak bisa
  dijalankan sampai ini diperbaiki.

Klik dua kali baris pesannya, dan Dev-C++ langsung melompat ke baris kode yang
bermasalah.

## Tiga pesan yang paling sering muncul

**Lupa titik koma**

```c
printf("%d\n", jumlah)
return 0;
```

Pesannya: `expected ';' before 'return'`. Compiler baru sadar ada yang kurang saat
bertemu `return`, jadi baris yang ditunjuk sering kali baris *setelah* kesalahan
yang sebenarnya.

**Salah ketik nama variabel**

```c
int jumlah = 0;
printf("%d\n", jumlh);
```

Pesannya: `'jumlh' undeclared (first use in this function)`. Artinya nama
`jumlh` belum pernah dibuat. Periksa ejaannya, atau pastikan variabelnya sudah
dideklarasikan di atas.

**Deklarasi di dalam `for`**

```c
for (int i = 0; i < 5; i++) {
```

Pesannya: `'for' loop initial declarations are only allowed in C99 or C11 mode`.
Ini khas Dev-C++, yang secara bawaan memakai aturan C versi lama. Perbaikannya
mudah: deklarasikan variabelnya di luar `for`.

```c
int i;
for (i = 0; i < 5; i++) {
```

## Error dan warning itu berbeda

**Error** membuat program gagal dikompilasi. **Warning** (awalan `[Warning]`)
tidak menghentikan kompilasi, tapi hampir selalu menandakan ada yang salah.
Contoh paling klasik adalah lupa tanda `&` di `scanf`:

```c
scanf("%d", umur);
```

```
[Warning] format '%d' expects argument of type 'int *', but argument 2 has type 'int'
```

Program ini tetap bisa dijalankan, tapi hasilnya kacau atau langsung berhenti.
Supaya warning penting seperti ini selalu muncul, nyalakan `-Wall` di Dev-C++:
buka **Tools → Compiler Options**, centang **Add the following commands when
calling the compiler**, lalu isi dengan `-Wall`.

## Tiga kebiasaan yang membantu

1. **Perbaiki error pertama dulu.** Satu kesalahan bisa memicu banyak error lain
   di bawahnya. Sering kali, setelah error pertama diperbaiki, sisanya ikut hilang.
2. **Lihat juga baris sebelumnya.** Kalau baris yang ditunjuk terlihat benar,
   kesalahannya mungkin ada di baris tepat di atasnya.
3. **Kompilasi sesering mungkin.** Menulis lima baris lalu kompilasi jauh lebih
   mudah daripada menulis seratus baris lalu menghadapi dua puluh error sekaligus.$ksp$, array[$ksp$tips$ksp$, $ksp$compiler$ksp$, $ksp$pemula$ksp$]::text[]),
  ($ksp$n-10$ksp$, $ksp$fakta-unik-bahasa-c$ksp$, $ksp$Tujuh Fakta Unik tentang Bahasa C$ksp$, $ksp$2026-09-08$ksp$, $ksp$fakta$ksp$, $ksp$https://bgrgkqrolpgcmbdlruzt.supabase.co/storage/v1/object/public/media/berita/2c2fbd7c-f51c-4327-958c-a6e4a0c2bec2.jpg$ksp$, $ksp$Dari asal-usul namanya, program "Hello, world!" pertama, sampai keunikan kecil yang bikin programmer berpengalaman pun kaget.$ksp$, $ksp$Tim KSP$ksp$, $ksp$Di balik kesannya yang serius, bahasa C punya banyak cerita dan keunikan kecil.
Berikut tujuh di antaranya.

## 1. Namanya diambil dari huruf sebelumnya

C adalah penerus bahasa bernama **B**, buatan Ken Thompson di Bell Labs. B sendiri
turunan dari bahasa BCPL. Jadi nama C bukan singkatan apa-apa, hanya huruf
berikutnya setelah B.

## 2. "Hello, world!" dipopulerkan oleh buku C

Program pertama yang hampir semua orang tulis, yaitu mencetak `Hello, world!`,
dipopulerkan oleh buku *The C Programming Language* karya Brian Kernighan dan
Dennis Ritchie yang terbit tahun 1978. Sejak itu, hampir setiap tutorial bahasa
pemrograman dimulai dengan cara yang sama.

## 3. Kata kuncinya sedikit sekali

Standar C yang pertama (C89) hanya punya **32 kata kunci**, seperti `int`, `if`,
`for`, dan `return`. Bandingkan dengan bahasa modern yang bisa punya jauh lebih
banyak. C memang sengaja dibuat kecil.

## 4. `a[2]` sama dengan `2[a]`

Ini keunikan yang sering bikin orang kaget. Coba jalankan:

```c
int a[3] = {10, 20, 30};
printf("%d %d\n", a[2], 2[a]);
```

Keluarannya `30 30`. Di balik layar, C membaca `a[2]` sebagai "ambil nilai di
posisi a ditambah 2", dan penjumlahan bisa dibalik urutannya. Tentu saja, jangan
menulis seperti ini di tugasmu. Ini hanya fakta menarik.

## 5. `sizeof` bukan fungsi

`sizeof` terlihat seperti fungsi karena sering ditulis dengan kurung, tapi
sebenarnya ia operator, sama seperti `+` atau `*`. Untuk variabel, kurungnya
boleh tidak ditulis:

```c
int x = 5;
int ukuran = sizeof x;
printf("%d\n", ukuran);
```

## 6. C terus diperbarui

C bukan bahasa yang berhenti di tahun 1970-an. Standarnya terus diperbarui:
C89, C99, C11, C17, dan yang terbaru C23. Setiap versi menambahkan fitur baru
sambil tetap menjaga kode lama supaya masih bisa berjalan.

## 7. `return 0` di akhir `main` punya arti

Angka yang dikembalikan `main` dikirim ke sistem operasi. Angka `0` berarti
"program selesai dengan baik", sedangkan angka lain biasanya berarti ada masalah.
Sejak C99, kalau `main` selesai tanpa `return`, C otomatis menganggapnya
mengembalikan `0`.$ksp$, array[$ksp$fakta$ksp$, $ksp$sejarah$ksp$, $ksp$bahasa-c$ksp$]::text[]),
  ($ksp$n-09$ksp$, $ksp$kenapa-bahasa-c-masih-dipakai$ksp$, $ksp$Kenapa Bahasa C Masih Dipakai Sampai Sekarang$ksp$, $ksp$2026-09-02$ksp$, $ksp$fakta$ksp$, $ksp$https://bgrgkqrolpgcmbdlruzt.supabase.co/storage/v1/object/public/media/berita/196c9108-f12c-4f79-93a9-9b612ab10ffe.jpg$ksp$, $ksp$Umurnya sudah lebih dari lima puluh tahun, tapi C masih ada di Linux, Python, sampai mesin cuci. Ini alasannya.$ksp$, $ksp$Tim KSP$ksp$, $ksp$Umur bahasa C sudah lebih dari lima puluh tahun. Di dunia teknologi, itu setara
dengan zaman purba. Tapi sampai hari ini C masih diajarkan di hampir setiap
jurusan informatika, dan masih dipakai untuk membangun perangkat lunak yang kamu
pakai setiap hari. Kenapa bisa begitu?

## Lahir untuk membangun sistem operasi

C dibuat oleh Dennis Ritchie di Bell Labs pada awal 1970-an. Tujuannya sangat
praktis: menulis ulang sistem operasi Unix supaya tidak perlu ditulis dalam
bahasa mesin yang berbeda-beda untuk setiap komputer.

Hasilnya, C menjadi bahasa yang dekat dengan cara kerja komputer, tapi tetap bisa
dibaca manusia. Kombinasi itulah yang membuatnya bertahan.

## Diam-diam ada di mana-mana

Banyak perangkat lunak besar yang kamu kenal ditulis dengan C, atau punya inti
yang ditulis dengan C:

- **Linux**, sistem operasi yang menjalankan sebagian besar server di internet
  dan menjadi dasar Android, intinya ditulis dengan C.
- **Python**, bahasa yang terkenal mudah dipelajari, dijalankan oleh program yang
  juga ditulis dengan C.
- **Git**, alat yang dipakai hampir semua programmer untuk menyimpan riwayat kode.
- **SQLite**, database kecil yang ada di hampir setiap ponsel.
- Program di dalam **mesin cuci, remote AC, sampai kendaraan** banyak yang
  ditulis dengan C, karena C bisa berjalan di perangkat dengan memori yang sangat
  kecil.

## Pintu masuk ke bahasa lain

Kalau kamu sudah paham C, bahasa lain akan terasa familier. C++, Java, C#,
JavaScript, dan banyak bahasa lain meminjam gaya penulisan C: kurung kurawal untuk
blok kode, titik koma di akhir perintah, dan bentuk perulangan `for` yang sama.

## Mengajarkan cara komputer berpikir

Bahasa yang lebih modern banyak mengerjakan hal secara otomatis di belakang
layar. Itu memudahkan, tapi juga menyembunyikan cara kerjanya. C tidak
menyembunyikan banyak hal. Kamu harus menentukan sendiri tipe data setiap
variabel, dan memikirkan langkah demi langkah apa yang dikerjakan program.

Karena itu, belajar C memang terasa lebih menantang di awal. Tapi pemahaman yang
kamu dapat akan terbawa ke bahasa apa pun yang kamu pelajari sesudahnya.$ksp$, array[$ksp$fakta$ksp$, $ksp$sejarah$ksp$, $ksp$bahasa-c$ksp$]::text[]),
  ($ksp$n-06$ksp$, $ksp$bahaya-scanf-persen-s$ksp$, $ksp$Berhenti Menulis scanf Persen-s Tanpa Batas Lebar$ksp$, $ksp$2026-08-30$ksp$, $ksp$tutorial$ksp$, $ksp$https://bgrgkqrolpgcmbdlruzt.supabase.co/storage/v1/object/public/media/berita/964a775e-e74c-420d-a713-3e59b8a269ed.jpg$ksp$, $ksp$Satu baris yang sering muncul di program pemula, dan hampir selalu menyimpan masalah. Perbaikannya cuma satu angka, dan angkanya bukan yang kamu kira.$ksp$, $ksp$Tim KSP$ksp$, $ksp$Ada satu baris yang sering sekali muncul di program pemula, dan hampir selalu
menyimpan masalah:

```c
char nama[32];
scanf("%s", nama);
```

Baris ini membaca satu kata dari masukan ke dalam `nama`. Masalahnya, `scanf`
tidak tahu bahwa `nama` hanya punya ruang 32 byte. Kalau masukannya lebih panjang,
`scanf` tetap menulis, melewati ujung array, ke memori yang bukan miliknya.

## Kenapa ini tidak ketahuan saat diuji

Karena saat diuji, kamu mengetik nama yang pendek.

Buffer overflow tidak selalu membuat program berhenti. Yang tertimpa mungkin
variabel lain di stack, dan programnya tetap jalan dengan nilai yang diam-diam
berubah. Atau yang tertimpa adalah bagian yang belum dipakai, dan tidak terjadi
apa-apa sama sekali.

Kelas kesalahan inilah yang selama puluhan tahun jadi sumber kerentanan keamanan
paling umum di perangkat lunak yang ditulis dengan C.

## Perbaikannya satu angka

`scanf` menerima batas lebar tepat setelah tanda persen:

```c
char nama[32];
scanf("%31s", nama);
```

Angkanya 31, bukan 32. `scanf` menambahkan karakter nol di akhir, dan karakter itu
juga butuh tempat. Aturannya: **selalu satu kurang dari ukuran array.**

Ini yang paling sering meleset satu. Kalau kamu menulis `%32s` pada array
berukuran 32, kamu baru saja menggeser masalahnya satu byte, bukan
menghilangkannya.

## Untuk membaca satu baris penuh

`%s` berhenti di spasi pertama, jadi ia tidak bisa membaca kalimat. Untuk itu
pakai `fgets`, yang menerima ukuran buffer sebagai argumen:

```c
char baris[256];
if (fgets(baris, sizeof baris, stdin) == NULL) {
    return 1;
}
```

Perhatikan bahwa `fgets` ikut menyimpan karakter baris baru kalau muat. Untuk
sebagian besar soal, hal itu perlu dibuang sendiri.

## Kebiasaan yang layak dibawa

Setiap kali kamu menulis `%s` di dalam `scanf`, berhenti sebentar dan tanyakan
berapa ukuran tujuannya. Kalau kamu tidak bisa menjawabnya langsung, itu tanda
bahwa batasnya memang belum kamu pikirkan.$ksp$, array[$ksp$string$ksp$, $ksp$tutorial$ksp$, $ksp$keamanan$ksp$]::text[]),
  ($ksp$n-01$ksp$, $ksp$pendaftaran-anggota-baru-2026$ksp$, $ksp$Pendaftaran Anggota Baru Semester Ganjil 2026/2027 Dibuka$ksp$, $ksp$2026-08-24$ksp$, $ksp$pengumuman$ksp$, $ksp$https://bgrgkqrolpgcmbdlruzt.supabase.co/storage/v1/object/public/media/berita/03028986-34f7-4b14-aa0d-cceaaa4142d7.jpg$ksp$, $ksp$Terbuka untuk mahasiswa aktif UAJY semester 1 sebagai persiapan mata kuliah dasar pemrograman C, tanpa syarat kemampuan awal. Biaya Rp150.000 dengan cashback 70%.$ksp$, $ksp$Pengurus KSP$ksp$, $ksp$Pendaftaran anggota baru Kelompok Studi Pemrograman untuk semester ganjil
2026/2027 dibuka mulai hari ini sampai 11 September 2026. Pendaftaran terbuka
untuk mahasiswa aktif UAJY semester 1, tanpa syarat kemampuan awal.

## Persiapan untuk mata kuliah dasar pemrograman

Kelas KSP disusun untuk mempersiapkanmu menghadapi mata kuliah dasar pemrograman
berbahasa C. Materinya berjalan bertahap setiap minggu: dimulai dari flowchart,
lalu tipe data, pemilihan, perulangan, prosedur, fungsi, array, sampai record.

Belum pernah menulis satu baris kode pun? Tidak masalah. Kelasnya dimulai dari
nol, dengan tentor yang mendampingi dari pertemuan pertama.

## Apa yang kamu dapat

- Kelas rutin setiap Senin dan Selasa, 19.00–21.00 WIB, di Lab Komputasi
- Pendampingan dari tentor di setiap pertemuan
- Challenge mingguan yang mengikuti materi kelas
- Akses ke arsip modul dan soal latihan
- Sertifikat keanggotaan di akhir tahun ajaran, bisa ditukar SPAMA tipe organisasi

## Biaya

Biaya pendaftaran Rp150.000, dibayar sekali. Kalau presensimu memenuhi, 70%
(Rp105.000) dikembalikan sebagai cashback. Tidak ada iuran bulanan.

## Cara mendaftar

Isi formulir pendaftaran lewat tombol daftar di halaman gabung. Informasi lengkap
tentang syarat, alur, dan pertanyaan yang sering diajukan ada di sana juga.$ksp$, array[$ksp$pendaftaran$ksp$, $ksp$anggota-baru$ksp$, $ksp$kelas$ksp$]::text[]);

insert into public.challenges (id, slug, minggu, judul, tanggal_rilis, deadline, difficulty, topik, deskripsi_mdx, constraints, sample_io, hint_terkunci, total_peserta, tags) values
  ($ksp$c-03$ksp$, $ksp$durasi-praktikum$ksp$, 3, $ksp$Durasi Praktikum$ksp$, $ksp$2026-10-05$ksp$, $ksp$2026-10-11T23:59$ksp$, $ksp$MUDAH$ksp$, array[$ksp$tipe-data$ksp$]::text[], $ksp$Server praktikum mencatat lama setiap sesi dalam satuan detik. Angka seperti
`7384` memang tepat, tapi tidak ada yang bisa membacanya sekilas. Koordinator
lab ingin angka itu ditampilkan dalam jam, menit, dan detik.

Tugasmu menulis program yang membaca lama sesi dalam detik, lalu mencetaknya
dalam format yang mudah dibaca.

## Format masukan

Satu bilangan bulat `N`, lama sesi dalam detik.

## Format keluaran

Satu baris dengan format persis seperti ini:

```
J jam M menit D detik
```

`M` dan `D` selalu di antara 0 dan 59. `J` boleh lebih dari 23.

## Catatan

Soal ini cukup diselesaikan dengan variabel, `scanf`, `printf`, dan operator
aritmetika. Tidak perlu `if` ataupun perulangan.$ksp$, array[$ksp$0 <= N <= 1000000$ksp$, $ksp$Keluaran persis satu baris$ksp$, $ksp$Batas waktu 1 detik, batas memori 64 MB$ksp$]::text[], $ksp$[{"input":"7384","output":"2 jam 3 menit 4 detik","penjelasan":"7384 detik = 2 × 3600 + 3 × 60 + 4."},{"input":"59","output":"0 jam 0 menit 59 detik","penjelasan":"Kurang dari satu menit, jam dan menitnya tetap dicetak sebagai 0."},{"input":"86400","output":"24 jam 0 menit 0 detik","penjelasan":"Satu hari penuh. Jam tidak dibatasi sampai 23."}]$ksp$::jsonb, array[$ksp$Satu jam sama dengan 3600 detik, satu menit 60 detik.$ksp$, $ksp$Operator / pada dua bilangan bulat membuang sisanya. Operator % justru mengambil sisanya.$ksp$, $ksp$Setelah jam diambil, sisa detiknya adalah N % 3600. Dari sisa itu baru hitung menitnya.$ksp$]::text[], 0, array[$ksp$pemanasan$ksp$, $ksp$aritmetika$ksp$]::text[]),
  ($ksp$c-04$ksp$, $ksp$nilai-akhir-semester$ksp$, 4, $ksp$Nilai Akhir Semester$ksp$, $ksp$2026-11-02$ksp$, $ksp$2026-11-08T23:59$ksp$, $ksp$MUDAH$ksp$, array[$ksp$pemilihan$ksp$]::text[], $ksp$Di akhir semester, setiap dosen menghitung nilai akhir dari tiga komponen:
tugas, UTS, dan UAS. Bobotnya 30%, 30%, dan 40%. Setelah itu nilai akhir
diubah menjadi nilai huruf.

Tugasmu menulis program yang melakukan keduanya — sekaligus menolak nilai yang
jelas salah ketik.

## Format masukan

Satu baris berisi tiga bilangan bulat: nilai tugas, UTS, dan UAS.

## Format keluaran

Kalau salah satu nilai di bawah 0 atau di atas 100, cetak:

```
nilai tidak valid
```

Kalau semua valid, cetak dua baris:

```
nilai akhir: X.XX
huruf: H
```

Nilai akhir dihitung sebagai `(3 × tugas + 3 × UTS + 4 × UAS) / 10`.

## Tabel huruf

| Nilai akhir | Huruf |
| --- | --- |
| 85 ke atas | A |
| 70 sampai di bawah 85 | B |
| 55 sampai di bawah 70 | C |
| 40 sampai di bawah 55 | D |
| di bawah 40 | E |$ksp$, array[$ksp$Ketiga nilai berupa bilangan bulat$ksp$, $ksp$Nilai di luar 0 sampai 100 dianggap tidak valid$ksp$, $ksp$Nilai akhir dicetak dengan tepat dua angka di belakang koma$ksp$]::text[], $ksp$[{"input":"80 75 90","output":"nilai akhir: 82.50\nhuruf: B","penjelasan":"(3 × 80 + 3 × 75 + 4 × 90) / 10 = 82.5, masuk rentang B."},{"input":"85 85 85","output":"nilai akhir: 85.00\nhuruf: A","penjelasan":"Tepat di batas bawah A tetap mendapat A."},{"input":"100 101 90","output":"nilai tidak valid","penjelasan":"Nilai UTS 101 di luar rentang, jadi tidak ada yang dihitung."}]$ksp$::jsonb, array[$ksp$Periksa validitas dulu. Kalau satu saja tidak valid, cetak pesannya dan selesai.$ksp$, $ksp$Urutkan pemeriksaan huruf dari batas tertinggi ke terendah dengan if – else if.$ksp$, $ksp$Bandingkan 3 × tugas + 3 × UTS + 4 × UAS dengan 850, 700, dan seterusnya supaya batasnya tidak meleset karena pecahan.$ksp$]::text[], 0, array[$ksp$if-else$ksp$, $ksp$nilai$ksp$]::text[]),
  ($ksp$c-05$ksp$, $ksp$tabungan-kas-kelas$ksp$, 5, $ksp$Tabungan Kas Kelas$ksp$, $ksp$2026-11-09$ksp$, $ksp$2026-11-15T23:59$ksp$, $ksp$MUDAH$ksp$, array[$ksp$perulangan$ksp$]::text[], $ksp$Kelas kita menabung untuk acara akhir semester. Setiap minggu bendahara
mencatat berapa yang masuk ke kas, dan setiap minggu pula ada yang bertanya:
"Sudah cukup belum?"

Tugasmu menulis program yang menjumlahkan semua setoran dan memberi tahu di
minggu ke berapa target pertama kali tercapai.

## Format masukan

Baris pertama berisi dua bilangan bulat: `N`, banyaknya minggu, dan `T`, target
tabungan.
Baris kedua berisi `N` bilangan bulat, setoran tiap minggu secara berurutan.

## Format keluaran

Baris pertama:

```
total: X
```

Baris kedua, kalau total pernah mencapai `T` atau lebih:

```
target tercapai di minggu ke-K
```

dengan `K` adalah minggu pertama saat total sementara sudah mencapai `T`.
Kalau sampai minggu terakhir target tidak tercapai:

```
target belum tercapai, kurang S
```

dengan `S` adalah selisih antara target dan total.$ksp$, array[$ksp$1 <= N <= 100$ksp$, $ksp$0 <= T <= 10000000$ksp$, $ksp$0 <= setoran <= 100000$ksp$]::text[], $ksp$[{"input":"5 100000\n20000 15000 30000 25000 10000","output":"total: 100000\ntarget tercapai di minggu ke-5","penjelasan":"Total baru menyentuh 100000 setelah setoran kelima."},{"input":"3 50000\n10000 5000 20000","output":"total: 35000\ntarget belum tercapai, kurang 15000","penjelasan":"Sampai minggu terakhir totalnya 35000, masih kurang 15000."},{"input":"1 0\n0","output":"total: 0\ntarget tercapai di minggu ke-1","penjelasan":"Target 0 sudah tercapai begitu minggu pertama dicatat."}]$ksp$::jsonb, array[$ksp$Tidak perlu menyimpan semua setoran. Cukup tambahkan ke total setiap kali dibaca.$ksp$, $ksp$Simpan minggu tercapainya di variabel tersendiri, dan isi hanya sekali — saat pertama kali total >= T.$ksp$, $ksp$Setoran tetap harus dibaca sampai habis walaupun target sudah tercapai lebih awal.$ksp$]::text[], 0, array[$ksp$for$ksp$, $ksp$akumulasi$ksp$]::text[]),
  ($ksp$c-06$ksp$, $ksp$segitiga-angka$ksp$, 6, $ksp$Segitiga Angka$ksp$, $ksp$2026-11-16$ksp$, $ksp$2026-11-22T23:59$ksp$, $ksp$SEDANG$ksp$, array[$ksp$perulangan$ksp$]::text[], $ksp$Papan pengumuman lab butuh hiasan untuk acara ulang tahun KSP, dan seseorang
mengusulkan segitiga dari angka. Menggambarnya dengan tangan butuh waktu lama.
Mencetaknya dengan program cukup beberapa baris.

Tugasmu mencetak segitiga angka setinggi `N`.

## Format masukan

Satu bilangan bulat `N`.

## Format keluaran

`N` baris. Baris ke-`i` (dimulai dari 1) berisi:

1. `N − i` spasi,
2. angka `1` sampai `i` secara menaik,
3. angka `i − 1` sampai `1` secara menurun.

Contoh untuk `N = 4`:

```
   1
  121
 12321
1234321
```

Jangan mencetak spasi di akhir baris.$ksp$, array[$ksp$1 <= N <= 9$ksp$, $ksp$Tidak ada spasi di akhir baris$ksp$]::text[], $ksp$[{"input":"3","output":"  1\n 121\n12321","penjelasan":"Baris ke-i diawali N − i spasi, naik dari 1 sampai i, lalu turun lagi ke 1."},{"input":"1","output":"1","penjelasan":"Satu baris, tanpa spasi di depan."},{"input":"5","output":"    1\n   121\n  12321\n 1234321\n123454321","penjelasan":"Baris terakhir selalu rata kiri."}]$ksp$::jsonb, array[$ksp$Satu perulangan luar untuk baris, lalu tiga perulangan dalam: spasi, angka naik, angka turun.$ksp$, $ksp$Banyaknya spasi di baris ke-i adalah N − i.$ksp$, $ksp$Angka turun dimulai dari i − 1, bukan dari i, supaya puncaknya tidak tercetak dua kali.$ksp$]::text[], 0, array[$ksp$nested-loop$ksp$, $ksp$pola$ksp$]::text[]),
  ($ksp$c-07$ksp$, $ksp$bingkai-papan-nama$ksp$, 7, $ksp$Bingkai Papan Nama$ksp$, $ksp$2026-11-23$ksp$, $ksp$2026-11-29T23:59$ksp$, $ksp$SEDANG$ksp$, array[$ksp$prosedur$ksp$, $ksp$perulangan$ksp$]::text[], $ksp$Panitia pameran proyek butuh bingkai papan nama untuk setiap meja. Ukurannya
berbeda-beda, tapi bentuknya selalu sama: tepi dari `#`, bagian dalam dari
titik.

Tugasmu mencetak beberapa bingkai sekaligus. Kodenya akan jauh lebih pendek
kalau bagian yang berulang dipindahkan ke prosedur sendiri.

## Format masukan

Baris pertama berisi `K`, banyaknya bingkai.
`K` baris berikutnya masing-masing berisi dua bilangan bulat: lebar dan tinggi.

## Format keluaran

Setiap bingkai dicetak dalam `tinggi` baris dengan `lebar` karakter per baris.
Baris pertama dan terakhir seluruhnya `#`. Baris di antaranya diawali dan
diakhiri `#`, dengan titik di tengahnya.

Contoh untuk lebar 6 dan tinggi 4:

```
######
#....#
#....#
######
```

Antar bingkai dipisahkan tepat satu baris kosong.$ksp$, array[$ksp$1 <= K <= 10$ksp$, $ksp$1 <= lebar, tinggi <= 50$ksp$, $ksp$Antar bingkai dipisahkan tepat satu baris kosong$ksp$]::text[], $ksp$[{"input":"1\n5 3","output":"#####\n#...#\n#####","penjelasan":"Tepi berupa #, bagian dalam berupa titik."},{"input":"2\n3 3\n1 1","output":"###\n#.#\n###\n\n#","penjelasan":"Dua bingkai, dipisahkan satu baris kosong. Bingkai 1 × 1 hanya satu #."},{"input":"1\n4 1","output":"####","penjelasan":"Tinggi 1 berarti hanya ada satu baris tepi."}]$ksp$::jsonb, array[$ksp$Buat satu prosedur yang mencetak satu baris: karakter tepi, isi sebanyak lebar − 2, lalu tepi lagi.$ksp$, $ksp$Bingkai = baris atas, tinggi − 2 baris tengah, baris bawah. Semuanya memanggil prosedur yang sama.$ksp$, $ksp$Hati-hati dengan lebar atau tinggi 1: tepi kanan dan baris bawah tidak boleh tercetak dua kali.$ksp$]::text[], 0, array[$ksp$prosedur$ksp$, $ksp$pola$ksp$]::text[]),
  ($ksp$c-08$ksp$, $ksp$tiga-angka-berurutan$ksp$, 8, $ksp$Tiga Angka Berurutan$ksp$, $ksp$2027-03-01$ksp$, $ksp$2027-03-07T23:59$ksp$, $ksp$SEDANG$ksp$, array[$ksp$prosedur$ksp$, $ksp$pointer$ksp$]::text[], $ksp$Prosedur yang kamu tulis minggu lalu bisa mencetak, tapi belum bisa mengubah
variabel milik `main`. Minggu ini kita perbaiki itu.

Tugasmu mengurutkan tiga bilangan dari kecil ke besar dengan sebuah prosedur,
dan menghitung berapa kali pertukaran terjadi.

## Aturan pengurutan

Pengurutan dilakukan dengan tiga perbandingan, persis dalam urutan ini:

1. bandingkan `a` dan `b`, tukar kalau `a > b`,
2. bandingkan `b` dan `c`, tukar kalau `b > c`,
3. bandingkan `a` dan `b` sekali lagi, tukar kalau `a > b`.

Setiap pertukaran dihitung satu. Dua bilangan yang sama tidak ditukar.

## Format masukan

Baris pertama berisi `T`, banyaknya kasus.
`T` baris berikutnya masing-masing berisi tiga bilangan bulat `a`, `b`, dan `c`.

## Format keluaran

Satu baris untuk setiap kasus:

```
a b c (J tukar)
```

dengan `a b c` sudah terurut menaik dan `J` banyaknya pertukaran.$ksp$, array[$ksp$1 <= T <= 100$ksp$, $ksp$-1000 <= a, b, c <= 1000$ksp$, $ksp$Pertukaran dihitung sesuai urutan perbandingan di soal$ksp$]::text[], $ksp$[{"input":"3\n3 1 2\n1 2 3\n9 5 1","output":"1 2 3 (2 tukar)\n1 2 3 (0 tukar)\n1 5 9 (3 tukar)","penjelasan":"Data yang sudah urut tidak butuh pertukaran. 9 5 1 butuh ketiganya."},{"input":"1\n4 4 2","output":"2 4 4 (2 tukar)","penjelasan":"Dua angka yang sama tidak ditukar, karena yang kiri tidak lebih besar."}]$ksp$::jsonb, array[$ksp$Prosedur tukar(int a, int b) tidak mengubah apa pun di main. Kirimkan alamatnya: tukar(&a, &b).$ksp$, $ksp$Di dalam prosedur, *a adalah isi variabel yang ditunjuk, bukan alamatnya.$ksp$, $ksp$Jumlah pertukaran juga bisa dikembalikan lewat parameter keluaran, sama seperti angkanya.$ksp$]::text[], 0, array[$ksp$parameter-keluaran$ksp$, $ksp$tukar$ksp$]::text[]),
  ($ksp$c-09$ksp$, $ksp$prima-di-rentang$ksp$, 9, $ksp$Prima di Rentang$ksp$, $ksp$2027-03-15$ksp$, $ksp$2027-03-21T23:59$ksp$, $ksp$SEDANG$ksp$, array[$ksp$fungsi$ksp$, $ksp$perulangan$ksp$]::text[], $ksp$Bilangan prima adalah bilangan lebih dari 1 yang hanya habis dibagi 1 dan
dirinya sendiri. Memeriksa satu bilangan itu mudah. Memeriksa ribuan bilangan
dengan kode yang sama berulang-ulang di dalam `main` itulah yang melelahkan.

Tugasmu mencetak semua bilangan prima di antara `A` dan `B`. Pisahkan
pemeriksaan prima ke dalam sebuah fungsi yang mengembalikan nilai.

## Format masukan

Satu baris berisi dua bilangan bulat `A` dan `B`.

## Format keluaran

Baris pertama berisi semua bilangan prima `p` dengan `A <= p <= B`, terurut
menaik dan dipisahkan satu spasi. Kalau tidak ada satu pun, cetak `-`.

Baris kedua:

```
jumlah: K
```

dengan `K` banyaknya bilangan prima yang ditemukan.$ksp$, array[$ksp$1 <= A <= B <= 100000$ksp$, $ksp$Bilangan prima dicetak menaik, dipisahkan satu spasi$ksp$, $ksp$Batas waktu 1 detik, batas memori 64 MB$ksp$]::text[], $ksp$[{"input":"10 30","output":"11 13 17 19 23 29\njumlah: 6","penjelasan":"Enam bilangan prima di antara 10 dan 30."},{"input":"1 10","output":"2 3 5 7\njumlah: 4","penjelasan":"1 bukan bilangan prima."},{"input":"24 28","output":"-\njumlah: 0","penjelasan":"Tidak ada prima di rentang ini, jadi baris pertama berisi tanda minus."}]$ksp$::jsonb, array[$ksp$Tulis fungsi int prima(int n) yang mengembalikan 1 kalau prima dan 0 kalau bukan.$ksp$, $ksp$Cukup coba pembagi dari 2 selama d × d <= n. Kalau tidak ada yang habis membagi, n prima.$ksp$, $ksp$Cetak spasi sebelum setiap bilangan kecuali yang pertama, supaya tidak ada spasi berlebih.$ksp$]::text[], 0, array[$ksp$fungsi$ksp$, $ksp$prima$ksp$]::text[]),
  ($ksp$c-10$ksp$, $ksp$suhu-rata-rata-laboratorium$ksp$, 10, $ksp$Suhu Rata-Rata Laboratorium$ksp$, $ksp$2027-04-26$ksp$, $ksp$2027-05-02T23:59$ksp$, $ksp$MUDAH$ksp$, array[$ksp$array$ksp$]::text[], $ksp$Laboratorium FTI memasang termometer digital di empat sudut ruang server. Setiap
jam, angkanya dicatat ke dalam satu berkas. Bagian kelistrikan ingin ringkasan
harian yang bisa dibaca sekilas, bukan deretan angka mentah.

Tugasmu menulis program yang membaca sederet suhu lalu mencetak rata-rata,
suhu tertinggi, dan suhu terendah.

## Format masukan

Baris pertama berisi satu bilangan bulat `N`, banyaknya pencatatan.
Baris kedua berisi `N` bilangan bulat yang dipisahkan spasi.

## Format keluaran

Tiga baris, dengan format persis seperti ini:

```
rata-rata: X.XX
tertinggi: Y
terendah: Z
```

Rata-rata dicetak dengan dua angka di belakang koma. Perhatikan bahwa pembagian
antar bilangan bulat di C membuang sisanya — `7 / 2` bernilai `3`, bukan `3.5`.
Kamu harus mengubah tipenya lebih dulu.$ksp$, array[$ksp$1 <= N <= 1000$ksp$, $ksp$-50 <= suhu <= 100$ksp$, $ksp$Rata-rata dicetak dengan tepat dua angka di belakang koma$ksp$, $ksp$Batas waktu 1 detik, batas memori 64 MB$ksp$]::text[], $ksp$[{"input":"5\n21 24 23 27 20","output":"rata-rata: 23.00\ntertinggi: 27\nterendah: 20","penjelasan":"Jumlah seluruh suhu 115, dibagi 5 menghasilkan tepat 23."},{"input":"1\n30","output":"rata-rata: 30.00\ntertinggi: 30\nterendah: 30","penjelasan":"Dengan satu data, ketiganya bernilai sama."},{"input":"4\n-3 -1 0 4","output":"rata-rata: 0.00\ntertinggi: 4\nterendah: -3","penjelasan":"Suhu negatif tetap dihitung. Totalnya nol, jadi rata-ratanya nol."}]$ksp$::jsonb, array[$ksp$Nilai awal untuk tertinggi dan terendah sebaiknya diambil dari elemen pertama, bukan dari 0.$ksp$, $ksp$total / n memakai pembagian bulat. Ubah salah satu operandnya ke double sebelum membagi.$ksp$, $ksp$printf("%.2f", x) mencetak dua angka di belakang koma dan sudah membulatkan sendiri.$ksp$]::text[], 0, array[$ksp$array$ksp$, $ksp$min-max$ksp$]::text[]),
  ($ksp$c-11$ksp$, $ksp$ipk-tertinggi-angkatan$ksp$, 11, $ksp$IPK Tertinggi Angkatan$ksp$, $ksp$2027-05-03$ksp$, $ksp$2027-05-09T23:59$ksp$, $ksp$SEDANG$ksp$, array[$ksp$record$ksp$]::text[], $ksp$Bagian akademik ingin memberi penghargaan untuk mahasiswa dengan IPK tertinggi
di angkatannya. Datanya ada: nama, NPM, dan IPK setiap mahasiswa. Ketiganya
milik orang yang sama, jadi sebaiknya disimpan bersama juga.

Tugasmu mencari mahasiswa dengan IPK tertinggi memakai `struct`.

## Format masukan

Baris pertama berisi bilangan bulat `N`.
`N` baris berikutnya masing-masing berisi nama tanpa spasi, NPM, dan IPK,
dipisahkan satu spasi.

## Format keluaran

Satu baris:

```
<nama> (<npm>) <ipk>
```

IPK dicetak dengan dua angka di belakang koma. Kalau ada beberapa mahasiswa
dengan IPK tertinggi yang sama, cetak yang paling dulu muncul di masukan.$ksp$, array[$ksp$1 <= N <= 1000$ksp$, $ksp$Nama tanpa spasi, panjang <= 32 karakter$ksp$, $ksp$NPM berupa 9 digit$ksp$, $ksp$0.00 <= IPK <= 4.00, dengan dua angka di belakang koma$ksp$]::text[], $ksp$[{"input":"3\nAlya 240711001 3.72\nBimo 240711002 3.85\nCitra 240711003 3.85","output":"Bimo (240711002) 3.85","penjelasan":"Bimo dan Citra seri. Yang dicetak adalah yang lebih dulu muncul."},{"input":"1\nDamar 240711010 2.50","output":"Damar (240711010) 2.50","penjelasan":"Satu mahasiswa otomatis menjadi yang tertinggi."}]$ksp$::jsonb, array[$ksp$Satu struct Mahasiswa berisi nama, NPM, dan IPK. NPM lebih aman disimpan sebagai teks.$ksp$, $ksp$Tidak perlu menyimpan semua data. Cukup dua variabel struct: yang sedang dibaca dan yang terbaik sejauh ini.$ksp$, $ksp$Struct bisa disalin utuh dengan satu penugasan: terbaik = sekarang;$ksp$]::text[], 0, array[$ksp$struct$ksp$, $ksp$maksimum$ksp$]::text[]),
  ($ksp$c-12$ksp$, $ksp$papan-peringkat-kelas$ksp$, 12, $ksp$Papan Peringkat Kelas$ksp$, $ksp$2027-05-18$ksp$, $ksp$2027-05-23T23:59$ksp$, $ksp$SULIT$ksp$, array[$ksp$array$ksp$, $ksp$record$ksp$]::text[], $ksp$Rekap nilai kelas selama ini disimpan sebagai dua array terpisah: satu untuk
nama, satu untuk nilai. Sistemnya bertahan sampai seseorang perlu mengurutkan
data itu, dan menyadari kedua array harus digeser bersamaan supaya indeksnya
tetap sejajar. Satu kali lupa, dan nilai orang lain menempel di namamu.

Tugasmu menyusun papan peringkat memakai array of record, lalu mengurutkannya.

## Format masukan

Baris pertama berisi bilangan bulat `N`.
`N` baris berikutnya masing-masing berisi sebuah nama tanpa spasi dan sebuah
nilai, dipisahkan satu spasi.

## Format keluaran

`N` baris, terurut berdasarkan nilai dari besar ke kecil. Kalau nilainya sama,
urutkan berdasarkan nama secara alfabetis menaik. Setiap baris berformat:

```
<peringkat>. <nama> <nilai>
```

Peringkat dimulai dari 1 dan selalu bertambah satu, termasuk saat nilainya sama.

## Catatan

Saat menukar dua elemen, tukar struct-nya utuh — nama dan nilai ikut pindah
bersama. Itulah keuntungan record dibanding dua array terpisah.

Untuk membandingkan dua nama, pakai `strcmp` dari `string.h`. Operator `<`
pada dua array karakter membandingkan alamatnya, bukan isinya.$ksp$, array[$ksp$1 <= N <= 100$ksp$, $ksp$Nama tanpa spasi, panjang <= 32 karakter$ksp$, $ksp$0 <= nilai <= 100$ksp$, $ksp$Urutan: nilai menurun, lalu nama menaik bila seri$ksp$]::text[], $ksp$[{"input":"4\nNadia 92\nGilang 95\nRangga 92\nIvana 88","output":"1. Gilang 95\n2. Nadia 92\n3. Rangga 92\n4. Ivana 88","penjelasan":"Nadia dan Rangga sama-sama 92, jadi urutannya ditentukan secara alfabetis."},{"input":"2\nBimo 70\nAlya 70","output":"1. Alya 70\n2. Bimo 70","penjelasan":"Nilainya identik, sehingga seluruh urutan ditentukan oleh nama."},{"input":"1\nDamar 100","output":"1. Damar 100","penjelasan":"Satu peserta tetap harus dicetak dengan format peringkat yang sama."}]$ksp$::jsonb, array[$ksp$Satu array of struct berisi nama dan nilai jauh lebih aman daripada dua array yang harus dijaga sejajar.$ksp$, $ksp$Bubble sort cukup untuk N <= 100: bandingkan dua elemen bersebelahan, tukar kalau urutannya salah.$ksp$, $ksp$strcmp(a, b) bernilai positif kalau a seharusnya di belakang b secara alfabetis.$ksp$]::text[], 0, array[$ksp$array-of-record$ksp$, $ksp$sorting$ksp$]::text[]);

insert into public.registration_rounds (buka, tutup) values
  ($ksp$2026-08-24T00:00$ksp$, $ksp$2026-09-11T23:59$ksp$);
