-- Generated by scripts/generate-seed.mts. Do not edit by hand.

truncate public.winners, public.challenges, public.news_posts, public.modules, public.sesi, public.registration_rounds restart identity cascade;

insert into public.modules (id, minggu, judul, rilis, tentor_pj, koordinator, ringkasan, berkas_url, tenggat) values
  ($ksp$mod-01$ksp$, 1, $ksp$Flowchart 1$ksp$, $ksp$2026-09-21$ksp$, array[$ksp$Sabrina$ksp$, $ksp$Eldha$ksp$]::text[], $ksp$Michelle$ksp$, $ksp$Simbol-simbol flowchart dan alur urut: terminal, proses, masukan dan keluaran, serta cara membaca diagram dari atas ke bawah.$ksp$, null, null),
  ($ksp$mod-02$ksp$, 2, $ksp$Flowchart 2$ksp$, $ksp$2026-09-28$ksp$, array[$ksp$Sabrina$ksp$, $ksp$Eldha$ksp$]::text[], $ksp$Michelle$ksp$, $ksp$Percabangan dan perulangan di flowchart: simbol keputusan, alur yang kembali ke atas, dan menelusuri diagram dengan tabel jejak.$ksp$, null, null),
  ($ksp$mod-03$ksp$, 3, $ksp$Tipe Data$ksp$, $ksp$2026-10-05$ksp$, array[$ksp$Boby$ksp$, $ksp$Kley$ksp$]::text[], $ksp$Kley$ksp$, $ksp$Aturan penamaan variabel, tipe data dasar di C, dan program sekuensial pertama dengan printf dan scanf.$ksp$, null, null),
  ($ksp$mod-04$ksp$, 4, $ksp$Pemilihan$ksp$, $ksp$2026-11-02$ksp$, array[$ksp$Dwi$ksp$, $ksp$Andrew$ksp$]::text[], $ksp$Kley$ksp$, $ksp$if, else if, else, dan switch — memilih jalur program berdasarkan kondisi.$ksp$, null, null),
  ($ksp$mod-05$ksp$, 5, $ksp$Perulangan 1$ksp$, $ksp$2026-11-09$ksp$, array[$ksp$Ardhya$ksp$, $ksp$Beto$ksp$]::text[], $ksp$Rena$ksp$, $ksp$for dan while: menghitung, menjumlahkan, dan menentukan kapan sebuah perulangan berhenti.$ksp$, null, null),
  ($ksp$mod-06$ksp$, 6, $ksp$Perulangan 2$ksp$, $ksp$2026-11-16$ksp$, array[$ksp$Doni$ksp$, $ksp$Rena$ksp$]::text[], $ksp$Rena$ksp$, $ksp$do-while, perulangan bersarang, serta break dan continue.$ksp$, null, null),
  ($ksp$mod-07$ksp$, 7, $ksp$Prosedur 1$ksp$, $ksp$2026-11-23$ksp$, array[$ksp$Richard$ksp$, $ksp$Petra$ksp$]::text[], $ksp$Richard$ksp$, $ksp$Memecah program menjadi prosedur: deklarasi, pemanggilan, dan parameter masukan.$ksp$, null, null),
  ($ksp$mod-08$ksp$, 8, $ksp$Prosedur 2$ksp$, $ksp$2027-03-01$ksp$, array[$ksp$Adit$ksp$, $ksp$Tristan$ksp$]::text[], $ksp$Richard$ksp$, $ksp$Parameter keluaran: kenapa nilai yang diubah di dalam prosedur tidak ikut kembali, dan cara memperbaikinya dengan pointer.$ksp$, null, null),
  ($ksp$mod-09$ksp$, 9, $ksp$Fungsi$ksp$, $ksp$2027-03-15$ksp$, array[$ksp$Nathan$ksp$, $ksp$Stella$ksp$]::text[], $ksp$Michelle$ksp$, $ksp$Fungsi yang mengembalikan nilai, return, dan kapan memilih fungsi daripada prosedur.$ksp$, null, null),
  ($ksp$mod-10$ksp$, 10, $ksp$Array$ksp$, $ksp$2027-04-26$ksp$, array[$ksp$Albert$ksp$, $ksp$Nadya$ksp$]::text[], $ksp$Audrey$ksp$, $ksp$Array satu dimensi: indeks, perulangan atas array, pencarian, dan nilai terbesar atau terkecil.$ksp$, null, null),
  ($ksp$mod-11$ksp$, 11, $ksp$Record$ksp$, $ksp$2027-05-03$ksp$, array[$ksp$Jolie$ksp$, $ksp$Epun$ksp$]::text[], $ksp$Audrey$ksp$, $ksp$struct sebagai record: mengelompokkan data yang saling berkaitan dan mengakses tiap field-nya.$ksp$, null, null),
  ($ksp$mod-12$ksp$, 12, $ksp$Array of Record$ksp$, $ksp$2027-05-18$ksp$, array[$ksp$Adit$ksp$]::text[], $ksp$Audrey$ksp$, $ksp$Menggabungkan keduanya: array berisi struct untuk data berbentuk tabel, seperti daftar nilai satu kelas.$ksp$, null, $ksp$2027-05-23T23:59$ksp$);

insert into public.sesi (id, judul, rilis, pj, ringkasan) values
  ($ksp$sesi-games$ksp$, $ksp$Games$ksp$, $ksp$2026-11-30$ksp$, $ksp$PH$ksp$, $ksp$Sesi santai di akhir semester ganjil: permainan dan kuis seputar materi yang sudah dipelajari. Tanpa modul dan tanpa tugas.$ksp$),
  ($ksp$sesi-review$ksp$, $ksp$Review Materi$ksp$, $ksp$2027-02-22$ksp$, $ksp$PH$ksp$, $ksp$Mengulang materi semester ganjil sebelum lanjut ke prosedur dan fungsi. Tanpa modul dan tanpa tugas.$ksp$);

insert into public.news_posts (id, slug, judul, tanggal, kategori, cover, excerpt, penulis, body_mdx, tags) values
  ($ksp$n-01$ksp$, $ksp$pendaftaran-anggota-baru-2026$ksp$, $ksp$Pendaftaran Anggota Baru Semester Ganjil 2026/2027 Dibuka$ksp$, $ksp$2026-08-24$ksp$, $ksp$pengumuman$ksp$, $ksp$https://picsum.photos/seed/ksp-berita-pendaftaran/1200/675$ksp$, $ksp$Terbuka untuk seluruh mahasiswa aktif UAJY, dari angkatan mana pun, tanpa syarat kemampuan awal. Semester lalu sembilan dari dua puluh tujuh anggota baru mendaftar tanpa pengalaman apa pun.$ksp$, $ksp$Salsabila Rahmawati$ksp$, $ksp$Pendaftaran anggota baru Kelompok Studi Pemrograman untuk semester ganjil
2026/2027 resmi dibuka mulai hari ini sampai 11 September 2026. Pendaftaran
terbuka untuk seluruh mahasiswa aktif UAJY, dari angkatan mana pun, dan tidak
ada syarat kemampuan awal.

## Tidak perlu bisa C dulu

Ini pertanyaan yang paling sering masuk ke kotak masuk kami, jadi mari
diselesaikan di awal: **kamu tidak perlu sudah bisa memrogram untuk mendaftar.**

Kelas dibagi menjadi dua jalur. Jalur pertama untuk yang belum pernah menulis
satu baris kode pun, dimulai dari cara membaca kode orang lain sebelum menulis
kode sendiri. Jalur kedua untuk yang sudah lewat mata kuliah Algoritma dan
Pemrograman dan ingin masuk ke manajemen memori, struktur data, dan pemrograman
sistem.

Semester lalu, sembilan dari dua puluh tujuh anggota baru mendaftar tanpa
pengalaman apa pun. Empat di antaranya sekarang mengisi papan peringkat
challenge mingguan.

## Apa yang kamu dapat

- Kelas rutin setiap Jumat sore, 90 menit, di ruang FTI 3.2
- Pendampingan satu tentor untuk empat peserta
- Challenge mingguan dengan pembahasan solusi terbuka
- Akses ke arsip materi dan rekaman kelas
- Sertifikat keanggotaan di akhir tahun ajaran

Seluruh kegiatan gratis. Tidak ada biaya pendaftaran dan tidak ada iuran bulanan.

## Alur pendaftaran

1. Isi formulir pendaftaran daring
2. Ikuti sesi perkenalan pada 12 September 2026
3. Pilih jalur kelas yang sesuai
4. Mulai kelas pertama pada 19 September 2026

Sesi perkenalan bukan seleksi. Tidak ada yang ditolak. Sesi itu ada supaya kamu
bisa bertanya sebelum memutuskan, dan supaya kami bisa menempatkanmu di jalur
yang tepat.

## Kenapa C, di tahun 2026

Pertanyaan yang wajar. Hampir tidak ada orang yang memulai proyek baru dengan C
sekarang, dan itu memang bukan tujuannya.

Alasannya sederhana: C tidak menyembunyikan apa pun. Ketika kamu menulis Python
atau JavaScript, banyak keputusan sudah diambil untukmu — kapan memori
dialokasikan, kapan dilepaskan, bagaimana sebuah string disimpan. Semua itu tetap
terjadi, hanya saja di tempat yang tidak kamu lihat.

Setelah satu semester di C, hal-hal itu berhenti jadi misteri. Dan ketika kamu
kembali ke bahasa yang kamu pakai sehari-hari, kamu membacanya dengan cara yang
berbeda.$ksp$, array[$ksp$pendaftaran$ksp$, $ksp$anggota-baru$ksp$, $ksp$kelas$ksp$]::text[]),
  ($ksp$n-02$ksp$, $ksp$pemenang-termuda-challenge$ksp$, $ksp$Theresia Menang Dua Minggu Beruntun di Musim Keduanya$ksp$, $ksp$2026-08-01$ksp$, $ksp$prestasi$ksp$, $ksp$https://picsum.photos/seed/ksp-berita-theresia/1200/675$ksp$, $ksp$Angkatan 2025, bergabung lewat challenge sebelum mengambil satu kelas pun, dan kini memimpin papan peringkat sepanjang masa dengan sembilan kemenangan.$ksp$, $ksp$Damar Aji Setiawan$ksp$, $ksp$Theresia Maharani Putri, mahasiswa angkatan 2025, memenangi challenge minggu
ketiga dan keempat berturut-turut. Dengan itu ia menjadi peserta angkatan pertama
pertama yang memenangi dua challenge beruntun sejak program ini dimulai pada 2025.

## Dua soal yang berbeda jauh

Minggu ketiga adalah soal string bertingkat MUDAH. Minggu keempat adalah soal
aritmetika bilangan besar bertingkat SEDANG, yang menuntut peserta menyimpan
hasilnya sebagai array digit karena tidak ada tipe bilangan bulat di C yang cukup
besar untuk menampung `25!`.

Keduanya diselesaikan dalam hitungan jam setelah soalnya terbit.

"Soal minggu ketiga saya kerjakan dua kali," katanya. "Percobaan pertama saya coba
membandingkan langsung sambil melompati tanda baca dari dua arah, dan langsung
berantakan begitu ada tanda baca beruntun. Saya buang, lalu tulis ulang dengan cara
yang lebih panjang tapi bisa saya baca sekali jalan."

Pendekatan itu, menurut Reza Maulana Hakim yang memeriksa submission tersebut,
adalah alasan utama ia menang. "Kode yang lebih pendek belum tentu kode yang lebih
benar. Dia tahu kapan harus membuang percobaan pertamanya, dan itu keterampilan
yang biasanya butuh waktu lama untuk tumbuh."

## Masuk lewat challenge

Theresia bergabung dengan KSP pada Februari 2026, empat bulan sebelum musim kedua
dimulai, dan tidak langsung mengambil kelas. Ia mengerjakan challenge lebih dulu.

"Saya ikut karena penasaran, bukan karena mau masuk kelompok studi. Baru setelah
soal SEGFAULT pertama saya tembus, saya sadar saya sudah belajar lebih banyak dalam
tiga minggu daripada satu semester sebelumnya."

Ia sekarang mengisi posisi staf di Divisi Akademik dan ikut menyiapkan sesi latihan
untuk anggota baru.

## Papan peringkat sementara

Dengan dua kemenangan musim ini, total kemenangan sepanjang masa Theresia mencapai
sembilan, memimpin papan peringkat di atas Gilang Prasetyo Nugroho yang mengoleksi
delapan.

Papan peringkat lengkap tersedia di halaman Hall of Fame dan diperbarui setiap
Senin pagi.$ksp$, array[$ksp$challenge$ksp$, $ksp$hall-of-fame$ksp$, $ksp$anggota$ksp$]::text[]),
  ($ksp$n-03$ksp$, $ksp$challenge-mingguan-musim-kedua$ksp$, $ksp$Challenge Mingguan Musim Kedua Dimulai Hari Ini$ksp$, $ksp$2026-07-06$ksp$, $ksp$pengumuman$ksp$, $ksp$https://picsum.photos/seed/ksp-berita-challenge/1200/675$ksp$, $ksp$Dua belas soal, satu setiap Senin. Tiga perubahan dari musim pertama: tingkat SEGFAULT, petunjuk yang terkunci bertingkat, dan solusi pemenang yang dipublikasikan lengkap dengan tulisan pendekatannya.$ksp$, $ksp$Nadia Puspita Ramadhani$ksp$, $ksp$Challenge mingguan musim kedua dimulai hari ini. Dua belas soal, satu soal setiap
Senin, dengan batas pengumpulan Minggu pukul 23.59. Seluruh soal terbuka untuk
anggota maupun non-anggota.

## Yang berubah dari musim pertama

Tiga hal.

**Tingkat kesulitan sekarang punya empat tingkat, bukan tiga.** Tingkat keempat
diberi nama SEGFAULT, dan dipakai untuk soal yang menuntut pengelolaan memori
manual atau struktur data yang dibangun sendiri. Musim ini ada dua soal
bertingkat SEGFAULT, keduanya di paruh kedua.

**Petunjuk sekarang bertingkat dan bisa dibuka satu per satu.** Musim lalu semua
petunjuk muncul sekaligus, dan sebagian besar orang membacanya sebelum sempat
mencoba. Sekarang petunjuknya terkunci dan kamu memilih sendiri kapan membukanya.
Membukanya tidak mengurangi nilai apa pun. Kuncinya ada supaya kamu berhenti
sebentar dan bertanya apakah benar-benar butuh.

**Solusi pemenang dipublikasikan lengkap dengan tulisan pendekatannya.** Kode saja
tidak banyak mengajarkan. Yang mengajarkan adalah cerita tentang percobaan yang
gagal lebih dulu, dan itu yang kami minta dari setiap pemenang.

## Jadwal

Soal terbit setiap Senin pukul 08.00. Pembahasan terbit setiap Selasa berikutnya,
bersamaan dengan pengumuman pemenang.

Peserta yang mengumpulkan setelah batas waktu tetap mendapat koreksi, hanya tidak
masuk penilaian. Kami lebih suka kamu menyelesaikannya terlambat daripada tidak
sama sekali.

## Cara ikut

Tidak ada pendaftaran terpisah. Buka halaman challenge, pilih soal minggu ini,
kerjakan, lalu kirim berkas `.c` ke surel pengurus sebelum batas waktu.

Satu berkas, satu `main`, tanpa pustaka di luar pustaka standar C.$ksp$, array[$ksp$challenge$ksp$, $ksp$pengumuman$ksp$]::text[]),
  ($ksp$n-04$ksp$, $ksp$peringkat-empat-lomba-se-diy$ksp$, $ksp$Peringkat Empat dari 31 Tim di Lomba Pemrograman Se-DIY$ksp$, $ksp$2026-05-12$ksp$, $ksp$prestasi$ksp$, $ksp$https://picsum.photos/seed/ksp-berita-lomba/1200/675$ksp$, $ksp$Delapan dari sebelas soal terselesaikan, terpaut satu soal dari podium. Empat puluh menit hilang di satu soal bitwise, dan tim membawa pulang dua catatan yang langsung masuk materi kelas.$ksp$, $ksp$Damar Aji Setiawan$ksp$, $ksp$Tim Kelompok Studi Pemrograman UAJY meraih peringkat empat pada Lomba Pemrograman
Antar Kampus se-DIY yang digelar Sabtu lalu, bersaing dengan tiga puluh satu tim
dari sebelas perguruan tinggi.

Tim beranggotakan Gilang Prasetyo Nugroho, Damar Aji Setiawan, dan Theresia
Maharani Putri, dengan Reza Maulana Hakim sebagai pendamping.

## Jalannya lomba

Format lomba lima jam dengan sebelas soal. Tim KSP menyelesaikan delapan soal,
terpaut satu soal dari tiga tim di atasnya yang masing-masing menyelesaikan
sembilan.

Empat soal pertama selesai dalam lima puluh menit. Soal kelima, tentang pemampatan
data dengan operasi bit, memakan waktu hampir satu jam penuh, dan menurut catatan
tim itulah yang menentukan selisih akhirnya.

"Kami sebenarnya tahu cara menyelesaikannya sejak menit kelima," kata Gilang.
"Yang lama justru meyakinkan diri bahwa pergeseran bitnya tidak meluap. Kami
kehilangan empat puluh menit untuk sesuatu yang seharusnya bisa dipastikan dalam
sepuluh."

## Yang dibawa pulang

Pendamping tim mencatat dua hal yang akan langsung masuk ke materi kelas.

Yang pertama, kebiasaan menulis kasus uji sendiri sebelum mengumpulkan. Tiga dari
sebelas soal punya kasus tepi yang tidak muncul di contoh, dan dua di antaranya
sempat membuat tim tertahan.

Yang kedua, pembagian peran. Selama tiga jam pertama ketiganya mengerjakan soal
berbeda tanpa berkoordinasi, dan dua di antaranya sempat mengerjakan soal yang
sama tanpa sadar.

Materi tentang strategi tim akan masuk ke kelas persiapan kompetisi semester
depan.

## Peringkat akhir lima besar

1. Universitas Gadjah Mada, 9 soal
2. Universitas Islam Indonesia, 9 soal
3. Universitas Sanata Dharma, 9 soal
4. **Universitas Atma Jaya Yogyakarta, 8 soal**
5. Universitas Ahmad Dahlan, 8 soal$ksp$, array[$ksp$kompetisi$ksp$, $ksp$prestasi$ksp$, $ksp$tim$ksp$]::text[]),
  ($ksp$n-05$ksp$, $ksp$tiga-kesalahan-malloc$ksp$, $ksp$Tiga Kesalahan malloc yang Paling Sering Muncul$ksp$, $ksp$2026-04-18$ksp$, $ksp$tutorial$ksp$, $ksp$https://picsum.photos/seed/ksp-berita-malloc/1200/675$ksp$, $ksp$Dikumpulkan dari lebih dari tiga ratus submission dalam dua semester. Ketiganya punya satu kesamaan: programnya tetap jalan, sampai suatu hari tidak.$ksp$, $ksp$Reza Maulana Hakim$ksp$, $ksp$Setelah mengoreksi lebih dari tiga ratus submission dalam dua semester terakhir,
pola kesalahannya mulai terlihat berulang. Tiga di antaranya menyangkut `malloc`
dan kerabatnya, dan ketiganya punya satu kesamaan: programnya tetap jalan, sampai
suatu hari tidak.

## 1. Menimpa pointer dengan hasil realloc

Ini yang paling sering, dan paling halus.

```c
data = realloc(data, kapasitas_baru * sizeof *data);
```

Baris ini benar selama `realloc` berhasil. Ketika gagal, `realloc` mengembalikan
`NULL` dan **tidak** membebaskan blok lama. Karena hasilnya langsung ditimpakan ke
`data`, satu-satunya pointer ke blok lama baru saja hilang. Memorinya bocor dan
tidak ada cara mengambilnya kembali.

Bentuk yang benar menampung hasilnya lebih dulu:

```c
int *lebih = realloc(data, kapasitas_baru * sizeof *data);
if (lebih == NULL) {
    free(data);
    return EXIT_FAILURE;
}
data = lebih;
```

Di komputer dengan memori besar, versi yang salah hampir tidak pernah gagal saat
diuji. Itu sebabnya ia lolos terus.

## 2. Membaca simpul setelah dibebaskan

Muncul hampir di setiap submission linked list.

```c
free(depan);
depan = depan->next;
```

Setelah `free`, isi memori itu bukan lagi milikmu. Membacanya adalah perilaku tak
terdefinisi. Bukan berarti pasti crash, tapi berarti tidak ada jaminan apa pun.
Dalam praktiknya nilai lamanya sering masih ada di sana beberapa saat, jadi
programnya kelihatan jalan.

Simpan penerusnya lebih dulu:

```c
Simpul *berikut = depan->next;
free(depan);
depan = berikut;
```

## 3. Mengira free menghapus pointernya

`free` melepaskan memorinya. Ia tidak mengubah nilai pointer yang kamu pegang.

```c
free(p);
if (p != NULL) {
    p->nilai = 10;
}
```

Pemeriksaan di atas masih bernilai benar, dan itulah masalahnya. Setelah `free`,
`p` masih menyimpan alamat lama, yang sekarang disebut dangling pointer. Kalau
pointernya masih akan hidup beberapa baris lagi, setel sendiri ke `NULL` supaya
pemeriksaan berikutnya berarti sesuatu.

## Cara memastikan

Tiga kesalahan ini punya satu hal yang sama: pengujian biasa tidak menangkapnya.

Yang menangkapnya adalah alat. Di Linux dan WSL, `valgrind ./program` akan
menyebutkan persis baris mana yang bocor dan baris mana yang membaca memori bebas.
Pada gcc dan clang, `-fsanitize=address` melakukan hal serupa tanpa perlu alat
terpisah.

Biasakan menjalankan salah satunya sebelum mengumpulkan. Butuh satu perintah, dan
menghemat satu sore.$ksp$, array[$ksp$memori$ksp$, $ksp$tutorial$ksp$, $ksp$malloc$ksp$]::text[]),
  ($ksp$n-06$ksp$, $ksp$bahaya-scanf-persen-s$ksp$, $ksp$Berhenti Menulis scanf Persen-s Tanpa Batas Lebar$ksp$, $ksp$2026-02-27$ksp$, $ksp$tutorial$ksp$, $ksp$https://picsum.photos/seed/ksp-berita-scanf/1200/675$ksp$, $ksp$Satu baris yang muncul di hampir setiap submission minggu-minggu awal, dan hampir selalu salah. Perbaikannya cuma satu angka, dan angkanya bukan yang kamu kira.$ksp$, $ksp$Melati Kusumaningrum$ksp$, $ksp$Ada satu baris yang muncul di hampir setiap submission minggu-minggu awal, dan
hampir selalu salah:

```c
char nama[32];
scanf("%s", nama);
```

Baris ini membaca satu kata dari masukan ke dalam `nama`. Masalahnya, `scanf`
tidak tahu bahwa `nama` hanya punya ruang 32 byte. Kalau masukannya lebih panjang,
`scanf` tetap menulis, melewati ujung array, ke memori yang bukan miliknya.

## Kenapa ini tidak ketahuan saat diuji

Karena saat diuji, kamu mengetik nama yang pendek.

Buffer overflow tidak selalu membuat program berhenti. Yang tertimpa mungkin
variabel lain di stack, dan programnya tetap jalan dengan nilai yang diam-diam
berubah. Atau yang tertimpa adalah bagian yang belum dipakai, dan tidak terjadi
apa-apa sama sekali.

Kelas kesalahan inilah yang selama puluhan tahun jadi sumber kerentanan keamanan
paling umum di perangkat lunak yang ditulis dengan C.

## Perbaikannya satu angka

`scanf` menerima batas lebar tepat setelah tanda persen:

```c
char nama[32];
scanf("%31s", nama);
```

Angkanya 31, bukan 32. `scanf` menambahkan karakter nol di akhir, dan karakter itu
juga butuh tempat. Aturannya: **selalu satu kurang dari ukuran array.**

Ini yang paling sering meleset satu. Kalau kamu menulis `%32s` pada array
berukuran 32, kamu baru saja menggeser masalahnya satu byte, bukan
menghilangkannya.

## Untuk membaca satu baris penuh

`%s` berhenti di spasi pertama, jadi ia tidak bisa membaca kalimat. Untuk itu
pakai `fgets`, yang menerima ukuran buffer sebagai argumen:

```c
char baris[256];
if (fgets(baris, sizeof baris, stdin) == NULL) {
    return 1;
}
```

Perhatikan bahwa `fgets` ikut menyimpan karakter baris baru kalau muat. Untuk
sebagian besar soal, hal itu perlu dibuang sendiri.

## Kebiasaan yang layak dibawa

Setiap kali kamu menulis `%s` di dalam `scanf`, berhenti sebentar dan tanyakan
berapa ukuran tujuannya. Kalau kamu tidak bisa menjawabnya langsung, itu tanda
bahwa batasnya memang belum kamu pikirkan.

Mulai musim ini, submission yang memakai `%s` tanpa batas lebar akan dikembalikan
untuk diperbaiki, meski keluarannya sudah benar.$ksp$, array[$ksp$string$ksp$, $ksp$tutorial$ksp$, $ksp$keamanan$ksp$]::text[]),
  ($ksp$n-07$ksp$, $ksp$kompetisi-internal-akhir-semester$ksp$, $ksp$Kompetisi Internal: 34 Peserta, Satu Soal Tak Tersentuh$ksp$, $ksp$2025-12-01$ksp$, $ksp$liputan$ksp$, $ksp$https://picsum.photos/seed/ksp-berita-kompetisi/1200/675$ksp$, $ksp$Tiga jam, delapan soal. Tujuh dari delapan submission untuk soal nomor tujuh sebenarnya sudah benar secara logika, dan yang hilang cuma satu hal.$ksp$, $ksp$Kevin Alexander Tanuwijaya$ksp$, $ksp$Kompetisi internal akhir semester ganjil digelar Jumat lalu di laboratorium FTI,
diikuti 34 peserta dari seluruh angkatan. Formatnya tiga jam, delapan soal,
penilaian berbasis jumlah soal terselesaikan dan waktu pengumpulan.

## Hasil akhir

Peringkat pertama diraih Theresia Maharani Putri dari angkatan 2025, dengan enam
soal terselesaikan dalam dua jam empat puluh menit. Ini pertama kalinya peserta
angkatan pertama memenangi kompetisi internal.

Peringkat kedua dan ketiga masing-masing diraih Gilang Prasetyo Nugroho dan
Damar Aji Setiawan, keduanya dengan enam soal, terpaut sembilan dan enam belas
menit dari peringkat pertama.

## Soal nomor tujuh

Dari delapan soal, hanya satu yang tidak terselesaikan oleh siapa pun: soal
nomor tujuh, tentang penelusuran graf berarah dengan siklus.

Delapan peserta mengumpulkan jawaban dan seluruhnya kehabisan waktu. Setelah
kompetisi, pembahasan menunjukkan bahwa tujuh dari delapan submission itu
sebenarnya sudah benar secara logika. Yang hilang adalah penanda simpul yang
sudah dikunjungi, sehingga penelusurannya berputar selamanya di dalam siklus.

Soal itu kemudian dipakai ulang sebagai challenge minggu kedua belas musim ini,
dengan batas waktu yang lebih longgar.

## Catatan panitia

Dua hal yang dicatat panitia untuk kompetisi berikutnya.

Pertama, waktu tiga jam terlalu pendek untuk delapan soal. Enam soal dalam tiga
jam akan memberi ruang lebih untuk membaca soal dengan benar, yang ternyata jadi
sumber kesalahan terbanyak.

Kedua, sistem penilaian akan membekukan papan peringkat tiga puluh menit
terakhir. Papan yang terus berubah sampai detik akhir memang seru untuk ditonton,
tapi membuat sebagian peserta panik dan meninggalkan soal yang hampir selesai.$ksp$, array[$ksp$kompetisi$ksp$, $ksp$liputan$ksp$, $ksp$graf$ksp$]::text[]),
  ($ksp$n-08$ksp$, $ksp$workshop-manajemen-memori$ksp$, $ksp$Catatan dari Workshop Manajemen Memori$ksp$, $ksp$2025-10-27$ksp$, $ksp$liputan$ksp$, $ksp$https://picsum.photos/seed/ksp-berita-workshop/1200/675$ksp$, $ksp$Dibuka bukan dengan malloc, melainkan dengan menggambar. Dari 28 gambar, hanya 6 yang menempatkan pointer sebagai variabel yang punya alamatnya sendiri.$ksp$, $ksp$Salsabila Rahmawati$ksp$, $ksp$Workshop manajemen memori digelar Sabtu lalu selama tiga jam, diikuti 28 peserta.
Materinya dibawakan Reza Maulana Hakim dan Bimo Santoso Aji, dengan format setengah
penjelasan dan setengah praktik langsung.

## Struktur sesi

Sesi dibuka bukan dengan `malloc`, melainkan dengan menggambar. Setiap peserta
diminta menggambar apa yang menurut mereka terjadi di memori ketika sebuah
variabel dideklarasikan, lalu ketika sebuah pointer menunjuk ke variabel itu.

Dari 28 gambar, 19 di antaranya menggambarkan pointer sebagai panah yang menunjuk
ke sebuah nilai. Hanya 6 yang menggambarkan pointer sebagai variabel tersendiri
yang menyimpan alamat, dan punya alamatnya sendiri.

"Perbedaan itu kelihatan sepele sampai kamu perlu pointer ke pointer," kata Reza.
"Kalau modelmu berupa panah, `int **p` jadi tidak masuk akal. Kalau modelmu berupa
kotak beralamat, ia cuma kotak yang isinya alamat kotak lain."

## Bagian praktik

Peserta diberi satu program yang sudah jalan dan benar keluarannya, lalu diminta
menemukan tiga kebocoran memori di dalamnya menggunakan `valgrind`.

Rata-rata peserta menemukan dua dari tiga. Kebocoran ketiga sengaja ditaruh di
jalur penanganan galat, yang hanya berjalan kalau alokasinya gagal. Tidak ada satu
pun yang menemukannya lewat pengujian biasa, karena jalur itu tidak pernah dijalani.

Pesan penutupnya diambil dari situ: jalur galat adalah bagian program yang paling
jarang diuji dan paling sering salah.

## Berkas dan rekaman

Rekaman sesi, berkas latihan, dan kunci jawaban tersedia di arsip materi. Program
berisi kebocoran memori yang dipakai dalam sesi praktik dibiarkan apa adanya,
lengkap dengan ketiga kebocorannya, supaya bisa dipakai ulang untuk latihan mandiri.$ksp$, array[$ksp$workshop$ksp$, $ksp$memori$ksp$, $ksp$liputan$ksp$]::text[]);

insert into public.challenges (id, slug, minggu, judul, tanggal_rilis, deadline, difficulty, topik, deskripsi_mdx, constraints, sample_io, hint_terkunci, total_peserta, tags) values
  ($ksp$c-01$ksp$, $ksp$suhu-rata-rata-laboratorium$ksp$, 1, $ksp$Suhu Rata-Rata Laboratorium$ksp$, $ksp$2026-07-06$ksp$, $ksp$2026-07-12T23:59$ksp$, $ksp$MUDAH$ksp$, array[$ksp$array$ksp$, $ksp$algoritma$ksp$]::text[], $ksp$Laboratorium FTI memasang termometer digital di empat sudut ruang server. Setiap
jam, angkanya dicatat ke dalam satu berkas. Bagian kelistrikan ingin ringkasan
harian yang bisa dibaca sekilas, bukan deretan angka mentah.

Tugasmu menulis program yang membaca sederet suhu lalu mencetak rata-rata,
suhu tertinggi, dan suhu terendah.

## Format masukan

Baris pertama berisi satu bilangan bulat `N`, banyaknya pencatatan.
Baris kedua berisi `N` bilangan bulat yang dipisahkan spasi.

## Format keluaran

Tiga baris, dengan format persis seperti ini:

```
rata-rata: X.XX
tertinggi: Y
terendah: Z
```

Rata-rata dicetak dengan dua angka di belakang koma. Perhatikan bahwa pembagian
antar bilangan bulat di C membuang sisanya — `7 / 2` bernilai `3`, bukan `3.5`.
Kamu harus mengubah tipenya lebih dulu.$ksp$, array[$ksp$1 <= N <= 1000$ksp$, $ksp$-50 <= suhu <= 100$ksp$, $ksp$Rata-rata dicetak dengan tepat dua angka di belakang koma$ksp$, $ksp$Batas waktu 1 detik, batas memori 64 MB$ksp$]::text[], $ksp$[{"input":"5\n21 24 23 27 20","output":"rata-rata: 23.00\ntertinggi: 27\nterendah: 20","penjelasan":"Jumlah seluruh suhu 115, dibagi 5 menghasilkan tepat 23."},{"input":"1\n30","output":"rata-rata: 30.00\ntertinggi: 30\nterendah: 30","penjelasan":"Dengan satu data, ketiganya bernilai sama."},{"input":"4\n-3 -1 0 4","output":"rata-rata: 0.00\ntertinggi: 4\nterendah: -3","penjelasan":"Suhu negatif tetap dihitung. Totalnya nol, jadi rata-ratanya nol."}]$ksp$::jsonb, array[$ksp$Nilai awal untuk tertinggi dan terendah sebaiknya diambil dari elemen pertama, bukan dari 0.$ksp$, $ksp$total / n memakai pembagian bulat. Ubah salah satu operandnya ke double sebelum membagi.$ksp$, $ksp$printf("%.2f", x) mencetak dua angka di belakang koma dan sudah membulatkan sendiri.$ksp$]::text[], 38, array[$ksp$pemanasan$ksp$, $ksp$aritmetika$ksp$]::text[]),
  ($ksp$c-02$ksp$, $ksp$jalan-pintas-pointer$ksp$, 2, $ksp$Jalan Pintas Pointer$ksp$, $ksp$2026-07-13$ksp$, $ksp$2026-07-19T23:59$ksp$, $ksp$MUDAH$ksp$, array[$ksp$pointer$ksp$, $ksp$array$ksp$]::text[], $ksp$Ada satu aturan tambahan di soal ini: **jangan gunakan tanda kurung siku sama
sekali**. Tidak ada `data[i]`. Semua akses ke elemen array harus lewat aritmetika
pointer.

Aturannya terdengar menyebalkan, dan memang sengaja. `data[i]` di C hanyalah cara
penulisan lain untuk `*(data + i)` — keduanya benar-benar sama bagi kompilator.
Menulis bentuk panjangnya sekali dua kali membuat hubungan itu berhenti terasa
seperti hafalan.

Tugasmu mencetak elemen array pada posisi `0`, `k`, `2k`, `3k`, dan seterusnya,
selama posisinya masih di dalam array.

## Format masukan

Baris pertama berisi dua bilangan bulat `N` dan `k`.
Baris kedua berisi `N` bilangan bulat.

## Format keluaran

Satu baris berisi elemen-elemen terpilih, dipisahkan satu spasi, diakhiri
baris baru. Tidak ada spasi di akhir baris.

## Catatan

Menambahkan bilangan bulat ke sebuah pointer tidak menggeser alamatnya sebanyak
itu dalam byte — pergeserannya sebanyak itu dikali ukuran tipe yang ditunjuk.
Pada `int *p`, `p + 1` melompat empat byte di kebanyakan mesin, bukan satu.$ksp$, array[$ksp$1 <= N <= 100000$ksp$, $ksp$1 <= k <= N$ksp$, $ksp$Dilarang memakai tanda kurung siku sama sekali di seluruh berkas$ksp$, $ksp$Batas waktu 1 detik, batas memori 64 MB$ksp$]::text[], $ksp$[{"input":"8 3\n5 1 9 4 7 2 8 6","output":"5 4 8","penjelasan":"Posisi yang diambil adalah 0, 3, dan 6. Posisi 9 sudah di luar array."},{"input":"5 1\n10 20 30 40 50","output":"10 20 30 40 50","penjelasan":"Dengan k bernilai 1, semua elemen terpilih."},{"input":"4 5\n1 2 3 4","output":"1","penjelasan":"Lompatan pertama sudah melewati ujung array, jadi hanya elemen nol yang tercetak."}]$ksp$::jsonb, array[$ksp$data[i] hanyalah cara penulisan lain untuk *(data + i). Pakai bentuk panjangnya.$ksp$, $ksp$Menambahkan k ke sebuah int* menggeser alamatnya sebanyak k * sizeof(int) byte, bukan k byte.$ksp$, $ksp$Simpan pointer ke satu elemen sesudah elemen terakhir sebagai penanda berhenti, lalu bandingkan dengan p < akhir.$ksp$]::text[], 41, array[$ksp$pointer$ksp$, $ksp$aritmetika-alamat$ksp$]::text[]),
  ($ksp$c-03$ksp$, $ksp$palindrom-nama-laboratorium$ksp$, 3, $ksp$Palindrom Nama Laboratorium$ksp$, $ksp$2026-07-20$ksp$, $ksp$2026-07-26T23:59$ksp$, $ksp$MUDAH$ksp$, array[$ksp$string$ksp$, $ksp$array$ksp$]::text[], $ksp$Panitia kompetisi internal ingin membuat sandi ruangan dari kalimat yang terbaca
sama dari depan dan belakang. Spasi dan besar-kecil huruf diabaikan, tanda baca
dibuang.

Tugasmu memeriksa apakah sebuah kalimat adalah palindrom setelah semua karakter
selain huruf dan angka dibuang, dan semua huruf diseragamkan jadi huruf kecil.

## Format masukan

Satu baris berisi kalimat, panjangnya paling banyak 200 karakter. Kalimat bisa
memuat spasi, tanda baca, huruf besar, dan angka.

## Format keluaran

Satu baris: `palindrom` atau `bukan palindrom`.

## Catatan

String di C adalah array karakter yang diakhiri satu byte bernilai nol. Fungsi
seperti `strlen` bekerja dengan mencari byte nol itu, jadi kalau kamu menimpanya
tanpa sengaja, semua fungsi string sesudahnya akan membaca melewati ujung array.

`fgets` menyimpan karakter baris baru ke dalam buffer kalau muat. Kalimat
`kasur ini rusak\n` bukan palindrom — tapi `kasur ini rusak` adalah.$ksp$, array[$ksp$Panjang kalimat <= 200 karakter$ksp$, $ksp$Kalimat bisa memuat huruf besar, huruf kecil, angka, spasi, dan tanda baca$ksp$, $ksp$Hanya huruf dan angka yang diperhitungkan$ksp$, $ksp$Batas waktu 1 detik, batas memori 64 MB$ksp$]::text[], $ksp$[{"input":"Kasur Ini Rusak","output":"palindrom","penjelasan":"Setelah spasi dibuang dan huruf diseragamkan, terbaca kasurinirusak dari dua arah."},{"input":"Kelompok Studi","output":"bukan palindrom","penjelasan":"kelompokstudi dibaca dari belakang menjadi idutskopmolek."},{"input":"Ibu Ratna antar ubi","output":"palindrom","penjelasan":"iburatnaantarubi punya 16 karakter dan simetris di titik tengahnya."}]$ksp$::jsonb, array[$ksp$isalnum dan tolower dari ctype.h mengharapkan argumen bertipe unsigned char. Ubah dulu tipenya.$ksp$, $ksp$fgets ikut menyimpan karakter baris baru. Saringan huruf dan angka otomatis membuangnya.$ksp$, $ksp$Menyalin karakter yang lolos ke buffer baru jauh lebih mudah dibaca daripada melompati tanda baca di dua arah sekaligus.$ksp$]::text[], 36, array[$ksp$string$ksp$, $ksp$karakter$ksp$]::text[]),
  ($ksp$c-04$ksp$, $ksp$faktorial-panjang$ksp$, 4, $ksp$Faktorial Panjang$ksp$, $ksp$2026-07-27$ksp$, $ksp$2026-08-02T23:59$ksp$, $ksp$SEDANG$ksp$, array[$ksp$array$ksp$, $ksp$algoritma$ksp$]::text[], $ksp$`20!` masih muat di dalam `unsigned long long`. `21!` sudah tidak. Padahal soal
kombinatorika di kelas Analisis dan Desain Algoritma rutin memakai angka jauh di
atas itu.

Tugasmu menghitung `N!` untuk `N` sampai 100 dan mencetak seluruh digitnya.

## Format masukan

Satu bilangan bulat `N`.

## Format keluaran

Satu baris berisi `N!` tanpa pemisah ribuan dan tanpa nol di depan.

## Catatan

Cara yang lazim: simpan hasilnya sebagai array digit, satu digit per elemen,
dengan digit paling tidak signifikan di indeks nol. Untuk mengalikan seluruh
array dengan sebuah bilangan, kalikan setiap digit lalu rambatkan sisa
penyimpanan ke elemen berikutnya — persis seperti perkalian bersusun di kertas.

`100!` punya 158 digit. Pastikan arraymu cukup besar sebelum menulis ke dalamnya.$ksp$, array[$ksp$0 <= N <= 100$ksp$, $ksp$Keluaran tanpa pemisah ribuan dan tanpa nol di depan$ksp$, $ksp$0! bernilai 1$ksp$, $ksp$Batas waktu 1 detik, batas memori 64 MB$ksp$]::text[], $ksp$[{"input":"20","output":"2432902008176640000","penjelasan":"Nilai terbesar yang masih muat di unsigned long long. Satu langkah lagi dan cara biasa gagal."},{"input":"0","output":"1","penjelasan":"Faktorial nol didefinisikan bernilai satu."},{"input":"25","output":"15511210043330985984000000","penjelasan":"Dua puluh enam digit, jauh melampaui tipe bilangan bulat mana pun di C."}]$ksp$::jsonb, array[$ksp$Simpan hasilnya sebagai array digit dengan digit satuan di indeks nol.$ksp$, $ksp$Mengalikan array dengan sebuah bilangan sama persis dengan perkalian bersusun: kalikan digitnya, lalu rambatkan sisa penyimpanan.$ksp$, $ksp$Sisa penyimpanan bisa lebih dari satu digit. Habiskan dengan while, bukan dengan satu if.$ksp$]::text[], 29, array[$ksp$bignum$ksp$, $ksp$aritmetika$ksp$]::text[]),
  ($ksp$c-05$ksp$, $ksp$papan-peringkat-kelas$ksp$, 5, $ksp$Papan Peringkat Kelas$ksp$, $ksp$2026-08-03$ksp$, $ksp$2026-08-09T23:59$ksp$, $ksp$SEDANG$ksp$, array[$ksp$struct$ksp$, $ksp$algoritma$ksp$]::text[], $ksp$Rekap nilai kelas selama ini disimpan sebagai dua array terpisah: satu untuk
nama, satu untuk nilai. Sistemnya bertahan sampai seseorang perlu mengurutkan
data itu, dan menyadari kedua array harus digeser bersamaan supaya indeksnya
tetap sejajar. Satu kali lupa, dan nilai orang lain menempel di namamu.

Tugasmu menyusun papan peringkat memakai `struct`, lalu mengurutkannya.

## Format masukan

Baris pertama berisi bilangan bulat `N`.
`N` baris berikutnya masing-masing berisi sebuah nama tanpa spasi dan sebuah
nilai, dipisahkan satu spasi.

## Format keluaran

`N` baris, terurut berdasarkan nilai dari besar ke kecil. Kalau nilainya sama,
urutkan berdasarkan nama secara alfabetis menaik. Setiap baris berformat:

```
<peringkat>. <nama> <nilai>
```

Peringkat dimulai dari 1 dan selalu bertambah satu, termasuk saat nilainya sama.

## Catatan

`qsort` dari `stdlib.h` menerima fungsi pembanding yang mengembalikan bilangan
negatif, nol, atau positif. Fungsi itu menerima dua `const void *`, jadi kamu
harus mengubahnya sendiri ke tipe yang benar sebelum membaca isinya.

Hati-hati dengan pembanding yang mengembalikan selisih dua bilangan bulat besar:
selisihnya bisa meluap. Untuk nilai 0 sampai 100 di soal ini hal itu aman.$ksp$, array[$ksp$1 <= N <= 5000$ksp$, $ksp$Nama tanpa spasi, panjang <= 32 karakter$ksp$, $ksp$0 <= nilai <= 100$ksp$, $ksp$Urutan: nilai menurun, lalu nama menaik bila seri$ksp$]::text[], $ksp$[{"input":"4\nNadia 92\nGilang 95\nRangga 92\nIvana 88","output":"1. Gilang 95\n2. Nadia 92\n3. Rangga 92\n4. Ivana 88","penjelasan":"Nadia dan Rangga sama-sama 92, jadi urutannya ditentukan secara alfabetis."},{"input":"2\nBimo 70\nAlya 70","output":"1. Alya 70\n2. Bimo 70","penjelasan":"Nilainya identik, sehingga seluruh urutan ditentukan oleh nama."},{"input":"1\nDamar 100","output":"1. Damar 100","penjelasan":"Satu peserta tetap harus dicetak dengan format peringkat yang sama."}]$ksp$::jsonb, array[$ksp$Satu struct berisi nama dan nilai jauh lebih aman daripada dua array yang harus dijaga sejajar.$ksp$, $ksp$Fungsi pembanding qsort menerima dua const void*. Ubah dulu ke tipe struct-mu sebelum membaca isinya.$ksp$, $ksp$Untuk kunci kedua, strcmp sudah mengembalikan nilai dengan tanda yang tepat. Kembalikan hasilnya apa adanya.$ksp$]::text[], 33, array[$ksp$struct$ksp$, $ksp$qsort$ksp$]::text[]),
  ($ksp$c-06$ksp$, $ksp$riwayat-peminjaman-buku$ksp$, 6, $ksp$Riwayat Peminjaman Buku$ksp$, $ksp$2026-08-10$ksp$, $ksp$2026-08-16T23:59$ksp$, $ksp$SEDANG$ksp$, array[$ksp$linked-list$ksp$, $ksp$memori-dinamis$ksp$]::text[], $ksp$Perpustakaan kecil di sekretariat KSP mencatat peminjaman di selembar kertas.
Buku yang baru dipinjam ditulis paling atas, dan yang dikembalikan diambil dari
atas juga. Kertas itu, tanpa disadari siapa pun, adalah sebuah stack yang
diimplementasikan sebagai linked list.

Tugasmu membangun linked list dinamis dan menjalankan urutan perintah.

## Format masukan

Baris pertama berisi bilangan bulat `N`, banyaknya perintah.
`N` baris berikutnya masing-masing berisi satu perintah:

- `T <judul>` — tambahkan judul ke bagian depan daftar. Tidak mencetak apa pun.
- `A` — ambil judul paling depan, hapus dari daftar, lalu cetak judulnya.
- `L` — cetak seluruh daftar dari depan ke belakang, dipisahkan ` -> `.

Untuk `A` dan `L`, kalau daftarnya kosong, cetak `kosong`.

## Format keluaran

Satu baris untuk setiap perintah `A` dan `L`, sesuai urutan perintahnya.

## Catatan

Setiap simpul dialokasikan dengan `malloc` dan harus dibebaskan dengan `free`.
Saat menghapus simpul depan, simpan dulu pointer ke simpul berikutnya sebelum
membebaskan yang sekarang — begitu memori dibebaskan, membaca `simpul->next`
adalah perilaku tak terdefinisi, meski sering kali kelihatan berhasil.

Jangan lupa membebaskan sisa daftar sebelum program berakhir.$ksp$, array[$ksp$1 <= N <= 10000$ksp$, $ksp$Judul tanpa spasi, panjang <= 64 karakter$ksp$, $ksp$Setiap simpul wajib dialokasikan dengan malloc dan dibebaskan dengan free$ksp$, $ksp$Program tidak boleh menyisakan memori yang belum dibebaskan$ksp$]::text[], $ksp$[{"input":"6\nT algoritma\nT struktur-data\nT sistem-operasi\nA\nL\nA","output":"sistem-operasi\nstruktur-data -> algoritma\nstruktur-data","penjelasan":"Judul terakhir yang ditambahkan berada paling depan, jadi itulah yang pertama diambil."},{"input":"3\nA\nT basis-data\nL","output":"kosong\nbasis-data","penjelasan":"Mengambil dari daftar kosong harus dijawab, bukan membuat program berhenti."},{"input":"4\nT c-lanjut\nT jaringan\nL\nA","output":"jaringan -> c-lanjut\njaringan","penjelasan":"Pemisah antar judul adalah spasi, tanda minus, tanda lebih besar, lalu spasi."}]$ksp$::jsonb, array[$ksp$Menambah ke depan hanya butuh dua langkah: sambungkan simpul baru ke kepala lama, lalu pindahkan kepalanya.$ksp$, $ksp$Sebelum free(depan), simpan depan->next ke variabel lain. Setelah dibebaskan, membacanya sudah tidak sah.$ksp$, $ksp$Sisa daftar harus dibebaskan sebelum program berakhir, bukan hanya simpul yang sempat diambil.$ksp$]::text[], 27, array[$ksp$linked-list$ksp$, $ksp$malloc$ksp$]::text[]),
  ($ksp$c-07$ksp$, $ksp$matriks-spiral$ksp$, 7, $ksp$Matriks Spiral$ksp$, $ksp$2026-08-17$ksp$, $ksp$2026-08-23T23:59$ksp$, $ksp$SEDANG$ksp$, array[$ksp$array$ksp$, $ksp$algoritma$ksp$]::text[], $ksp$Modul kamera di proyek akhir salah satu anggota membaca sensor sebagai matriks,
tetapi mengirimkannya lewat kabel serial satu nilai demi satu, memutar dari tepi
ke dalam. Untuk mencocokkan keluarannya, kamu perlu membaca matriks dengan urutan
yang sama.

Tugasmu mencetak isi matriks dengan urutan spiral searah jarum jam, dimulai dari
sudut kiri atas.

## Format masukan

Baris pertama berisi dua bilangan bulat `R` dan `C`.
`R` baris berikutnya masing-masing berisi `C` bilangan bulat.

## Format keluaran

Satu baris berisi seluruh `R * C` nilai dengan urutan spiral, dipisahkan satu
spasi, tanpa spasi di akhir.

## Catatan

Cara yang rapi adalah menjaga empat batas — atas, bawah, kiri, kanan — lalu
mengecilkannya satu per satu setiap kali satu sisi selesai dilalui. Berhenti
begitu batas atas melewati batas bawah, atau batas kiri melewati batas kanan.

Kasus yang paling sering meleset adalah matriks satu baris atau satu kolom.
Ujilah keduanya sebelum mengumpulkan.$ksp$, array[$ksp$1 <= R, C <= 500$ksp$, $ksp$-1000000 <= nilai <= 1000000$ksp$, $ksp$Keluaran dalam satu baris, dipisahkan satu spasi, tanpa spasi di akhir$ksp$, $ksp$Batas waktu 1 detik, batas memori 64 MB$ksp$]::text[], $ksp$[{"input":"3 4\n1 2 3 4\n5 6 7 8\n9 10 11 12","output":"1 2 3 4 8 12 11 10 9 5 6 7","penjelasan":"Tepi luar dilalui searah jarum jam, lalu tersisa baris tengah 6 dan 7."},{"input":"1 5\n3 1 4 1 5","output":"3 1 4 1 5","penjelasan":"Matriks satu baris hanya punya satu sisi. Tanpa penjagaan batas, sebagian elemen akan tercetak dua kali."},{"input":"3 3\n1 2 3\n4 5 6\n7 8 9","output":"1 2 3 6 9 8 7 4 5","penjelasan":"Elemen tengah menjadi yang terakhir karena semua tepinya sudah habis lebih dulu."}]$ksp$::jsonb, array[$ksp$Jaga empat batas: atas, bawah, kiri, kanan. Kecilkan satu per satu setiap kali sebuah sisi selesai.$ksp$, $ksp$Sebelum melintasi sisi bawah, periksa lagi atas <= bawah. Sebelum sisi kiri, periksa lagi kiri <= kanan.$ksp$, $ksp$Matriks satu baris dan satu kolom adalah dua kasus yang paling sering meleset. Uji keduanya.$ksp$]::text[], 31, array[$ksp$matriks$ksp$, $ksp$simulasi$ksp$]::text[]),
  ($ksp$c-08$ksp$, $ksp$rekap-durasi-belajar$ksp$, 8, $ksp$Rekap Durasi Belajar$ksp$, $ksp$2026-08-24$ksp$, $ksp$2026-08-30T23:59$ksp$, $ksp$SULIT$ksp$, array[$ksp$file-io$ksp$, $ksp$string$ksp$, $ksp$struct$ksp$]::text[], $ksp$Aplikasi pencatat jam belajar di sekretariat menulis satu baris log setiap kali
seseorang selesai memakai ruangan. Di akhir minggu, log itu perlu diringkas per
orang. Karena laporannya juga diminta dalam bentuk berkas, ringkasannya ditulis
ke disk lebih dulu, baru dicetak ke layar dari berkas itu.

Alurnya sengaja dibuat begitu: kamu wajib benar-benar menulis dan membaca
kembali sebuah berkas, bukan sekadar menyimpan semuanya di memori.

## Tugas

1. Baca seluruh log dari masukan standar.
2. Jumlahkan durasi per nama.
3. Tulis hasilnya ke berkas bernama `rekap.txt`, satu baris per nama, terurut
   alfabetis menaik, dengan format `<nama> <total>`.
4. Buka kembali `rekap.txt`, baca isinya baris demi baris, dan cetak ke layar
   apa adanya.

## Format masukan

Baris pertama berisi bilangan bulat `N`.
`N` baris berikutnya berformat `<nama>;<durasi>` tanpa spasi, dengan `durasi`
dalam menit.

## Format keluaran

Isi `rekap.txt`, dicetak baris demi baris.

## Catatan

`fopen` mengembalikan `NULL` kalau gagal, dan alasan paling umum bukan berkasnya
tidak ada, melainkan izin tulis yang tidak dimiliki. Periksa nilai kembaliannya
sebelum dipakai — program yang langsung menulis ke `NULL` akan berhenti dengan
segmentation fault tanpa memberi tahu apa yang salah.

Tutup berkas tulis dengan `fclose` sebelum membukanya untuk dibaca. Data yang
masih tertahan di buffer belum tentu sudah sampai ke disk.$ksp$, array[$ksp$1 <= N <= 10000$ksp$, $ksp$Nama tanpa spasi, panjang <= 32 karakter$ksp$, $ksp$1 <= durasi <= 1440$ksp$, $ksp$Program wajib benar-benar menulis dan membaca kembali berkas rekap.txt$ksp$, $ksp$Keluaran terurut alfabetis menaik berdasarkan nama$ksp$]::text[], $ksp$[{"input":"5\nnadia;30\ngilang;45\nnadia;20\nivana;15\ngilang;10","output":"gilang 55\nivana 15\nnadia 50","penjelasan":"Durasi milik nama yang sama dijumlahkan, lalu seluruh hasilnya diurutkan alfabetis."},{"input":"1\ndamar;60","output":"damar 60","penjelasan":"Satu baris log tetap harus melewati berkas sebelum dicetak."},{"input":"3\na;1\nb;2\na;3","output":"a 4\nb 2","penjelasan":"Nama a muncul dua kali dan totalnya 4, tetap berada di depan b."}]$ksp$::jsonb, array[$ksp$strchr menemukan posisi titik koma. Menimpanya dengan karakter nol langsung memotong string itu jadi dua.$ksp$, $ksp$fclose setelah menulis bukan formalitas: data yang masih tertahan di buffer belum tentu sudah sampai ke disk.$ksp$, $ksp$Periksa nilai kembalian fopen. Menulis ke FILE* yang bernilai NULL berakhir dengan segmentation fault.$ksp$]::text[], 22, array[$ksp$berkas$ksp$, $ksp$agregasi$ksp$]::text[]),
  ($ksp$c-09$ksp$, $ksp$buffer-yang-tumbuh-sendiri$ksp$, 9, $ksp$Buffer yang Tumbuh Sendiri$ksp$, $ksp$2026-08-31$ksp$, $ksp$2026-09-06T23:59$ksp$, $ksp$SULIT$ksp$, array[$ksp$memori-dinamis$ksp$, $ksp$pointer$ksp$]::text[], $ksp$Soal-soal sebelumnya selalu memberitahu banyaknya data di baris pertama. Di dunia
nyata hal itu jarang terjadi. Kamu menerima aliran data dan baru tahu panjangnya
setelah datanya habis.

Tugasmu membaca bilangan bulat dari masukan standar sampai habis, menyimpannya
dalam array yang tumbuh sendiri, lalu melaporkan isinya.

## Format masukan

Sederet bilangan bulat yang dipisahkan spasi atau baris baru, sampai akhir
masukan. Banyaknya tidak diberitahukan.

## Format keluaran

Tiga baris:

```
jumlah elemen: N
total: S
terbalik: aN ... a2 a1
```

`terbalik` berisi seluruh elemen dengan urutan dibalik, dipisahkan satu spasi,
tanpa spasi di akhir.

## Catatan

Pola yang biasa dipakai: mulai dengan kapasitas kecil, dan setiap kali penuh,
gandakan kapasitasnya dengan `realloc`. Menggandakan, bukan menambah satu —
menambah satu membuat biaya totalnya kuadratik.

Ada satu jebakan yang memakan banyak orang:

```c
data = realloc(data, kapasitas * sizeof *data);
```

Kalau `realloc` gagal, ia mengembalikan `NULL` **tanpa** membebaskan blok lama.
Menimpa `data` dengan `NULL` berarti kamu baru saja kehilangan satu-satunya
pointer ke memori itu. Tampung dulu hasilnya di variabel sementara.$ksp$, array[$ksp$Banyaknya bilangan tidak diberitahukan dan bisa mencapai 1000000$ksp$, $ksp$-1000000 <= nilai <= 1000000$ksp$, $ksp$Kapasitas awal bebas, tetapi harus tumbuh dengan cara menggandakan$ksp$, $ksp$Seluruh memori yang dialokasikan wajib dibebaskan sebelum program berakhir$ksp$]::text[], $ksp$[{"input":"3 1 4 1 5 9 2 6","output":"jumlah elemen: 8\ntotal: 31\nterbalik: 6 2 9 5 1 4 1 3","penjelasan":"Delapan bilangan masuk tanpa pernah diberitahukan jumlahnya lebih dulu."},{"input":"42","output":"jumlah elemen: 1\ntotal: 42\nterbalik: 42","penjelasan":"Satu elemen belum memicu realokasi sama sekali."},{"input":"-5 5 -5 5","output":"jumlah elemen: 4\ntotal: 0\nterbalik: 5 -5 5 -5","penjelasan":"Totalnya nol, tetapi jumlah elemennya tetap empat."}]$ksp$::jsonb, array[$ksp$scanf mengembalikan banyaknya item yang berhasil dibaca. Perulangan berhenti saat nilainya bukan 1.$ksp$, $ksp$Menggandakan kapasitas membuat biaya total linear. Menambah satu setiap kali membuatnya kuadratik.$ksp$, $ksp$Tampung hasil realloc di variabel sementara. Kalau gagal, blok lama belum dibebaskan dan kamu masih memerlukan pointer-nya.$ksp$]::text[], 24, array[$ksp$realloc$ksp$, $ksp$buffer$ksp$]::text[]),
  ($ksp$c-10$ksp$, $ksp$jejak-menara-hanoi$ksp$, 10, $ksp$Jejak Menara Hanoi$ksp$, $ksp$2026-09-07$ksp$, $ksp$2026-09-13T23:59$ksp$, $ksp$SULIT$ksp$, array[$ksp$rekursi$ksp$, $ksp$algoritma$ksp$]::text[], $ksp$Menara Hanoi selalu muncul di kelas rekursi, biasanya berhenti di "pindahkan
semua cakram". Kali ini kamu harus mencetak jejaknya: setiap langkah, bernomor,
dengan urutan yang persis.

Tugasmu memindahkan `N` cakram dari tiang `A` ke tiang `C` dengan bantuan tiang
`B`, mencetak banyaknya langkah lalu setiap langkahnya.

## Aturan permainan

- Hanya satu cakram boleh dipindahkan dalam satu langkah.
- Cakram hanya boleh diletakkan di tiang kosong, atau di atas cakram yang lebih
  besar.
- Semua cakram mulai bertumpuk di tiang `A`, terbesar di bawah.

## Format masukan

Satu bilangan bulat `N`.

## Format keluaran

Baris pertama: `<banyak langkah> langkah`.
Lalu satu baris untuk setiap langkah, berformat `<nomor>: <asal>-><tujuan>`.

## Catatan

Banyaknya langkah minimum adalah `2^N - 1`. Untuk `N = 20` itu sudah lebih dari
satu juta baris, jadi pastikan pencetakannya tidak melakukan pekerjaan berlebih
per baris.

Tulis kasus dasarnya lebih dulu. Rekursi tanpa kasus dasar bukan rekursi — itu
cara panjang untuk menghabiskan stack.$ksp$, array[$ksp$1 <= N <= 20$ksp$, $ksp$Banyaknya langkah harus tepat 2^N - 1$ksp$, $ksp$Urutan langkah harus persis sama dengan penyelesaian rekursif baku$ksp$, $ksp$Batas waktu 2 detik, batas memori 64 MB$ksp$]::text[], $ksp$[{"input":"3","output":"7 langkah\n1: A->C\n2: A->B\n3: C->B\n4: A->C\n5: B->A\n6: B->C\n7: A->C","penjelasan":"Langkah keempat memindahkan cakram terbesar, tepat di tengah seluruh urutan."},{"input":"1","output":"1 langkah\n1: A->C","penjelasan":"Kasus terkecil: satu cakram langsung pindah ke tujuan."},{"input":"2","output":"3 langkah\n1: A->B\n2: A->C\n3: B->C","penjelasan":"Tiang bantu dipakai sekali, lalu dikosongkan lagi."}]$ksp$::jsonb, array[$ksp$Tulis kasus dasarnya lebih dulu. Tanpa itu, rekursi ini hanya cara panjang untuk menghabiskan stack.$ksp$, $ksp$Pola rekursifnya: pindahkan N-1 cakram ke tiang bantu, pindahkan cakram terbesar, lalu pindahkan N-1 itu ke tujuan.$ksp$, $ksp$Peran ketiga tiang bertukar di setiap pemanggilan. Perhatikan urutan argumennya, bukan namanya.$ksp$]::text[], 26, array[$ksp$rekursi$ksp$, $ksp$klasik$ksp$]::text[]),
  ($ksp$c-11$ksp$, $ksp$status-terkompresi$ksp$, 11, $ksp$Status Terkompresi$ksp$, $ksp$2026-09-14$ksp$, $ksp$2026-09-20T23:59$ksp$, $ksp$SEGFAULT$ksp$, array[$ksp$bitwise$ksp$, $ksp$struct$ksp$]::text[], $ksp$Kartu anggota berbasis RFID di sekretariat hanya punya ruang 32 bit untuk
menyimpan status seorang anggota. Empat keterangan harus muat di sana sekaligus,
dan tidak ada ruang untuk satu `struct` yang longgar.

Tugasmu mengelola satu bilangan bulat 32 bit sebagai wadah empat medan.

## Tata letak bit

| Medan      | Bit     | Lebar  | Rentang nilai |
| ---------- | ------- | ------ | ------------- |
| `hadir`    | 0–7     | 8 bit  | 0–255         |
| `nilai`    | 8–15    | 8 bit  | 0–100         |
| `lunas`    | 16      | 1 bit  | 0–1           |
| `angkatan` | 17–20   | 4 bit  | 0–15          |

Bit 21 sampai 31 selalu nol. Semua medan bermula bernilai nol.

## Format masukan

Baris pertama berisi bilangan bulat `N`, banyaknya perintah.
`N` baris berikutnya masing-masing berisi salah satu dari:

- `SET <medan> <nilai>` — tulis nilai ke medan itu. Tidak mencetak apa pun.
- `GET <medan>` — cetak nilai medan itu sebagai bilangan desimal.
- `RAW` — cetak seluruh 32 bit sebagai heksadesimal huruf besar, tepat delapan
  digit, dengan nol di depan bila perlu.

## Format keluaran

Satu baris untuk setiap perintah `GET` dan `RAW`.

## Catatan

Menulis sebuah medan berarti dua langkah: bersihkan dulu bit lama dengan masker
yang dibalik, baru pasang nilai barunya.

```c
nilai_baru = (nilai_baru & ~(masker << geser)) | ((baru & masker) << geser);
```

Gunakan `unsigned int`, bukan `int`. Pergeseran ke kiri pada bilangan bertanda
yang meluap adalah perilaku tak terdefinisi, dan pergeseran ke kanan pada
bilangan negatif bergantung pada implementasi.$ksp$, array[$ksp$1 <= N <= 100000$ksp$, $ksp$Nilai yang diberikan selalu berada di dalam rentang medannya$ksp$, $ksp$Bit 21 sampai 31 harus selalu bernilai nol$ksp$, $ksp$RAW dicetak sebagai delapan digit heksadesimal huruf besar$ksp$]::text[], $ksp$[{"input":"6\nSET hadir 12\nSET nilai 88\nSET lunas 1\nSET angkatan 5\nGET nilai\nRAW","output":"88\n000B580C","penjelasan":"hadir 12 mengisi 0x0C, nilai 88 mengisi 0x5800, lunas mengisi 0x10000, angkatan 5 mengisi 0xA0000."},{"input":"4\nSET hadir 255\nSET angkatan 15\nGET hadir\nRAW","output":"255\n001E00FF","penjelasan":"Kedua medan terisi penuh tanpa saling menimpa, karena maskernya tidak beririsan."},{"input":"3\nSET nilai 100\nGET lunas\nRAW","output":"0\n00006400","penjelasan":"Medan yang belum pernah ditulis tetap bernilai nol."}]$ksp$::jsonb, array[$ksp$Menulis medan butuh dua langkah: bersihkan bit lama dengan masker terbalik, baru pasang nilai barunya.$ksp$, $ksp$Gunakan unsigned int. Pergeseran kiri pada bilangan bertanda yang meluap adalah perilaku tak terdefinisi.$ksp$, $ksp$Sebuah tabel berisi nama, pergeseran, dan lebar masker membuat SET dan GET cukup ditulis sekali saja.$ksp$]::text[], 18, array[$ksp$bitwise$ksp$, $ksp$masker$ksp$]::text[]),
  ($ksp$c-12$ksp$, $ksp$peta-rantai-pointer$ksp$, 12, $ksp$Peta Rantai Pointer$ksp$, $ksp$2026-09-21$ksp$, $ksp$2026-09-27T23:59$ksp$, $ksp$SEGFAULT$ksp$, array[$ksp$pointer$ksp$, $ksp$memori-dinamis$ksp$, $ksp$struct$ksp$, $ksp$rekursi$ksp$]::text[], $ksp$Prasyarat antar mata kuliah membentuk graf berarah: Struktur Data mensyaratkan
Algoritma dan Pemrograman, Analisis Algoritma mensyaratkan Struktur Data, dan
seterusnya. Pertanyaan yang selalu muncul saat penyusunan KRS: kalau saya ambil
mata kuliah ini, apa saja yang jadi terbuka setelahnya?

Tugasmu membangun graf berarah dengan simpul yang dialokasikan dinamis, lalu
menjawab pertanyaan keterjangkauan.

## Format masukan

Baris pertama berisi dua bilangan bulat `N` dan `M` — banyaknya simpul dan
busur. Simpul bernomor `1` sampai `N`.

`M` baris berikutnya masing-masing berisi dua bilangan `a` dan `b`, menyatakan
busur berarah dari `a` ke `b`.

Baris berikutnya berisi bilangan bulat `Q`, banyaknya pertanyaan.
`Q` baris berikutnya masing-masing berisi dua bilangan `x` dan `y`.

## Format keluaran

Satu baris untuk setiap pertanyaan: `ya` kalau `y` terjangkau dari `x`, `tidak`
kalau tidak. Setiap simpul selalu terjangkau dari dirinya sendiri, jadi `x == y`
selalu menjawab `ya`.

## Catatan

Graf ini bisa memuat siklus. Penelusuran tanpa penanda simpul yang sudah
dikunjungi akan berputar selamanya.

Daftar ketetanggaan dibangun dari simpul yang dialokasikan dengan `malloc`, satu
per busur. Bebaskan semuanya sebelum program berakhir — kebocoran memori tidak
membuat program ini salah jawab, tapi soal ini bertingkat SEGFAULT dan penilaian
membaca keduanya.

Hati-hati dengan pointer yang menunjuk ke elemen array yang kemudian di-`realloc`.
Setelah realokasi, alamat lamanya tidak lagi berlaku.$ksp$, array[$ksp$1 <= N <= 100000$ksp$, $ksp$0 <= M <= 200000$ksp$, $ksp$1 <= Q <= 1000$ksp$, $ksp$Graf boleh memuat siklus dan busur ganda$ksp$, $ksp$Seluruh simpul yang dialokasikan wajib dibebaskan sebelum program berakhir$ksp$]::text[], $ksp$[{"input":"5 5\n1 2\n2 3\n3 4\n4 2\n1 5\n3\n1 4\n5 1\n2 4","output":"ya\ntidak\nya","penjelasan":"Simpul 2, 3, dan 4 membentuk siklus. Penelusuran tanpa penanda kunjungan akan berputar selamanya di sana."},{"input":"2 1\n1 2\n2\n2 1\n1 2","output":"tidak\nya","penjelasan":"Busurnya berarah. Terjangkau dari 1 ke 2 tidak berarti sebaliknya."},{"input":"3 1\n1 2\n2\n1 1\n1 3","output":"ya\ntidak","penjelasan":"Setiap simpul selalu terjangkau dari dirinya sendiri, meski tidak punya busur ke mana pun."}]$ksp$::jsonb, array[$ksp$Daftar ketetanggaan cukup berupa array kepala sepanjang N, masing-masing menunjuk ke rantai simpul busur.$ksp$, $ksp$Tanpa penanda simpul yang sudah dikunjungi, siklus pada contoh pertama membuat penelusuran tidak pernah berhenti.$ksp$, $ksp$Kedalaman rekursi bisa mencapai N. Untuk N sebesar 100000, penelusuran berbasis stack sendiri lebih aman daripada rekursi.$ksp$]::text[], 14, array[$ksp$graf$ksp$, $ksp$penelusuran$ksp$]::text[]);

insert into public.winners (id, slug, nama, foto, angkatan, challenge_id, minggu, waktu_submit, runtime_ms, pendekatan, kode_solusi, quote, total_menang) values
  ($ksp$w-01$ksp$, $ksp$nadia-puspita-ramadhani$ksp$, $ksp$Nadia Puspita Ramadhani$ksp$, $ksp$https://picsum.photos/seed/ksp-member-nadia/640/800$ksp$, 2024, $ksp$c-01$ksp$, 1, $ksp$2026-07-06T20:14$ksp$, 2, $ksp$Satu lintasan saja sudah cukup. Nilai awal untuk tertinggi dan terendah saya ambil dari elemen pertama, bukan dari nol — kalau semua suhunya negatif, memulai dari nol membuat tertinggi selamanya salah. Total saya simpan sebagai long supaya seribu pembacaan bersuhu 100 pun tidak mendekati batas. Bagian yang paling banyak menjatuhkan orang bukan logikanya, melainkan pembagian bulat di baris terakhir.$ksp$, $ksp$#include <stdio.h>

int main(void) {
    int n;
    if (scanf("%d", &n) != 1 || n <= 0) return 1;

    long total = 0;
    int tertinggi = 0;
    int terendah = 0;

    for (int i = 0; i < n; i++) {
        int suhu;
        if (scanf("%d", &suhu) != 1) return 1;

        total += suhu;
        if (i == 0 || suhu > tertinggi) tertinggi = suhu;
        if (i == 0 || suhu < terendah) terendah = suhu;
    }

    /* Pembagian harus dipaksa jadi pecahan dulu. total / n memakai
       pembagian bulat dan membuang sisanya sebelum sempat dicetak. */
    printf("rata-rata: %.2f\n", (double)total / (double)n);
    printf("tertinggi: %d\n", tertinggi);
    printf("terendah: %d\n", terendah);

    return 0;
}$ksp$, $ksp$Soal pemanasan yang ternyata punya satu jebakan. Saya submit dua kali.$ksp$, 6),
  ($ksp$w-02$ksp$, $ksp$rangga-dwi-saputra$ksp$, $ksp$Rangga Dwi Saputra$ksp$, $ksp$https://picsum.photos/seed/ksp-member-rangga/640/800$ksp$, 2025, $ksp$c-02$ksp$, 2, $ksp$2026-07-15T22:47$ksp$, 4, $ksp$Larangan memakai kurung siku memaksa saya berhenti menganggap array dan pointer sebagai dua hal berbeda. Saya simpan satu pointer ke elemen pertama dan satu ke posisi tepat setelah elemen terakhir, lalu maju k langkah setiap putaran. Perbandingannya p < akhir, bukan menghitung indeks — jadi tidak ada satu pun perkalian dalam perulangannya.$ksp$, $ksp$#include <stdio.h>
#include <stdlib.h>

/* Tidak ada satu pun tanda kurung siku di berkas ini. Setiap akses
   ke elemen array ditulis sebagai aritmetika pointer. */
int main(void) {
    int n;
    int k;
    if (scanf("%d %d", &n, &k) != 2 || n <= 0 || k <= 0) return 1;

    int *data = malloc((size_t)n * sizeof *data);
    if (data == NULL) return 1;

    for (int i = 0; i < n; i++) {
        if (scanf("%d", data + i) != 1) {
            free(data);
            return 1;
        }
    }

    const int *p = data;
    const int *akhir = data + n;
    int pertama = 1;

    while (p < akhir) {
        if (!pertama) putchar(' ');
        printf("%d", *p);
        pertama = 0;
        p += k;
    }
    putchar('\n');

    free(data);
    return 0;
}$ksp$, $ksp$Ternyata selama ini saya menulis *(data + i) terus, cuma tidak sadar.$ksp$, 2),
  ($ksp$w-03$ksp$, $ksp$theresia-maharani-putri$ksp$, $ksp$Theresia Maharani Putri$ksp$, $ksp$https://picsum.photos/seed/ksp-member-theresia/640/800$ksp$, 2025, $ksp$c-03$ksp$, 3, $ksp$2026-07-20T19:05$ksp$, 1, $ksp$Saya coba dulu membandingkan langsung sambil melompati spasi dan tanda baca dari dua arah, dan langsung berantakan di kalimat yang punya tanda baca beruntun. Menyalin karakter yang lolos saringan ke buffer baru memakai memori ekstra, tapi seluruh logikanya jadi muat dalam satu while yang bisa saya baca sekali jalan. Untuk 200 karakter, memori bukan masalah.$ksp$, $ksp$#include <ctype.h>
#include <stdio.h>

int main(void) {
    char baris[256];
    if (fgets(baris, (int)sizeof baris, stdin) == NULL) return 1;

    /* Saring dulu jadi huruf kecil dan angka saja. Membandingkan
       sambil melompati tanda baca di dua arah sekaligus jauh lebih
       mudah salah daripada menyalinnya sekali. */
    char bersih[256];
    int n = 0;
    for (int i = 0; baris[i] != '\0'; i++) {
        unsigned char c = (unsigned char)baris[i];
        if (isalnum(c)) {
            bersih[n] = (char)tolower(c);
            n++;
        }
    }

    int kiri = 0;
    int kanan = n - 1;
    int palindrom = 1;

    while (kiri < kanan) {
        if (bersih[kiri] != bersih[kanan]) {
            palindrom = 0;
            break;
        }
        kiri++;
        kanan--;
    }

    puts(palindrom ? "palindrom" : "bukan palindrom");
    return 0;
}$ksp$, $ksp$Pelajarannya: kode yang lebih pendek belum tentu kode yang lebih benar.$ksp$, 9),
  ($ksp$w-04$ksp$, $ksp$theresia-maharani-putri$ksp$, $ksp$Theresia Maharani Putri$ksp$, $ksp$https://picsum.photos/seed/ksp-member-theresia/640/800$ksp$, 2025, $ksp$c-04$ksp$, 4, $ksp$2026-07-27T21:32$ksp$, 3, $ksp$Kuncinya menyimpan digit satuan di indeks nol. Dengan urutan itu, sisa penyimpanan merambat maju ke indeks yang lebih besar dan array-nya tumbuh ke arah yang sama — tidak ada penggeseran sama sekali. Kesalahan saya yang pertama: menghabiskan sisa penyimpanan dengan satu if. Untuk faktor dua digit, sisanya bisa lebih dari sembilan dan harus dihabiskan dengan while.$ksp$, $ksp$#include <stdio.h>

/* 100! punya 158 digit. 200 elemen memberi ruang lebih dari cukup. */
#define MAKS_DIGIT 200

int main(void) {
    int n;
    if (scanf("%d", &n) != 1 || n < 0) return 1;

    /* Digit paling tidak signifikan di indeks nol, supaya perambatan
       sisa penyimpanan bergerak maju, bukan mundur. */
    int digit[MAKS_DIGIT] = {0};
    int panjang = 1;
    digit[0] = 1;

    for (int faktor = 2; faktor <= n; faktor++) {
        int simpan = 0;

        for (int i = 0; i < panjang; i++) {
            int hasil = digit[i] * faktor + simpan;
            digit[i] = hasil % 10;
            simpan = hasil / 10;
        }

        while (simpan > 0) {
            digit[panjang] = simpan % 10;
            panjang++;
            simpan /= 10;
        }
    }

    for (int i = panjang - 1; i >= 0; i--) {
        putchar('0' + digit[i]);
    }
    putchar('\n');

    return 0;
}$ksp$, $ksp$Perkalian bersusun yang diajarkan di SD ternyata algoritma yang benar-benar dipakai.$ksp$, 9),
  ($ksp$w-05$ksp$, $ksp$gilang-prasetyo-nugroho$ksp$, $ksp$Gilang Prasetyo Nugroho$ksp$, $ksp$https://picsum.photos/seed/ksp-member-gilang/640/800$ksp$, 2024, $ksp$c-05$ksp$, 5, $ksp$2026-08-03T18:22$ksp$, 6, $ksp$Struct-nya sengaja saya buat menyimpan nama sebagai array, bukan pointer. Kalau nama disimpan sebagai char*, qsort akan menukar pointer-nya dan itu masih benar, tapi saya harus menjamin memori yang ditunjuk tetap hidup. Array di dalam struct ikut berpindah saat elemennya ditukar, jadi tidak ada yang perlu dijaga. Pembanding mengembalikan selisih nilai untuk kunci pertama dan hasil strcmp apa adanya untuk kunci kedua.$ksp$, $ksp$#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct {
    char nama[33];
    int nilai;
} Peserta;

/* Nilai menurun lebih dulu; nama menaik hanya dipakai kalau seri. */
static int bandingkan(const void *a, const void *b) {
    const Peserta *p = (const Peserta *)a;
    const Peserta *q = (const Peserta *)b;

    if (p->nilai != q->nilai) return q->nilai - p->nilai;
    return strcmp(p->nama, q->nama);
}

int main(void) {
    int n;
    if (scanf("%d", &n) != 1 || n <= 0) return 1;

    Peserta *daftar = malloc((size_t)n * sizeof *daftar);
    if (daftar == NULL) return 1;

    for (int i = 0; i < n; i++) {
        if (scanf("%32s %d", daftar[i].nama, &daftar[i].nilai) != 2) {
            free(daftar);
            return 1;
        }
    }

    qsort(daftar, (size_t)n, sizeof *daftar, bandingkan);

    for (int i = 0; i < n; i++) {
        printf("%d. %s %d\n", i + 1, daftar[i].nama, daftar[i].nilai);
    }

    free(daftar);
    return 0;
}$ksp$, $ksp$Dua array paralel itu bom waktu. Satu struct menyelesaikan semuanya.$ksp$, 8),
  ($ksp$w-06$ksp$, $ksp$kevin-alexander-tanuwijaya$ksp$, $ksp$Kevin Alexander Tanuwijaya$ksp$, $ksp$https://picsum.photos/seed/ksp-member-kevin/640/800$ksp$, 2024, $ksp$c-06$ksp$, 6, $ksp$2026-08-14T23:11$ksp$, 5, $ksp$Submission pertama saya lolos semua contoh tapi ditolak karena kebocoran memori: saya hanya membebaskan simpul yang diambil lewat perintah A, dan lupa sisanya saat program berakhir. Perbaikannya satu perulangan di akhir main. Satu hal lagi yang saya catat: pada perintah A, pointer ke simpul berikutnya harus disimpan sebelum free, bukan sesudah. Versi yang salah tetap jalan di laptop saya, dan itu justru yang berbahaya.$ksp$, $ksp$#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct Simpul {
    char judul[65];
    struct Simpul *next;
} Simpul;

int main(void) {
    int n;
    if (scanf("%d", &n) != 1) return 1;

    Simpul *depan = NULL;

    for (int i = 0; i < n; i++) {
        char perintah[8];
        if (scanf("%7s", perintah) != 1) break;

        if (strcmp(perintah, "T") == 0) {
            Simpul *baru = malloc(sizeof *baru);
            if (baru == NULL) return 1;
            if (scanf("%64s", baru->judul) != 1) {
                free(baru);
                return 1;
            }
            baru->next = depan;
            depan = baru;
        } else if (strcmp(perintah, "A") == 0) {
            if (depan == NULL) {
                puts("kosong");
                continue;
            }
            /* Simpan penerusnya SEBELUM membebaskan simpul ini.
               Membaca depan->next setelah free adalah perilaku tak
               terdefinisi, dan biasanya kelihatan berhasil sampai
               suatu hari tidak. */
            Simpul *berikut = depan->next;
            puts(depan->judul);
            free(depan);
            depan = berikut;
        } else if (strcmp(perintah, "L") == 0) {
            if (depan == NULL) {
                puts("kosong");
                continue;
            }
            for (const Simpul *p = depan; p != NULL; p = p->next) {
                printf("%s", p->judul);
                if (p->next != NULL) printf(" -> ");
            }
            putchar('\n');
        }
    }

    while (depan != NULL) {
        Simpul *berikut = depan->next;
        free(depan);
        depan = berikut;
    }

    return 0;
}$ksp$, $ksp$Program yang kelihatan jalan dan program yang benar itu dua hal berbeda.$ksp$, 3),
  ($ksp$w-07$ksp$, $ksp$salsabila-rahmawati$ksp$, $ksp$Salsabila Rahmawati$ksp$, $ksp$https://picsum.photos/seed/ksp-member-salsabila/640/800$ksp$, 2025, $ksp$c-07$ksp$, 7, $ksp$2026-08-18T20:40$ksp$, 9, $ksp$Empat batas yang menyusut, dan dua penjagaan tambahan sebelum melintasi sisi bawah dan sisi kiri. Tanpa dua penjagaan itu, matriks satu baris akan mencetak barisnya dua kali — sekali dari kiri ke kanan, sekali dari kanan ke kiri. Kasus itu tidak ada di contoh yang diberikan, jadi saya menemukannya hanya karena iseng menguji 1 x 5 sendiri.$ksp$, $ksp$#include <stdio.h>
#include <stdlib.h>

int main(void) {
    int r;
    int c;
    if (scanf("%d %d", &r, &c) != 2 || r <= 0 || c <= 0) return 1;

    int *m = malloc((size_t)r * (size_t)c * sizeof *m);
    if (m == NULL) return 1;

    for (int i = 0; i < r * c; i++) {
        if (scanf("%d", &m[i]) != 1) {
            free(m);
            return 1;
        }
    }

    int atas = 0;
    int bawah = r - 1;
    int kiri = 0;
    int kanan = c - 1;
    int pertama = 1;

    while (atas <= bawah && kiri <= kanan) {
        for (int j = kiri; j <= kanan; j++) {
            if (!pertama) putchar(' ');
            printf("%d", m[atas * c + j]);
            pertama = 0;
        }
        atas++;

        for (int i = atas; i <= bawah; i++) {
            if (!pertama) putchar(' ');
            printf("%d", m[i * c + kanan]);
            pertama = 0;
        }
        kanan--;

        /* Dua penjagaan ini yang menyelamatkan matriks satu baris dan
           satu kolom dari tercetak dua kali. */
        if (atas <= bawah) {
            for (int j = kanan; j >= kiri; j--) {
                if (!pertama) putchar(' ');
                printf("%d", m[bawah * c + j]);
                pertama = 0;
            }
            bawah--;
        }

        if (kiri <= kanan) {
            for (int i = bawah; i >= atas; i--) {
                if (!pertama) putchar(' ');
                printf("%d", m[i * c + kiri]);
                pertama = 0;
            }
            kiri++;
        }
    }

    putchar('\n');
    free(m);
    return 0;
}$ksp$, $ksp$Contoh yang diberikan itu lantai, bukan langit-langit. Uji sendiri yang lain.$ksp$, 2),
  ($ksp$w-08$ksp$, $ksp$yohanes-krisna-adiputra$ksp$, $ksp$Yohanes Krisna Adiputra$ksp$, $ksp$https://picsum.photos/seed/ksp-member-yohanes/640/800$ksp$, 2024, $ksp$c-08$ksp$, 8, $ksp$2026-08-29T16:58$ksp$, 12, $ksp$strchr untuk menemukan titik koma, lalu menimpanya dengan karakter nol. Satu baris itu langsung memotong string jadi dua tanpa menyalin apa pun: bagian sebelum titik koma jadi nama, dan pointer setelahnya langsung bisa diberikan ke strtol. Bagian yang paling saya perhatikan justru fclose setelah menulis — tanpa itu, sebagian isi berkas masih di buffer saat saya membukanya kembali, dan keluarannya terpotong.$ksp$, $ksp$#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAKS_NAMA 256

typedef struct {
    char nama[33];
    long total;
} Rekap;

static int bandingkan(const void *a, const void *b) {
    const Rekap *p = (const Rekap *)a;
    const Rekap *q = (const Rekap *)b;
    return strcmp(p->nama, q->nama);
}

int main(void) {
    int n;
    if (scanf("%d", &n) != 1 || n < 0) return 1;

    Rekap rekap[MAKS_NAMA];
    int jumlah = 0;

    for (int i = 0; i < n; i++) {
        char baris[128];
        if (scanf("%127s", baris) != 1) return 1;

        char *pemisah = strchr(baris, ';');
        if (pemisah == NULL) return 1;
        *pemisah = '\0';
        long durasi = strtol(pemisah + 1, NULL, 10);

        int ketemu = -1;
        for (int j = 0; j < jumlah; j++) {
            if (strcmp(rekap[j].nama, baris) == 0) {
                ketemu = j;
                break;
            }
        }

        if (ketemu >= 0) {
            rekap[ketemu].total += durasi;
        } else {
            if (jumlah == MAKS_NAMA) return 1;
            snprintf(rekap[jumlah].nama, sizeof rekap[jumlah].nama, "%s", baris);
            rekap[jumlah].total = durasi;
            jumlah++;
        }
    }

    qsort(rekap, (size_t)jumlah, sizeof rekap[0], bandingkan);

    FILE *tulis = fopen("rekap.txt", "w");
    if (tulis == NULL) {
        perror("rekap.txt");
        return EXIT_FAILURE;
    }
    for (int i = 0; i < jumlah; i++) {
        fprintf(tulis, "%s %ld\n", rekap[i].nama, rekap[i].total);
    }
    /* Tutup sebelum dibuka lagi: data yang masih tertahan di buffer
       belum tentu sudah sampai ke disk. */
    fclose(tulis);

    FILE *baca = fopen("rekap.txt", "r");
    if (baca == NULL) {
        perror("rekap.txt");
        return EXIT_FAILURE;
    }

    char baris[160];
    while (fgets(baris, (int)sizeof baris, baca) != NULL) {
        fputs(baris, stdout);
    }
    fclose(baca);

    return 0;
}$ksp$, $ksp$fclose bukan formalitas. Itu yang benar-benar mengirim data ke disk.$ksp$, 4),
  ($ksp$w-09$ksp$, $ksp$ivana-christabel-sudarsono$ksp$, $ksp$Ivana Christabel Sudarsono$ksp$, $ksp$https://picsum.photos/seed/ksp-member-ivana/640/800$ksp$, 2024, $ksp$c-09$ksp$, 9, $ksp$2026-09-04T21:03$ksp$, 31, $ksp$Kapasitas awal empat, digandakan setiap kali penuh. Yang membuat saya berhenti sebentar adalah baris realloc. Menulis data = realloc(data, ...) kelihatan wajar sampai kamu sadar bahwa kalau realloc gagal, ia mengembalikan NULL tanpa membebaskan blok lama — dan kamu baru saja menimpa satu-satunya pointer ke blok itu. Hasilnya saya tampung dulu di variabel sementara, dan blok lama baru dilepas kalau realokasinya berhasil.$ksp$, $ksp$#include <stdio.h>
#include <stdlib.h>

int main(void) {
    int kapasitas = 4;
    int jumlah = 0;
    int *data = malloc((size_t)kapasitas * sizeof *data);
    if (data == NULL) return EXIT_FAILURE;

    long total = 0;
    int nilai;

    while (scanf("%d", &nilai) == 1) {
        if (jumlah == kapasitas) {
            int kapasitas_baru = kapasitas * 2;
            /* Hasil realloc ditampung dulu. Kalau langsung ditimpakan ke
               data dan realloc gagal, satu-satunya pointer ke blok lama
               hilang dan memorinya bocor untuk selamanya. */
            int *lebih = realloc(data, (size_t)kapasitas_baru * sizeof *data);
            if (lebih == NULL) {
                free(data);
                return EXIT_FAILURE;
            }
            data = lebih;
            kapasitas = kapasitas_baru;
        }

        data[jumlah] = nilai;
        jumlah++;
        total += nilai;
    }

    printf("jumlah elemen: %d\n", jumlah);
    printf("total: %ld\n", total);

    printf("terbalik:");
    for (int i = jumlah - 1; i >= 0; i--) {
        printf(" %d", data[i]);
    }
    putchar('\n');

    free(data);
    return 0;
}$ksp$, $ksp$Baris yang paling berbahaya di program saya justru yang paling pendek.$ksp$, 3),
  ($ksp$w-10$ksp$, $ksp$damar-aji-setiawan$ksp$, $ksp$Damar Aji Setiawan$ksp$, $ksp$https://picsum.photos/seed/ksp-member-damar/640/800$ksp$, 2023, $ksp$c-10$ksp$, 10, $ksp$2026-09-07T22:19$ksp$, 88, $ksp$Rekursinya sendiri tujuh baris dan tidak berubah dari versi pertama. Yang saya ubah adalah penghitung langkah: awalnya saya kirim sebagai parameter dan mengembalikannya lagi, yang membuat tanda tangan fungsinya berantakan. Satu variabel static jauh lebih jelas untuk kasus ini. Banyaknya langkah saya hitung langsung dengan pergeseran bit, bukan dengan menghitung berapa kali fungsinya dipanggil.$ksp$, $ksp$#include <stdio.h>

static long nomor = 0;

static void pindah(int n, char dari, char ke, char bantu) {
    if (n == 0) return;

    pindah(n - 1, dari, bantu, ke);
    nomor++;
    printf("%ld: %c->%c\n", nomor, dari, ke);
    pindah(n - 1, bantu, ke, dari);
}

int main(void) {
    int n;
    if (scanf("%d", &n) != 1 || n < 1) return 1;

    long langkah = (1L << n) - 1L;
    printf("%ld langkah\n", langkah);

    pindah(n, 'A', 'C', 'B');
    return 0;
}$ksp$, $ksp$Kalau kasus dasarnya benar, sisanya hampir selalu menulis dirinya sendiri.$ksp$, 5),
  ($ksp$w-11$ksp$, $ksp$fransiska-ayu-larasati$ksp$, $ksp$Fransiska Ayu Larasati$ksp$, $ksp$https://picsum.photos/seed/ksp-member-fransiska/640/800$ksp$, 2024, $ksp$c-11$ksp$, 11, $ksp$2026-09-19T14:26$ksp$, 15, $ksp$Daripada menulis empat pasang SET dan GET, saya buat satu tabel berisi nama medan, besar pergeseran, dan maskernya. Setelah itu SET dan GET masing-masing cukup ditulis sekali. Dua hal yang saya jaga: statusnya unsigned, karena pergeseran kiri pada bilangan bertanda yang meluap tidak terdefinisi; dan nilai baru selalu di-AND dengan maskernya sebelum digeser, supaya masukan yang melebihi lebar medan tidak pernah merembet ke medan tetangga.$ksp$, $ksp$#include <stdio.h>
#include <string.h>

typedef struct {
    const char *nama;
    unsigned int geser;
    unsigned int masker;
} Medan;

static const Medan MEDAN[] = {
    {"hadir",     0u, 0xFFu},
    {"nilai",     8u, 0xFFu},
    {"lunas",    16u, 0x01u},
    {"angkatan", 17u, 0x0Fu},
};

static const Medan *cari_medan(const char *nama) {
    const int banyak = (int)(sizeof MEDAN / sizeof MEDAN[0]);
    for (int i = 0; i < banyak; i++) {
        if (strcmp(MEDAN[i].nama, nama) == 0) return &MEDAN[i];
    }
    return NULL;
}

int main(void) {
    int n;
    if (scanf("%d", &n) != 1) return 1;

    /* unsigned, bukan int: pergeseran kiri pada bilangan bertanda yang
       meluap adalah perilaku tak terdefinisi. */
    unsigned int status = 0u;

    for (int i = 0; i < n; i++) {
        char perintah[8];
        if (scanf("%7s", perintah) != 1) break;

        if (strcmp(perintah, "RAW") == 0) {
            printf("%08X\n", status);
            continue;
        }

        char nama[16];
        if (scanf("%15s", nama) != 1) break;

        const Medan *medan = cari_medan(nama);
        if (medan == NULL) continue;

        if (strcmp(perintah, "SET") == 0) {
            unsigned int baru;
            if (scanf("%u", &baru) != 1) break;
            status &= ~(medan->masker << medan->geser);
            status |= (baru & medan->masker) << medan->geser;
        } else if (strcmp(perintah, "GET") == 0) {
            printf("%u\n", (status >> medan->geser) & medan->masker);
        }
    }

    return 0;
}$ksp$, $ksp$Menang pertama saya, dan kebetulan di soal SEGFAULT. Saya masih agak kaget.$ksp$, 1);

insert into public.registration_rounds (buka, tutup) values
  ($ksp$2026-08-24T00:00$ksp$, $ksp$2026-09-11T23:59$ksp$);
