-- Generated by scripts/generate-seed.mts. Do not edit by hand.

truncate public.winners, public.challenges, public.news_posts, public.modules, public.sesi, public.registration_rounds restart identity cascade;

insert into public.modules (id, minggu, judul, rilis, tentor_pj, koordinator, ringkasan, berkas_url, tenggat) values
  ($ksp$mod-01$ksp$, 1, $ksp$Flowchart 1$ksp$, $ksp$2026-09-21$ksp$, array[$ksp$Sabrina$ksp$, $ksp$Eldha$ksp$]::text[], $ksp$Michelle$ksp$, $ksp$Simbol-simbol flowchart dan alur urut: terminal, proses, masukan dan keluaran, serta cara membaca diagram dari atas ke bawah.$ksp$, null, null),
  ($ksp$mod-02$ksp$, 2, $ksp$Flowchart 2$ksp$, $ksp$2026-09-28$ksp$, array[$ksp$Sabrina$ksp$, $ksp$Eldha$ksp$]::text[], $ksp$Michelle$ksp$, $ksp$Percabangan dan perulangan di flowchart: simbol keputusan, alur yang kembali ke atas, dan menelusuri diagram dengan tabel jejak.$ksp$, null, null),
  ($ksp$mod-03$ksp$, 3, $ksp$Tipe Data$ksp$, $ksp$2026-10-05$ksp$, array[$ksp$Boby$ksp$, $ksp$Kley$ksp$]::text[], $ksp$Kley$ksp$, $ksp$Aturan penamaan variabel, tipe data dasar di C, dan program sekuensial pertama dengan printf dan scanf.$ksp$, null, null),
  ($ksp$mod-04$ksp$, 4, $ksp$Pemilihan$ksp$, $ksp$2026-11-02$ksp$, array[$ksp$Dwi$ksp$, $ksp$Andrew$ksp$]::text[], $ksp$Kley$ksp$, $ksp$if, else if, else, dan switch — memilih jalur program berdasarkan kondisi.$ksp$, null, null),
  ($ksp$mod-05$ksp$, 5, $ksp$Perulangan 1$ksp$, $ksp$2026-11-09$ksp$, array[$ksp$Ardhya$ksp$, $ksp$Beto$ksp$]::text[], $ksp$Rena$ksp$, $ksp$for dan while: menghitung, menjumlahkan, dan menentukan kapan sebuah perulangan berhenti.$ksp$, null, null),
  ($ksp$mod-06$ksp$, 6, $ksp$Perulangan 2$ksp$, $ksp$2026-11-16$ksp$, array[$ksp$Doni$ksp$, $ksp$Rena$ksp$]::text[], $ksp$Rena$ksp$, $ksp$do-while, perulangan bersarang, serta break dan continue.$ksp$, null, null),
  ($ksp$mod-07$ksp$, 7, $ksp$Prosedur 1$ksp$, $ksp$2026-11-23$ksp$, array[$ksp$Richard$ksp$, $ksp$Petra$ksp$]::text[], $ksp$Richard$ksp$, $ksp$Memecah program menjadi prosedur: deklarasi, pemanggilan, dan parameter masukan.$ksp$, null, null),
  ($ksp$mod-08$ksp$, 8, $ksp$Prosedur 2$ksp$, $ksp$2027-03-01$ksp$, array[$ksp$Adit$ksp$, $ksp$Tristan$ksp$]::text[], $ksp$Richard$ksp$, $ksp$Parameter keluaran: kenapa nilai yang diubah di dalam prosedur tidak ikut kembali, dan cara memperbaikinya dengan pointer.$ksp$, null, null),
  ($ksp$mod-09$ksp$, 9, $ksp$Fungsi$ksp$, $ksp$2027-03-15$ksp$, array[$ksp$Nathan$ksp$, $ksp$Stella$ksp$]::text[], $ksp$Michelle$ksp$, $ksp$Fungsi yang mengembalikan nilai, return, dan kapan memilih fungsi daripada prosedur.$ksp$, null, null),
  ($ksp$mod-10$ksp$, 10, $ksp$Array$ksp$, $ksp$2027-04-26$ksp$, array[$ksp$Albert$ksp$, $ksp$Nadya$ksp$]::text[], $ksp$Audrey$ksp$, $ksp$Array satu dimensi: indeks, perulangan atas array, pencarian, dan nilai terbesar atau terkecil.$ksp$, null, null),
  ($ksp$mod-11$ksp$, 11, $ksp$Record$ksp$, $ksp$2027-05-03$ksp$, array[$ksp$Jolie$ksp$, $ksp$Epun$ksp$]::text[], $ksp$Audrey$ksp$, $ksp$struct sebagai record: mengelompokkan data yang saling berkaitan dan mengakses tiap field-nya.$ksp$, null, null),
  ($ksp$mod-12$ksp$, 12, $ksp$Array of Record$ksp$, $ksp$2027-05-18$ksp$, array[$ksp$Adit$ksp$]::text[], $ksp$Audrey$ksp$, $ksp$Menggabungkan keduanya: array berisi struct untuk data berbentuk tabel, seperti daftar nilai satu kelas.$ksp$, null, $ksp$2027-05-23T23:59$ksp$);

insert into public.sesi (id, judul, rilis, pj, ringkasan) values
  ($ksp$sesi-games$ksp$, $ksp$Games$ksp$, $ksp$2026-11-30$ksp$, $ksp$PH$ksp$, $ksp$Sesi santai di akhir semester ganjil: permainan dan kuis seputar materi yang sudah dipelajari. Tanpa modul dan tanpa tugas.$ksp$),
  ($ksp$sesi-review$ksp$, $ksp$Review Materi$ksp$, $ksp$2027-02-22$ksp$, $ksp$PH$ksp$, $ksp$Mengulang materi semester ganjil sebelum lanjut ke prosedur dan fungsi. Tanpa modul dan tanpa tugas.$ksp$);

insert into public.news_posts (id, slug, judul, tanggal, kategori, cover, excerpt, penulis, body_mdx, tags) values
  ($ksp$n-01$ksp$, $ksp$pendaftaran-anggota-baru-2026$ksp$, $ksp$Pendaftaran Anggota Baru Semester Ganjil 2026/2027 Dibuka$ksp$, $ksp$2026-08-24$ksp$, $ksp$pengumuman$ksp$, $ksp$https://picsum.photos/seed/ksp-berita-pendaftaran/1200/675$ksp$, $ksp$Terbuka untuk mahasiswa aktif UAJY semester 1 sebagai persiapan mata kuliah dasar pemrograman C, tanpa syarat kemampuan awal. Semester lalu sembilan dari dua puluh tujuh anggota baru mendaftar tanpa pengalaman apa pun.$ksp$, $ksp$Salsabila Rahmawati$ksp$, $ksp$Pendaftaran anggota baru Kelompok Studi Pemrograman untuk semester ganjil
2026/2027 resmi dibuka mulai hari ini sampai 11 September 2026. Pendaftaran
terbuka untuk mahasiswa aktif UAJY semester 1, dan tidak ada syarat kemampuan
awal. Kelasnya disusun untuk mempersiapkanmu menghadapi mata kuliah dasar
pemrograman berbahasa C.

## Tidak perlu bisa C dulu

Ini pertanyaan yang paling sering masuk ke kotak masuk kami, jadi mari
diselesaikan di awal: **kamu tidak perlu sudah bisa memrogram untuk mendaftar.**

Kelasnya dimulai dari nol. Kalau kamu belum pernah menulis satu baris kode pun,
tentor akan mendampingimu dari pertemuan pertama. Kalau sudah pernah, kelas ini
jadi tempat merapikan dasar sebelum kuliahnya dimulai.

Semester lalu, sembilan dari dua puluh tujuh anggota baru mendaftar tanpa
pengalaman apa pun. Empat di antaranya sekarang mengisi papan peringkat
challenge mingguan.

## Apa yang kamu dapat

- Kelas rutin setiap Jumat sore, 90 menit, di ruang FTI 3.2
- Pendampingan satu tentor untuk empat peserta
- Challenge mingguan dengan pembahasan solusi terbuka
- Akses ke arsip modul dan soal latihan
- Sertifikat keanggotaan di akhir tahun ajaran, bisa ditukar SPAMA tipe organisasi

Biaya pendaftaran Rp150.000, dibayar sekali. Kalau presensimu memenuhi, 70%
(Rp105.000) dikembalikan sebagai cashback. Tidak ada iuran bulanan.

## Alur pendaftaran

1. Isi formulir pendaftaran daring
2. Ikuti sesi perkenalan pada 12 September 2026
3. Pilih jalur kelas yang sesuai
4. Mulai kelas pertama pada 19 September 2026

Sesi perkenalan bukan seleksi. Tidak ada yang ditolak. Sesi itu ada supaya kamu
bisa bertanya sebelum memutuskan, dan supaya kami bisa menempatkanmu di jalur
yang tepat.

## Kenapa C, di tahun 2026

Pertanyaan yang wajar. Hampir tidak ada orang yang memulai proyek baru dengan C
sekarang, dan itu memang bukan tujuannya.

Alasannya sederhana: C tidak menyembunyikan apa pun. Ketika kamu menulis Python
atau JavaScript, banyak keputusan sudah diambil untukmu — kapan memori
dialokasikan, kapan dilepaskan, bagaimana sebuah string disimpan. Semua itu tetap
terjadi, hanya saja di tempat yang tidak kamu lihat.

Setelah satu semester di C, hal-hal itu berhenti jadi misteri. Dan ketika kamu
kembali ke bahasa yang kamu pakai sehari-hari, kamu membacanya dengan cara yang
berbeda.$ksp$, array[$ksp$pendaftaran$ksp$, $ksp$anggota-baru$ksp$, $ksp$kelas$ksp$]::text[]),
  ($ksp$n-02$ksp$, $ksp$pemenang-termuda-challenge$ksp$, $ksp$Theresia Menang Dua Minggu Beruntun di Musim Keduanya$ksp$, $ksp$2026-08-01$ksp$, $ksp$prestasi$ksp$, $ksp$https://picsum.photos/seed/ksp-berita-theresia/1200/675$ksp$, $ksp$Angkatan 2025, bergabung lewat challenge sebelum mengambil satu kelas pun, dan kini memimpin papan peringkat sepanjang masa dengan sembilan kemenangan.$ksp$, $ksp$Damar Aji Setiawan$ksp$, $ksp$Theresia Maharani Putri, mahasiswa angkatan 2025, memenangi challenge minggu
ketiga dan keempat berturut-turut. Dengan itu ia menjadi peserta angkatan pertama
pertama yang memenangi dua challenge beruntun sejak program ini dimulai pada 2025.

## Dua soal yang berbeda jauh

Minggu ketiga adalah soal string bertingkat MUDAH. Minggu keempat adalah soal
aritmetika bilangan besar bertingkat SEDANG, yang menuntut peserta menyimpan
hasilnya sebagai array digit karena tidak ada tipe bilangan bulat di C yang cukup
besar untuk menampung `25!`.

Keduanya diselesaikan dalam hitungan jam setelah soalnya terbit.

"Soal minggu ketiga saya kerjakan dua kali," katanya. "Percobaan pertama saya coba
membandingkan langsung sambil melompati tanda baca dari dua arah, dan langsung
berantakan begitu ada tanda baca beruntun. Saya buang, lalu tulis ulang dengan cara
yang lebih panjang tapi bisa saya baca sekali jalan."

Pendekatan itu, menurut Reza Maulana Hakim yang memeriksa submission tersebut,
adalah alasan utama ia menang. "Kode yang lebih pendek belum tentu kode yang lebih
benar. Dia tahu kapan harus membuang percobaan pertamanya, dan itu keterampilan
yang biasanya butuh waktu lama untuk tumbuh."

## Masuk lewat challenge

Theresia bergabung dengan KSP pada Februari 2026, empat bulan sebelum musim kedua
dimulai, dan tidak langsung mengambil kelas. Ia mengerjakan challenge lebih dulu.

"Saya ikut karena penasaran, bukan karena mau masuk kelompok studi. Baru setelah
soal SEGFAULT pertama saya tembus, saya sadar saya sudah belajar lebih banyak dalam
tiga minggu daripada satu semester sebelumnya."

Ia sekarang mengisi posisi staf di Divisi Akademik dan ikut menyiapkan sesi latihan
untuk anggota baru.

## Papan peringkat sementara

Dengan dua kemenangan musim ini, total kemenangan sepanjang masa Theresia mencapai
sembilan, memimpin papan peringkat di atas Gilang Prasetyo Nugroho yang mengoleksi
delapan.

Papan peringkat lengkap tersedia di halaman Hall of Fame dan diperbarui setiap
Senin pagi.$ksp$, array[$ksp$challenge$ksp$, $ksp$hall-of-fame$ksp$, $ksp$anggota$ksp$]::text[]),
  ($ksp$n-03$ksp$, $ksp$challenge-mingguan-musim-kedua$ksp$, $ksp$Challenge Mingguan Musim Kedua Dimulai Hari Ini$ksp$, $ksp$2026-07-06$ksp$, $ksp$pengumuman$ksp$, $ksp$https://picsum.photos/seed/ksp-berita-challenge/1200/675$ksp$, $ksp$Dua belas soal, satu setiap Senin. Tiga perubahan dari musim pertama: tingkat SEGFAULT, petunjuk yang terkunci bertingkat, dan solusi pemenang yang dipublikasikan lengkap dengan tulisan pendekatannya.$ksp$, $ksp$Nadia Puspita Ramadhani$ksp$, $ksp$Challenge mingguan musim kedua dimulai hari ini. Dua belas soal, satu soal setiap
Senin, dengan batas pengumpulan Minggu pukul 23.59. Seluruh soal terbuka untuk
anggota maupun non-anggota.

## Yang berubah dari musim pertama

Tiga hal.

**Tingkat kesulitan sekarang punya empat tingkat, bukan tiga.** Tingkat keempat
diberi nama SEGFAULT, dan dipakai untuk soal yang menuntut pengelolaan memori
manual atau struktur data yang dibangun sendiri. Musim ini ada dua soal
bertingkat SEGFAULT, keduanya di paruh kedua.

**Petunjuk sekarang bertingkat dan bisa dibuka satu per satu.** Musim lalu semua
petunjuk muncul sekaligus, dan sebagian besar orang membacanya sebelum sempat
mencoba. Sekarang petunjuknya terkunci dan kamu memilih sendiri kapan membukanya.
Membukanya tidak mengurangi nilai apa pun. Kuncinya ada supaya kamu berhenti
sebentar dan bertanya apakah benar-benar butuh.

**Solusi pemenang dipublikasikan lengkap dengan tulisan pendekatannya.** Kode saja
tidak banyak mengajarkan. Yang mengajarkan adalah cerita tentang percobaan yang
gagal lebih dulu, dan itu yang kami minta dari setiap pemenang.

## Jadwal

Soal terbit setiap Senin pukul 08.00. Pembahasan terbit setiap Selasa berikutnya,
bersamaan dengan pengumuman pemenang.

Peserta yang mengumpulkan setelah batas waktu tetap mendapat koreksi, hanya tidak
masuk penilaian. Kami lebih suka kamu menyelesaikannya terlambat daripada tidak
sama sekali.

## Cara ikut

Tidak ada pendaftaran terpisah. Buka halaman challenge, pilih soal minggu ini,
kerjakan, lalu kirim berkas `.c` ke surel pengurus sebelum batas waktu.

Satu berkas, satu `main`, tanpa pustaka di luar pustaka standar C.$ksp$, array[$ksp$challenge$ksp$, $ksp$pengumuman$ksp$]::text[]),
  ($ksp$n-04$ksp$, $ksp$peringkat-empat-lomba-se-diy$ksp$, $ksp$Peringkat Empat dari 31 Tim di Lomba Pemrograman Se-DIY$ksp$, $ksp$2026-05-12$ksp$, $ksp$prestasi$ksp$, $ksp$https://picsum.photos/seed/ksp-berita-lomba/1200/675$ksp$, $ksp$Delapan dari sebelas soal terselesaikan, terpaut satu soal dari podium. Empat puluh menit hilang di satu soal bitwise, dan tim membawa pulang dua catatan yang langsung masuk materi kelas.$ksp$, $ksp$Damar Aji Setiawan$ksp$, $ksp$Tim Kelompok Studi Pemrograman UAJY meraih peringkat empat pada Lomba Pemrograman
Antar Kampus se-DIY yang digelar Sabtu lalu, bersaing dengan tiga puluh satu tim
dari sebelas perguruan tinggi.

Tim beranggotakan Gilang Prasetyo Nugroho, Damar Aji Setiawan, dan Theresia
Maharani Putri, dengan Reza Maulana Hakim sebagai pendamping.

## Jalannya lomba

Format lomba lima jam dengan sebelas soal. Tim KSP menyelesaikan delapan soal,
terpaut satu soal dari tiga tim di atasnya yang masing-masing menyelesaikan
sembilan.

Empat soal pertama selesai dalam lima puluh menit. Soal kelima, tentang pemampatan
data dengan operasi bit, memakan waktu hampir satu jam penuh, dan menurut catatan
tim itulah yang menentukan selisih akhirnya.

"Kami sebenarnya tahu cara menyelesaikannya sejak menit kelima," kata Gilang.
"Yang lama justru meyakinkan diri bahwa pergeseran bitnya tidak meluap. Kami
kehilangan empat puluh menit untuk sesuatu yang seharusnya bisa dipastikan dalam
sepuluh."

## Yang dibawa pulang

Pendamping tim mencatat dua hal yang akan langsung masuk ke materi kelas.

Yang pertama, kebiasaan menulis kasus uji sendiri sebelum mengumpulkan. Tiga dari
sebelas soal punya kasus tepi yang tidak muncul di contoh, dan dua di antaranya
sempat membuat tim tertahan.

Yang kedua, pembagian peran. Selama tiga jam pertama ketiganya mengerjakan soal
berbeda tanpa berkoordinasi, dan dua di antaranya sempat mengerjakan soal yang
sama tanpa sadar.

Materi tentang strategi tim akan masuk ke kelas persiapan kompetisi semester
depan.

## Peringkat akhir lima besar

1. Universitas Gadjah Mada, 9 soal
2. Universitas Islam Indonesia, 9 soal
3. Universitas Sanata Dharma, 9 soal
4. **Universitas Atma Jaya Yogyakarta, 8 soal**
5. Universitas Ahmad Dahlan, 8 soal$ksp$, array[$ksp$kompetisi$ksp$, $ksp$prestasi$ksp$, $ksp$tim$ksp$]::text[]),
  ($ksp$n-05$ksp$, $ksp$tiga-kesalahan-malloc$ksp$, $ksp$Tiga Kesalahan malloc yang Paling Sering Muncul$ksp$, $ksp$2026-04-18$ksp$, $ksp$tutorial$ksp$, $ksp$https://picsum.photos/seed/ksp-berita-malloc/1200/675$ksp$, $ksp$Dikumpulkan dari lebih dari tiga ratus submission dalam dua semester. Ketiganya punya satu kesamaan: programnya tetap jalan, sampai suatu hari tidak.$ksp$, $ksp$Reza Maulana Hakim$ksp$, $ksp$Setelah mengoreksi lebih dari tiga ratus submission dalam dua semester terakhir,
pola kesalahannya mulai terlihat berulang. Tiga di antaranya menyangkut `malloc`
dan kerabatnya, dan ketiganya punya satu kesamaan: programnya tetap jalan, sampai
suatu hari tidak.

## 1. Menimpa pointer dengan hasil realloc

Ini yang paling sering, dan paling halus.

```c
data = realloc(data, kapasitas_baru * sizeof *data);
```

Baris ini benar selama `realloc` berhasil. Ketika gagal, `realloc` mengembalikan
`NULL` dan **tidak** membebaskan blok lama. Karena hasilnya langsung ditimpakan ke
`data`, satu-satunya pointer ke blok lama baru saja hilang. Memorinya bocor dan
tidak ada cara mengambilnya kembali.

Bentuk yang benar menampung hasilnya lebih dulu:

```c
int *lebih = realloc(data, kapasitas_baru * sizeof *data);
if (lebih == NULL) {
    free(data);
    return EXIT_FAILURE;
}
data = lebih;
```

Di komputer dengan memori besar, versi yang salah hampir tidak pernah gagal saat
diuji. Itu sebabnya ia lolos terus.

## 2. Membaca simpul setelah dibebaskan

Muncul hampir di setiap submission linked list.

```c
free(depan);
depan = depan->next;
```

Setelah `free`, isi memori itu bukan lagi milikmu. Membacanya adalah perilaku tak
terdefinisi. Bukan berarti pasti crash, tapi berarti tidak ada jaminan apa pun.
Dalam praktiknya nilai lamanya sering masih ada di sana beberapa saat, jadi
programnya kelihatan jalan.

Simpan penerusnya lebih dulu:

```c
Simpul *berikut = depan->next;
free(depan);
depan = berikut;
```

## 3. Mengira free menghapus pointernya

`free` melepaskan memorinya. Ia tidak mengubah nilai pointer yang kamu pegang.

```c
free(p);
if (p != NULL) {
    p->nilai = 10;
}
```

Pemeriksaan di atas masih bernilai benar, dan itulah masalahnya. Setelah `free`,
`p` masih menyimpan alamat lama, yang sekarang disebut dangling pointer. Kalau
pointernya masih akan hidup beberapa baris lagi, setel sendiri ke `NULL` supaya
pemeriksaan berikutnya berarti sesuatu.

## Cara memastikan

Tiga kesalahan ini punya satu hal yang sama: pengujian biasa tidak menangkapnya.

Yang menangkapnya adalah alat. Di Linux dan WSL, `valgrind ./program` akan
menyebutkan persis baris mana yang bocor dan baris mana yang membaca memori bebas.
Pada gcc dan clang, `-fsanitize=address` melakukan hal serupa tanpa perlu alat
terpisah.

Biasakan menjalankan salah satunya sebelum mengumpulkan. Butuh satu perintah, dan
menghemat satu sore.$ksp$, array[$ksp$memori$ksp$, $ksp$tutorial$ksp$, $ksp$malloc$ksp$]::text[]),
  ($ksp$n-06$ksp$, $ksp$bahaya-scanf-persen-s$ksp$, $ksp$Berhenti Menulis scanf Persen-s Tanpa Batas Lebar$ksp$, $ksp$2026-02-27$ksp$, $ksp$tutorial$ksp$, $ksp$https://picsum.photos/seed/ksp-berita-scanf/1200/675$ksp$, $ksp$Satu baris yang muncul di hampir setiap submission minggu-minggu awal, dan hampir selalu salah. Perbaikannya cuma satu angka, dan angkanya bukan yang kamu kira.$ksp$, $ksp$Melati Kusumaningrum$ksp$, $ksp$Ada satu baris yang muncul di hampir setiap submission minggu-minggu awal, dan
hampir selalu salah:

```c
char nama[32];
scanf("%s", nama);
```

Baris ini membaca satu kata dari masukan ke dalam `nama`. Masalahnya, `scanf`
tidak tahu bahwa `nama` hanya punya ruang 32 byte. Kalau masukannya lebih panjang,
`scanf` tetap menulis, melewati ujung array, ke memori yang bukan miliknya.

## Kenapa ini tidak ketahuan saat diuji

Karena saat diuji, kamu mengetik nama yang pendek.

Buffer overflow tidak selalu membuat program berhenti. Yang tertimpa mungkin
variabel lain di stack, dan programnya tetap jalan dengan nilai yang diam-diam
berubah. Atau yang tertimpa adalah bagian yang belum dipakai, dan tidak terjadi
apa-apa sama sekali.

Kelas kesalahan inilah yang selama puluhan tahun jadi sumber kerentanan keamanan
paling umum di perangkat lunak yang ditulis dengan C.

## Perbaikannya satu angka

`scanf` menerima batas lebar tepat setelah tanda persen:

```c
char nama[32];
scanf("%31s", nama);
```

Angkanya 31, bukan 32. `scanf` menambahkan karakter nol di akhir, dan karakter itu
juga butuh tempat. Aturannya: **selalu satu kurang dari ukuran array.**

Ini yang paling sering meleset satu. Kalau kamu menulis `%32s` pada array
berukuran 32, kamu baru saja menggeser masalahnya satu byte, bukan
menghilangkannya.

## Untuk membaca satu baris penuh

`%s` berhenti di spasi pertama, jadi ia tidak bisa membaca kalimat. Untuk itu
pakai `fgets`, yang menerima ukuran buffer sebagai argumen:

```c
char baris[256];
if (fgets(baris, sizeof baris, stdin) == NULL) {
    return 1;
}
```

Perhatikan bahwa `fgets` ikut menyimpan karakter baris baru kalau muat. Untuk
sebagian besar soal, hal itu perlu dibuang sendiri.

## Kebiasaan yang layak dibawa

Setiap kali kamu menulis `%s` di dalam `scanf`, berhenti sebentar dan tanyakan
berapa ukuran tujuannya. Kalau kamu tidak bisa menjawabnya langsung, itu tanda
bahwa batasnya memang belum kamu pikirkan.

Mulai musim ini, submission yang memakai `%s` tanpa batas lebar akan dikembalikan
untuk diperbaiki, meski keluarannya sudah benar.$ksp$, array[$ksp$string$ksp$, $ksp$tutorial$ksp$, $ksp$keamanan$ksp$]::text[]),
  ($ksp$n-07$ksp$, $ksp$kompetisi-internal-akhir-semester$ksp$, $ksp$Kompetisi Internal: 34 Peserta, Satu Soal Tak Tersentuh$ksp$, $ksp$2025-12-01$ksp$, $ksp$liputan$ksp$, $ksp$https://picsum.photos/seed/ksp-berita-kompetisi/1200/675$ksp$, $ksp$Tiga jam, delapan soal. Tujuh dari delapan submission untuk soal nomor tujuh sebenarnya sudah benar secara logika, dan yang hilang cuma satu hal.$ksp$, $ksp$Kevin Alexander Tanuwijaya$ksp$, $ksp$Kompetisi internal akhir semester ganjil digelar Jumat lalu di laboratorium FTI,
diikuti 34 peserta dari seluruh angkatan. Formatnya tiga jam, delapan soal,
penilaian berbasis jumlah soal terselesaikan dan waktu pengumpulan.

## Hasil akhir

Peringkat pertama diraih Theresia Maharani Putri dari angkatan 2025, dengan enam
soal terselesaikan dalam dua jam empat puluh menit. Ini pertama kalinya peserta
angkatan pertama memenangi kompetisi internal.

Peringkat kedua dan ketiga masing-masing diraih Gilang Prasetyo Nugroho dan
Damar Aji Setiawan, keduanya dengan enam soal, terpaut sembilan dan enam belas
menit dari peringkat pertama.

## Soal nomor tujuh

Dari delapan soal, hanya satu yang tidak terselesaikan oleh siapa pun: soal
nomor tujuh, tentang penelusuran graf berarah dengan siklus.

Delapan peserta mengumpulkan jawaban dan seluruhnya kehabisan waktu. Setelah
kompetisi, pembahasan menunjukkan bahwa tujuh dari delapan submission itu
sebenarnya sudah benar secara logika. Yang hilang adalah penanda simpul yang
sudah dikunjungi, sehingga penelusurannya berputar selamanya di dalam siklus.

Soal itu kemudian dipakai ulang sebagai challenge minggu kedua belas musim ini,
dengan batas waktu yang lebih longgar.

## Catatan panitia

Dua hal yang dicatat panitia untuk kompetisi berikutnya.

Pertama, waktu tiga jam terlalu pendek untuk delapan soal. Enam soal dalam tiga
jam akan memberi ruang lebih untuk membaca soal dengan benar, yang ternyata jadi
sumber kesalahan terbanyak.

Kedua, sistem penilaian akan membekukan papan peringkat tiga puluh menit
terakhir. Papan yang terus berubah sampai detik akhir memang seru untuk ditonton,
tapi membuat sebagian peserta panik dan meninggalkan soal yang hampir selesai.$ksp$, array[$ksp$kompetisi$ksp$, $ksp$liputan$ksp$, $ksp$graf$ksp$]::text[]),
  ($ksp$n-08$ksp$, $ksp$workshop-manajemen-memori$ksp$, $ksp$Catatan dari Workshop Manajemen Memori$ksp$, $ksp$2025-10-27$ksp$, $ksp$liputan$ksp$, $ksp$https://picsum.photos/seed/ksp-berita-workshop/1200/675$ksp$, $ksp$Dibuka bukan dengan malloc, melainkan dengan menggambar. Dari 28 gambar, hanya 6 yang menempatkan pointer sebagai variabel yang punya alamatnya sendiri.$ksp$, $ksp$Salsabila Rahmawati$ksp$, $ksp$Workshop manajemen memori digelar Sabtu lalu selama tiga jam, diikuti 28 peserta.
Materinya dibawakan Reza Maulana Hakim dan Bimo Santoso Aji, dengan format setengah
penjelasan dan setengah praktik langsung.

## Struktur sesi

Sesi dibuka bukan dengan `malloc`, melainkan dengan menggambar. Setiap peserta
diminta menggambar apa yang menurut mereka terjadi di memori ketika sebuah
variabel dideklarasikan, lalu ketika sebuah pointer menunjuk ke variabel itu.

Dari 28 gambar, 19 di antaranya menggambarkan pointer sebagai panah yang menunjuk
ke sebuah nilai. Hanya 6 yang menggambarkan pointer sebagai variabel tersendiri
yang menyimpan alamat, dan punya alamatnya sendiri.

"Perbedaan itu kelihatan sepele sampai kamu perlu pointer ke pointer," kata Reza.
"Kalau modelmu berupa panah, `int **p` jadi tidak masuk akal. Kalau modelmu berupa
kotak beralamat, ia cuma kotak yang isinya alamat kotak lain."

## Bagian praktik

Peserta diberi satu program yang sudah jalan dan benar keluarannya, lalu diminta
menemukan tiga kebocoran memori di dalamnya menggunakan `valgrind`.

Rata-rata peserta menemukan dua dari tiga. Kebocoran ketiga sengaja ditaruh di
jalur penanganan galat, yang hanya berjalan kalau alokasinya gagal. Tidak ada satu
pun yang menemukannya lewat pengujian biasa, karena jalur itu tidak pernah dijalani.

Pesan penutupnya diambil dari situ: jalur galat adalah bagian program yang paling
jarang diuji dan paling sering salah.

## Berkas dan rekaman

Rekaman sesi, berkas latihan, dan kunci jawaban tersedia di arsip materi. Program
berisi kebocoran memori yang dipakai dalam sesi praktik dibiarkan apa adanya,
lengkap dengan ketiga kebocorannya, supaya bisa dipakai ulang untuk latihan mandiri.$ksp$, array[$ksp$workshop$ksp$, $ksp$memori$ksp$, $ksp$liputan$ksp$]::text[]);

insert into public.challenges (id, slug, minggu, judul, tanggal_rilis, deadline, difficulty, topik, deskripsi_mdx, constraints, sample_io, hint_terkunci, total_peserta, tags) values
  ($ksp$c-03$ksp$, $ksp$durasi-praktikum$ksp$, 3, $ksp$Durasi Praktikum$ksp$, $ksp$2026-10-05$ksp$, $ksp$2026-10-11T23:59$ksp$, $ksp$MUDAH$ksp$, array[$ksp$tipe-data$ksp$]::text[], $ksp$Server praktikum mencatat lama setiap sesi dalam satuan detik. Angka seperti
`7384` memang tepat, tapi tidak ada yang bisa membacanya sekilas. Koordinator
lab ingin angka itu ditampilkan dalam jam, menit, dan detik.

Tugasmu menulis program yang membaca lama sesi dalam detik, lalu mencetaknya
dalam format yang mudah dibaca.

## Format masukan

Satu bilangan bulat `N`, lama sesi dalam detik.

## Format keluaran

Satu baris dengan format persis seperti ini:

```
J jam M menit D detik
```

`M` dan `D` selalu di antara 0 dan 59. `J` boleh lebih dari 23.

## Catatan

Soal ini cukup diselesaikan dengan variabel, `scanf`, `printf`, dan operator
aritmetika. Tidak perlu `if` ataupun perulangan.$ksp$, array[$ksp$0 <= N <= 1000000$ksp$, $ksp$Keluaran persis satu baris$ksp$, $ksp$Batas waktu 1 detik, batas memori 64 MB$ksp$]::text[], $ksp$[{"input":"7384","output":"2 jam 3 menit 4 detik","penjelasan":"7384 detik = 2 × 3600 + 3 × 60 + 4."},{"input":"59","output":"0 jam 0 menit 59 detik","penjelasan":"Kurang dari satu menit, jam dan menitnya tetap dicetak sebagai 0."},{"input":"86400","output":"24 jam 0 menit 0 detik","penjelasan":"Satu hari penuh. Jam tidak dibatasi sampai 23."}]$ksp$::jsonb, array[$ksp$Satu jam sama dengan 3600 detik, satu menit 60 detik.$ksp$, $ksp$Operator / pada dua bilangan bulat membuang sisanya. Operator % justru mengambil sisanya.$ksp$, $ksp$Setelah jam diambil, sisa detiknya adalah N % 3600. Dari sisa itu baru hitung menitnya.$ksp$]::text[], 0, array[$ksp$pemanasan$ksp$, $ksp$aritmetika$ksp$]::text[]),
  ($ksp$c-04$ksp$, $ksp$nilai-akhir-semester$ksp$, 4, $ksp$Nilai Akhir Semester$ksp$, $ksp$2026-11-02$ksp$, $ksp$2026-11-08T23:59$ksp$, $ksp$MUDAH$ksp$, array[$ksp$pemilihan$ksp$]::text[], $ksp$Di akhir semester, setiap dosen menghitung nilai akhir dari tiga komponen:
tugas, UTS, dan UAS. Bobotnya 30%, 30%, dan 40%. Setelah itu nilai akhir
diubah menjadi nilai huruf.

Tugasmu menulis program yang melakukan keduanya — sekaligus menolak nilai yang
jelas salah ketik.

## Format masukan

Satu baris berisi tiga bilangan bulat: nilai tugas, UTS, dan UAS.

## Format keluaran

Kalau salah satu nilai di bawah 0 atau di atas 100, cetak:

```
nilai tidak valid
```

Kalau semua valid, cetak dua baris:

```
nilai akhir: X.XX
huruf: H
```

Nilai akhir dihitung sebagai `(3 × tugas + 3 × UTS + 4 × UAS) / 10`.

## Tabel huruf

| Nilai akhir | Huruf |
| --- | --- |
| 85 ke atas | A |
| 70 sampai di bawah 85 | B |
| 55 sampai di bawah 70 | C |
| 40 sampai di bawah 55 | D |
| di bawah 40 | E |$ksp$, array[$ksp$Ketiga nilai berupa bilangan bulat$ksp$, $ksp$Nilai di luar 0 sampai 100 dianggap tidak valid$ksp$, $ksp$Nilai akhir dicetak dengan tepat dua angka di belakang koma$ksp$]::text[], $ksp$[{"input":"80 75 90","output":"nilai akhir: 82.50\nhuruf: B","penjelasan":"(3 × 80 + 3 × 75 + 4 × 90) / 10 = 82.5, masuk rentang B."},{"input":"85 85 85","output":"nilai akhir: 85.00\nhuruf: A","penjelasan":"Tepat di batas bawah A tetap mendapat A."},{"input":"100 101 90","output":"nilai tidak valid","penjelasan":"Nilai UTS 101 di luar rentang, jadi tidak ada yang dihitung."}]$ksp$::jsonb, array[$ksp$Periksa validitas dulu. Kalau satu saja tidak valid, cetak pesannya dan selesai.$ksp$, $ksp$Urutkan pemeriksaan huruf dari batas tertinggi ke terendah dengan if – else if.$ksp$, $ksp$Bandingkan 3 × tugas + 3 × UTS + 4 × UAS dengan 850, 700, dan seterusnya supaya batasnya tidak meleset karena pecahan.$ksp$]::text[], 0, array[$ksp$if-else$ksp$, $ksp$nilai$ksp$]::text[]),
  ($ksp$c-05$ksp$, $ksp$tabungan-kas-kelas$ksp$, 5, $ksp$Tabungan Kas Kelas$ksp$, $ksp$2026-11-09$ksp$, $ksp$2026-11-15T23:59$ksp$, $ksp$MUDAH$ksp$, array[$ksp$perulangan$ksp$]::text[], $ksp$Kelas kita menabung untuk acara akhir semester. Setiap minggu bendahara
mencatat berapa yang masuk ke kas, dan setiap minggu pula ada yang bertanya:
"Sudah cukup belum?"

Tugasmu menulis program yang menjumlahkan semua setoran dan memberi tahu di
minggu ke berapa target pertama kali tercapai.

## Format masukan

Baris pertama berisi dua bilangan bulat: `N`, banyaknya minggu, dan `T`, target
tabungan.
Baris kedua berisi `N` bilangan bulat, setoran tiap minggu secara berurutan.

## Format keluaran

Baris pertama:

```
total: X
```

Baris kedua, kalau total pernah mencapai `T` atau lebih:

```
target tercapai di minggu ke-K
```

dengan `K` adalah minggu pertama saat total sementara sudah mencapai `T`.
Kalau sampai minggu terakhir target tidak tercapai:

```
target belum tercapai, kurang S
```

dengan `S` adalah selisih antara target dan total.$ksp$, array[$ksp$1 <= N <= 100$ksp$, $ksp$0 <= T <= 10000000$ksp$, $ksp$0 <= setoran <= 100000$ksp$]::text[], $ksp$[{"input":"5 100000\n20000 15000 30000 25000 10000","output":"total: 100000\ntarget tercapai di minggu ke-5","penjelasan":"Total baru menyentuh 100000 setelah setoran kelima."},{"input":"3 50000\n10000 5000 20000","output":"total: 35000\ntarget belum tercapai, kurang 15000","penjelasan":"Sampai minggu terakhir totalnya 35000, masih kurang 15000."},{"input":"1 0\n0","output":"total: 0\ntarget tercapai di minggu ke-1","penjelasan":"Target 0 sudah tercapai begitu minggu pertama dicatat."}]$ksp$::jsonb, array[$ksp$Tidak perlu menyimpan semua setoran. Cukup tambahkan ke total setiap kali dibaca.$ksp$, $ksp$Simpan minggu tercapainya di variabel tersendiri, dan isi hanya sekali — saat pertama kali total >= T.$ksp$, $ksp$Setoran tetap harus dibaca sampai habis walaupun target sudah tercapai lebih awal.$ksp$]::text[], 0, array[$ksp$for$ksp$, $ksp$akumulasi$ksp$]::text[]),
  ($ksp$c-06$ksp$, $ksp$segitiga-angka$ksp$, 6, $ksp$Segitiga Angka$ksp$, $ksp$2026-11-16$ksp$, $ksp$2026-11-22T23:59$ksp$, $ksp$SEDANG$ksp$, array[$ksp$perulangan$ksp$]::text[], $ksp$Papan pengumuman lab butuh hiasan untuk acara ulang tahun KSP, dan seseorang
mengusulkan segitiga dari angka. Menggambarnya dengan tangan butuh waktu lama.
Mencetaknya dengan program cukup beberapa baris.

Tugasmu mencetak segitiga angka setinggi `N`.

## Format masukan

Satu bilangan bulat `N`.

## Format keluaran

`N` baris. Baris ke-`i` (dimulai dari 1) berisi:

1. `N − i` spasi,
2. angka `1` sampai `i` secara menaik,
3. angka `i − 1` sampai `1` secara menurun.

Contoh untuk `N = 4`:

```
   1
  121
 12321
1234321
```

Jangan mencetak spasi di akhir baris.$ksp$, array[$ksp$1 <= N <= 9$ksp$, $ksp$Tidak ada spasi di akhir baris$ksp$]::text[], $ksp$[{"input":"3","output":"  1\n 121\n12321","penjelasan":"Baris ke-i diawali N − i spasi, naik dari 1 sampai i, lalu turun lagi ke 1."},{"input":"1","output":"1","penjelasan":"Satu baris, tanpa spasi di depan."},{"input":"5","output":"    1\n   121\n  12321\n 1234321\n123454321","penjelasan":"Baris terakhir selalu rata kiri."}]$ksp$::jsonb, array[$ksp$Satu perulangan luar untuk baris, lalu tiga perulangan dalam: spasi, angka naik, angka turun.$ksp$, $ksp$Banyaknya spasi di baris ke-i adalah N − i.$ksp$, $ksp$Angka turun dimulai dari i − 1, bukan dari i, supaya puncaknya tidak tercetak dua kali.$ksp$]::text[], 0, array[$ksp$nested-loop$ksp$, $ksp$pola$ksp$]::text[]),
  ($ksp$c-07$ksp$, $ksp$bingkai-papan-nama$ksp$, 7, $ksp$Bingkai Papan Nama$ksp$, $ksp$2026-11-23$ksp$, $ksp$2026-11-29T23:59$ksp$, $ksp$SEDANG$ksp$, array[$ksp$prosedur$ksp$, $ksp$perulangan$ksp$]::text[], $ksp$Panitia pameran proyek butuh bingkai papan nama untuk setiap meja. Ukurannya
berbeda-beda, tapi bentuknya selalu sama: tepi dari `#`, bagian dalam dari
titik.

Tugasmu mencetak beberapa bingkai sekaligus. Kodenya akan jauh lebih pendek
kalau bagian yang berulang dipindahkan ke prosedur sendiri.

## Format masukan

Baris pertama berisi `K`, banyaknya bingkai.
`K` baris berikutnya masing-masing berisi dua bilangan bulat: lebar dan tinggi.

## Format keluaran

Setiap bingkai dicetak dalam `tinggi` baris dengan `lebar` karakter per baris.
Baris pertama dan terakhir seluruhnya `#`. Baris di antaranya diawali dan
diakhiri `#`, dengan titik di tengahnya.

Contoh untuk lebar 6 dan tinggi 4:

```
######
#....#
#....#
######
```

Antar bingkai dipisahkan tepat satu baris kosong.$ksp$, array[$ksp$1 <= K <= 10$ksp$, $ksp$1 <= lebar, tinggi <= 50$ksp$, $ksp$Antar bingkai dipisahkan tepat satu baris kosong$ksp$]::text[], $ksp$[{"input":"1\n5 3","output":"#####\n#...#\n#####","penjelasan":"Tepi berupa #, bagian dalam berupa titik."},{"input":"2\n3 3\n1 1","output":"###\n#.#\n###\n\n#","penjelasan":"Dua bingkai, dipisahkan satu baris kosong. Bingkai 1 × 1 hanya satu #."},{"input":"1\n4 1","output":"####","penjelasan":"Tinggi 1 berarti hanya ada satu baris tepi."}]$ksp$::jsonb, array[$ksp$Buat satu prosedur yang mencetak satu baris: karakter tepi, isi sebanyak lebar − 2, lalu tepi lagi.$ksp$, $ksp$Bingkai = baris atas, tinggi − 2 baris tengah, baris bawah. Semuanya memanggil prosedur yang sama.$ksp$, $ksp$Hati-hati dengan lebar atau tinggi 1: tepi kanan dan baris bawah tidak boleh tercetak dua kali.$ksp$]::text[], 0, array[$ksp$prosedur$ksp$, $ksp$pola$ksp$]::text[]),
  ($ksp$c-08$ksp$, $ksp$tiga-angka-berurutan$ksp$, 8, $ksp$Tiga Angka Berurutan$ksp$, $ksp$2027-03-01$ksp$, $ksp$2027-03-07T23:59$ksp$, $ksp$SEDANG$ksp$, array[$ksp$prosedur$ksp$, $ksp$pointer$ksp$]::text[], $ksp$Prosedur yang kamu tulis minggu lalu bisa mencetak, tapi belum bisa mengubah
variabel milik `main`. Minggu ini kita perbaiki itu.

Tugasmu mengurutkan tiga bilangan dari kecil ke besar dengan sebuah prosedur,
dan menghitung berapa kali pertukaran terjadi.

## Aturan pengurutan

Pengurutan dilakukan dengan tiga perbandingan, persis dalam urutan ini:

1. bandingkan `a` dan `b`, tukar kalau `a > b`,
2. bandingkan `b` dan `c`, tukar kalau `b > c`,
3. bandingkan `a` dan `b` sekali lagi, tukar kalau `a > b`.

Setiap pertukaran dihitung satu. Dua bilangan yang sama tidak ditukar.

## Format masukan

Baris pertama berisi `T`, banyaknya kasus.
`T` baris berikutnya masing-masing berisi tiga bilangan bulat `a`, `b`, dan `c`.

## Format keluaran

Satu baris untuk setiap kasus:

```
a b c (J tukar)
```

dengan `a b c` sudah terurut menaik dan `J` banyaknya pertukaran.$ksp$, array[$ksp$1 <= T <= 100$ksp$, $ksp$-1000 <= a, b, c <= 1000$ksp$, $ksp$Pertukaran dihitung sesuai urutan perbandingan di soal$ksp$]::text[], $ksp$[{"input":"3\n3 1 2\n1 2 3\n9 5 1","output":"1 2 3 (2 tukar)\n1 2 3 (0 tukar)\n1 5 9 (3 tukar)","penjelasan":"Data yang sudah urut tidak butuh pertukaran. 9 5 1 butuh ketiganya."},{"input":"1\n4 4 2","output":"2 4 4 (2 tukar)","penjelasan":"Dua angka yang sama tidak ditukar, karena yang kiri tidak lebih besar."}]$ksp$::jsonb, array[$ksp$Prosedur tukar(int a, int b) tidak mengubah apa pun di main. Kirimkan alamatnya: tukar(&a, &b).$ksp$, $ksp$Di dalam prosedur, *a adalah isi variabel yang ditunjuk, bukan alamatnya.$ksp$, $ksp$Jumlah pertukaran juga bisa dikembalikan lewat parameter keluaran, sama seperti angkanya.$ksp$]::text[], 0, array[$ksp$parameter-keluaran$ksp$, $ksp$tukar$ksp$]::text[]),
  ($ksp$c-09$ksp$, $ksp$prima-di-rentang$ksp$, 9, $ksp$Prima di Rentang$ksp$, $ksp$2027-03-15$ksp$, $ksp$2027-03-21T23:59$ksp$, $ksp$SEDANG$ksp$, array[$ksp$fungsi$ksp$, $ksp$perulangan$ksp$]::text[], $ksp$Bilangan prima adalah bilangan lebih dari 1 yang hanya habis dibagi 1 dan
dirinya sendiri. Memeriksa satu bilangan itu mudah. Memeriksa ribuan bilangan
dengan kode yang sama berulang-ulang di dalam `main` itulah yang melelahkan.

Tugasmu mencetak semua bilangan prima di antara `A` dan `B`. Pisahkan
pemeriksaan prima ke dalam sebuah fungsi yang mengembalikan nilai.

## Format masukan

Satu baris berisi dua bilangan bulat `A` dan `B`.

## Format keluaran

Baris pertama berisi semua bilangan prima `p` dengan `A <= p <= B`, terurut
menaik dan dipisahkan satu spasi. Kalau tidak ada satu pun, cetak `-`.

Baris kedua:

```
jumlah: K
```

dengan `K` banyaknya bilangan prima yang ditemukan.$ksp$, array[$ksp$1 <= A <= B <= 100000$ksp$, $ksp$Bilangan prima dicetak menaik, dipisahkan satu spasi$ksp$, $ksp$Batas waktu 1 detik, batas memori 64 MB$ksp$]::text[], $ksp$[{"input":"10 30","output":"11 13 17 19 23 29\njumlah: 6","penjelasan":"Enam bilangan prima di antara 10 dan 30."},{"input":"1 10","output":"2 3 5 7\njumlah: 4","penjelasan":"1 bukan bilangan prima."},{"input":"24 28","output":"-\njumlah: 0","penjelasan":"Tidak ada prima di rentang ini, jadi baris pertama berisi tanda minus."}]$ksp$::jsonb, array[$ksp$Tulis fungsi int prima(int n) yang mengembalikan 1 kalau prima dan 0 kalau bukan.$ksp$, $ksp$Cukup coba pembagi dari 2 selama d × d <= n. Kalau tidak ada yang habis membagi, n prima.$ksp$, $ksp$Cetak spasi sebelum setiap bilangan kecuali yang pertama, supaya tidak ada spasi berlebih.$ksp$]::text[], 0, array[$ksp$fungsi$ksp$, $ksp$prima$ksp$]::text[]),
  ($ksp$c-10$ksp$, $ksp$suhu-rata-rata-laboratorium$ksp$, 10, $ksp$Suhu Rata-Rata Laboratorium$ksp$, $ksp$2027-04-26$ksp$, $ksp$2027-05-02T23:59$ksp$, $ksp$MUDAH$ksp$, array[$ksp$array$ksp$]::text[], $ksp$Laboratorium FTI memasang termometer digital di empat sudut ruang server. Setiap
jam, angkanya dicatat ke dalam satu berkas. Bagian kelistrikan ingin ringkasan
harian yang bisa dibaca sekilas, bukan deretan angka mentah.

Tugasmu menulis program yang membaca sederet suhu lalu mencetak rata-rata,
suhu tertinggi, dan suhu terendah.

## Format masukan

Baris pertama berisi satu bilangan bulat `N`, banyaknya pencatatan.
Baris kedua berisi `N` bilangan bulat yang dipisahkan spasi.

## Format keluaran

Tiga baris, dengan format persis seperti ini:

```
rata-rata: X.XX
tertinggi: Y
terendah: Z
```

Rata-rata dicetak dengan dua angka di belakang koma. Perhatikan bahwa pembagian
antar bilangan bulat di C membuang sisanya — `7 / 2` bernilai `3`, bukan `3.5`.
Kamu harus mengubah tipenya lebih dulu.$ksp$, array[$ksp$1 <= N <= 1000$ksp$, $ksp$-50 <= suhu <= 100$ksp$, $ksp$Rata-rata dicetak dengan tepat dua angka di belakang koma$ksp$, $ksp$Batas waktu 1 detik, batas memori 64 MB$ksp$]::text[], $ksp$[{"input":"5\n21 24 23 27 20","output":"rata-rata: 23.00\ntertinggi: 27\nterendah: 20","penjelasan":"Jumlah seluruh suhu 115, dibagi 5 menghasilkan tepat 23."},{"input":"1\n30","output":"rata-rata: 30.00\ntertinggi: 30\nterendah: 30","penjelasan":"Dengan satu data, ketiganya bernilai sama."},{"input":"4\n-3 -1 0 4","output":"rata-rata: 0.00\ntertinggi: 4\nterendah: -3","penjelasan":"Suhu negatif tetap dihitung. Totalnya nol, jadi rata-ratanya nol."}]$ksp$::jsonb, array[$ksp$Nilai awal untuk tertinggi dan terendah sebaiknya diambil dari elemen pertama, bukan dari 0.$ksp$, $ksp$total / n memakai pembagian bulat. Ubah salah satu operandnya ke double sebelum membagi.$ksp$, $ksp$printf("%.2f", x) mencetak dua angka di belakang koma dan sudah membulatkan sendiri.$ksp$]::text[], 0, array[$ksp$array$ksp$, $ksp$min-max$ksp$]::text[]),
  ($ksp$c-11$ksp$, $ksp$ipk-tertinggi-angkatan$ksp$, 11, $ksp$IPK Tertinggi Angkatan$ksp$, $ksp$2027-05-03$ksp$, $ksp$2027-05-09T23:59$ksp$, $ksp$SEDANG$ksp$, array[$ksp$record$ksp$]::text[], $ksp$Bagian akademik ingin memberi penghargaan untuk mahasiswa dengan IPK tertinggi
di angkatannya. Datanya ada: nama, NPM, dan IPK setiap mahasiswa. Ketiganya
milik orang yang sama, jadi sebaiknya disimpan bersama juga.

Tugasmu mencari mahasiswa dengan IPK tertinggi memakai `struct`.

## Format masukan

Baris pertama berisi bilangan bulat `N`.
`N` baris berikutnya masing-masing berisi nama tanpa spasi, NPM, dan IPK,
dipisahkan satu spasi.

## Format keluaran

Satu baris:

```
<nama> (<npm>) <ipk>
```

IPK dicetak dengan dua angka di belakang koma. Kalau ada beberapa mahasiswa
dengan IPK tertinggi yang sama, cetak yang paling dulu muncul di masukan.$ksp$, array[$ksp$1 <= N <= 1000$ksp$, $ksp$Nama tanpa spasi, panjang <= 32 karakter$ksp$, $ksp$NPM berupa 9 digit$ksp$, $ksp$0.00 <= IPK <= 4.00, dengan dua angka di belakang koma$ksp$]::text[], $ksp$[{"input":"3\nAlya 240711001 3.72\nBimo 240711002 3.85\nCitra 240711003 3.85","output":"Bimo (240711002) 3.85","penjelasan":"Bimo dan Citra seri. Yang dicetak adalah yang lebih dulu muncul."},{"input":"1\nDamar 240711010 2.50","output":"Damar (240711010) 2.50","penjelasan":"Satu mahasiswa otomatis menjadi yang tertinggi."}]$ksp$::jsonb, array[$ksp$Satu struct Mahasiswa berisi nama, NPM, dan IPK. NPM lebih aman disimpan sebagai teks.$ksp$, $ksp$Tidak perlu menyimpan semua data. Cukup dua variabel struct: yang sedang dibaca dan yang terbaik sejauh ini.$ksp$, $ksp$Struct bisa disalin utuh dengan satu penugasan: terbaik = sekarang;$ksp$]::text[], 0, array[$ksp$struct$ksp$, $ksp$maksimum$ksp$]::text[]),
  ($ksp$c-12$ksp$, $ksp$papan-peringkat-kelas$ksp$, 12, $ksp$Papan Peringkat Kelas$ksp$, $ksp$2027-05-18$ksp$, $ksp$2027-05-23T23:59$ksp$, $ksp$SULIT$ksp$, array[$ksp$array$ksp$, $ksp$record$ksp$]::text[], $ksp$Rekap nilai kelas selama ini disimpan sebagai dua array terpisah: satu untuk
nama, satu untuk nilai. Sistemnya bertahan sampai seseorang perlu mengurutkan
data itu, dan menyadari kedua array harus digeser bersamaan supaya indeksnya
tetap sejajar. Satu kali lupa, dan nilai orang lain menempel di namamu.

Tugasmu menyusun papan peringkat memakai array of record, lalu mengurutkannya.

## Format masukan

Baris pertama berisi bilangan bulat `N`.
`N` baris berikutnya masing-masing berisi sebuah nama tanpa spasi dan sebuah
nilai, dipisahkan satu spasi.

## Format keluaran

`N` baris, terurut berdasarkan nilai dari besar ke kecil. Kalau nilainya sama,
urutkan berdasarkan nama secara alfabetis menaik. Setiap baris berformat:

```
<peringkat>. <nama> <nilai>
```

Peringkat dimulai dari 1 dan selalu bertambah satu, termasuk saat nilainya sama.

## Catatan

Saat menukar dua elemen, tukar struct-nya utuh — nama dan nilai ikut pindah
bersama. Itulah keuntungan record dibanding dua array terpisah.

Untuk membandingkan dua nama, pakai `strcmp` dari `string.h`. Operator `<`
pada dua array karakter membandingkan alamatnya, bukan isinya.$ksp$, array[$ksp$1 <= N <= 100$ksp$, $ksp$Nama tanpa spasi, panjang <= 32 karakter$ksp$, $ksp$0 <= nilai <= 100$ksp$, $ksp$Urutan: nilai menurun, lalu nama menaik bila seri$ksp$]::text[], $ksp$[{"input":"4\nNadia 92\nGilang 95\nRangga 92\nIvana 88","output":"1. Gilang 95\n2. Nadia 92\n3. Rangga 92\n4. Ivana 88","penjelasan":"Nadia dan Rangga sama-sama 92, jadi urutannya ditentukan secara alfabetis."},{"input":"2\nBimo 70\nAlya 70","output":"1. Alya 70\n2. Bimo 70","penjelasan":"Nilainya identik, sehingga seluruh urutan ditentukan oleh nama."},{"input":"1\nDamar 100","output":"1. Damar 100","penjelasan":"Satu peserta tetap harus dicetak dengan format peringkat yang sama."}]$ksp$::jsonb, array[$ksp$Satu array of struct berisi nama dan nilai jauh lebih aman daripada dua array yang harus dijaga sejajar.$ksp$, $ksp$Bubble sort cukup untuk N <= 100: bandingkan dua elemen bersebelahan, tukar kalau urutannya salah.$ksp$, $ksp$strcmp(a, b) bernilai positif kalau a seharusnya di belakang b secara alfabetis.$ksp$]::text[], 0, array[$ksp$array-of-record$ksp$, $ksp$sorting$ksp$]::text[]);

insert into public.registration_rounds (buka, tutup) values
  ($ksp$2026-08-24T00:00$ksp$, $ksp$2026-09-11T23:59$ksp$);
