// Generated by `npm run db:types`. Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      challenges: {
        Row: {
          constraints: string[]
          deadline: string
          deskripsi_mdx: string
          difficulty: string
          hint_terkunci: string[]
          id: string
          judul: string
          minggu: number
          sample_io: Json
          slug: string
          tags: string[]
          tanggal_rilis: string
          topik: string[]
          total_peserta: number
          updated_at: string
        }
        Insert: {
          constraints?: string[]
          deadline: string
          deskripsi_mdx: string
          difficulty: string
          hint_terkunci?: string[]
          id: string
          judul: string
          minggu: number
          sample_io?: Json
          slug: string
          tags?: string[]
          tanggal_rilis: string
          topik?: string[]
          total_peserta?: number
          updated_at?: string
        }
        Update: {
          constraints?: string[]
          deadline?: string
          deskripsi_mdx?: string
          difficulty?: string
          hint_terkunci?: string[]
          id?: string
          judul?: string
          minggu?: number
          sample_io?: Json
          slug?: string
          tags?: string[]
          tanggal_rilis?: string
          topik?: string[]
          total_peserta?: number
          updated_at?: string
        }
        Relationships: []
      }
      feedback: {
        Row: {
          created_at: string
          dibaca: boolean
          id: string
          kategori: string
          nama: string | null
          pesan: string
        }
        Insert: {
          created_at?: string
          dibaca?: boolean
          id?: string
          kategori: string
          nama?: string | null
          pesan: string
        }
        Update: {
          created_at?: string
          dibaca?: boolean
          id?: string
          kategori?: string
          nama?: string | null
          pesan?: string
        }
        Relationships: []
      }
      gallery_items: {
        Row: {
          alt: string
          caption: string
          created_at: string
          height: number
          id: string
          kategori: string
          src: string
          tanggal: string
          type: string
          video_url: string | null
          width: number
        }
        Insert: {
          alt: string
          caption?: string
          created_at?: string
          height: number
          id: string
          kategori: string
          src: string
          tanggal: string
          type?: string
          video_url?: string | null
          width: number
        }
        Update: {
          alt?: string
          caption?: string
          created_at?: string
          height?: number
          id?: string
          kategori?: string
          src?: string
          tanggal?: string
          type?: string
          video_url?: string | null
          width?: number
        }
        Relationships: []
      }
      module_tentors: {
        Row: {
          module_id: string
          profile_id: string
        }
        Insert: {
          module_id: string
          profile_id: string
        }
        Update: {
          module_id?: string
          profile_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "module_tentors_module_id_fkey"
            columns: ["module_id"]
            isOneToOne: false
            referencedRelation: "modules"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "module_tentors_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      modules: {
        Row: {
          berkas_url: string | null
          id: string
          judul: string
          koordinator: string
          minggu: number
          rilis: string
          ringkasan: string
          tenggat: string | null
          tentor_pj: string[]
          tugas_deskripsi: string
          updated_at: string
        }
        Insert: {
          berkas_url?: string | null
          id: string
          judul: string
          koordinator?: string
          minggu: number
          rilis: string
          ringkasan?: string
          tenggat?: string | null
          tentor_pj?: string[]
          tugas_deskripsi?: string
          updated_at?: string
        }
        Update: {
          berkas_url?: string | null
          id?: string
          judul?: string
          koordinator?: string
          minggu?: number
          rilis?: string
          ringkasan?: string
          tenggat?: string | null
          tentor_pj?: string[]
          tugas_deskripsi?: string
          updated_at?: string
        }
        Relationships: []
      }
      news_posts: {
        Row: {
          body_mdx: string
          cover: string
          excerpt: string
          id: string
          judul: string
          kategori: string
          penulis: string
          published: boolean
          slug: string
          tags: string[]
          tanggal: string
          updated_at: string
        }
        Insert: {
          body_mdx: string
          cover: string
          excerpt: string
          id: string
          judul: string
          kategori: string
          penulis: string
          published?: boolean
          slug: string
          tags?: string[]
          tanggal: string
          updated_at?: string
        }
        Update: {
          body_mdx?: string
          cover?: string
          excerpt?: string
          id?: string
          judul?: string
          kategori?: string
          penulis?: string
          published?: boolean
          slug?: string
          tags?: string[]
          tanggal?: string
          updated_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          angkatan: number | null
          created_at: string
          id: string
          must_change_password: boolean
          nama: string
          npm: string
          role: Database["public"]["Enums"]["app_role"]
        }
        Insert: {
          angkatan?: number | null
          created_at?: string
          id: string
          must_change_password?: boolean
          nama: string
          npm: string
          role?: Database["public"]["Enums"]["app_role"]
        }
        Update: {
          angkatan?: number | null
          created_at?: string
          id?: string
          must_change_password?: boolean
          nama?: string
          npm?: string
          role?: Database["public"]["Enums"]["app_role"]
        }
        Relationships: []
      }
      registration_rounds: {
        Row: {
          buka: string
          created_at: string
          id: number
          tutup: string
        }
        Insert: {
          buka: string
          created_at?: string
          id?: never
          tutup: string
        }
        Update: {
          buka?: string
          created_at?: string
          id?: never
          tutup?: string
        }
        Relationships: []
      }
      sesi: {
        Row: {
          id: string
          judul: string
          pj: string
          rilis: string
          ringkasan: string
          updated_at: string
        }
        Insert: {
          id: string
          judul: string
          pj?: string
          rilis: string
          ringkasan?: string
          updated_at?: string
        }
        Update: {
          id?: string
          judul?: string
          pj?: string
          rilis?: string
          ringkasan?: string
          updated_at?: string
        }
        Relationships: []
      }
      submissions: {
        Row: {
          dinilai_at: string | null
          dinilai_oleh: string | null
          file_kind: string
          file_name: string
          file_size: number
          id: string
          komentar: string | null
          module_id: string
          nilai: number | null
          penilai: string | null
          storage_path: string
          submitted_at: string
          terlambat: boolean
          user_id: string
        }
        Insert: {
          dinilai_at?: string | null
          dinilai_oleh?: string | null
          file_kind: string
          file_name: string
          file_size: number
          id?: string
          komentar?: string | null
          module_id: string
          nilai?: number | null
          penilai?: string | null
          storage_path: string
          submitted_at?: string
          terlambat?: boolean
          user_id: string
        }
        Update: {
          dinilai_at?: string | null
          dinilai_oleh?: string | null
          file_kind?: string
          file_name?: string
          file_size?: number
          id?: string
          komentar?: string | null
          module_id?: string
          nilai?: number | null
          penilai?: string | null
          storage_path?: string
          submitted_at?: string
          terlambat?: boolean
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "submissions_dinilai_oleh_fkey"
            columns: ["dinilai_oleh"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "submissions_module_id_fkey"
            columns: ["module_id"]
            isOneToOne: false
            referencedRelation: "modules"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "submissions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      tentor_profiles: {
        Row: {
          bio: string
          foto: string | null
          keahlian: string[]
          pengalaman: Json
          profile_id: string
          quote: string
          snippet_code: string | null
          snippet_judul: string | null
          socials: Json
          tampil: boolean
          updated_at: string
        }
        Insert: {
          bio?: string
          foto?: string | null
          keahlian?: string[]
          pengalaman?: Json
          profile_id: string
          quote?: string
          snippet_code?: string | null
          snippet_judul?: string | null
          socials?: Json
          tampil?: boolean
          updated_at?: string
        }
        Update: {
          bio?: string
          foto?: string | null
          keahlian?: string[]
          pengalaman?: Json
          profile_id?: string
          quote?: string
          snippet_code?: string | null
          snippet_judul?: string | null
          socials?: Json
          tampil?: boolean
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "tentor_profiles_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      winners: {
        Row: {
          angkatan: number
          challenge_id: string
          foto: string
          id: string
          kode_solusi: string
          minggu: number
          nama: string
          pendekatan: string
          quote: string
          runtime_ms: number | null
          slug: string
          total_menang: number
          updated_at: string
          waktu_submit: string
        }
        Insert: {
          angkatan: number
          challenge_id: string
          foto: string
          id: string
          kode_solusi: string
          minggu: number
          nama: string
          pendekatan: string
          quote: string
          runtime_ms?: number | null
          slug: string
          total_menang: number
          updated_at?: string
          waktu_submit: string
        }
        Update: {
          angkatan?: number
          challenge_id?: string
          foto?: string
          id?: string
          kode_solusi?: string
          minggu?: number
          nama?: string
          pendekatan?: string
          quote?: string
          runtime_ms?: number | null
          slug?: string
          total_menang?: number
          updated_at?: string
          waktu_submit?: string
        }
        Relationships: [
          {
            foreignKeyName: "winners_challenge_id_fkey"
            columns: ["challenge_id"]
            isOneToOne: true
            referencedRelation: "challenges"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      can_grade: { Args: { target_module: string }; Returns: boolean }
      current_app_role: {
        Args: never
        Returns: Database["public"]["Enums"]["app_role"]
      }
      is_admin: { Args: never; Returns: boolean }
      is_staff: { Args: never; Returns: boolean }
    }
    Enums: {
      app_role: "anggota" | "tentor" | "admin"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      app_role: ["anggota", "tentor", "admin"],
    },
  },
} as const

