/**
 * Runs the Supabase CLI against the project database named in `.env.local`,
 * so the connection string (and its password) never has to be typed or
 * pasted on a command line.
 *
 *   npm run db:push                 apply new migrations
 *   npm run db:push -- --seed       apply new migrations and the seed
 *   npm run db:push -- --dry-run    list what would be applied
 *   npm run db:types                regenerate src/lib/supabase/database.types.ts
 */

import { spawnSync } from 'node:child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

function readEnv(file) {
  const env = {}
  for (const line of readFileSync(file, 'utf8').split(/\r?\n/)) {
    const match = /^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/.exec(line)
    if (match) env[match[1]] = match[2].replace(/^(['"])(.*)\1$/, '$2')
  }
  return env
}

const env = readEnv(path.join(ROOT, '.env.local'))
const dbUrl = env.SUPABASE_DB_URL
if (!dbUrl) {
  console.error('SUPABASE_DB_URL belum diisi di .env.local — lihat .env.example.')
  process.exit(1)
}

const [command = 'push', ...flags] = process.argv.slice(2)

// The CLI echoes the connection string on some errors; never print the password.
const mask = (text) => (text ?? '').replace(/(postgres(?:ql)?:\/\/[^:\s]+:)[^@\s]+@/g, '$1***@')

function supabase(args) {
  // Arguments go through a shell on Windows (npx is a .cmd there), so the
  // URL is quoted: a password may contain characters the shell would read.
  const quoted = process.platform === 'win32' ? args.map((arg) => (arg === dbUrl ? `"${arg}"` : arg)) : args
  return spawnSync('npx', ['supabase', ...quoted], {
    cwd: ROOT,
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
    shell: process.platform === 'win32',
  })
}

if (command === 'push') {
  const args = ['db', 'push', '--db-url', dbUrl, '--yes']
  if (flags.includes('--seed')) args.push('--include-seed')
  if (flags.includes('--dry-run')) args.push('--dry-run')
  const result = supabase(args)
  process.stdout.write(mask(result.stdout))
  process.stderr.write(mask(result.stderr))
  process.exit(result.status ?? 1)
} else if (command === 'types') {
  const result = supabase(['gen', 'types', 'typescript', '--db-url', dbUrl, '--schema', 'public'])
  if (result.status !== 0) {
    process.stderr.write(mask(result.stderr))
    process.exit(result.status ?? 1)
  }
  const out = path.join(ROOT, 'src', 'lib', 'supabase', 'database.types.ts')
  mkdirSync(path.dirname(out), { recursive: true })
  writeFileSync(out, `// Generated by \`npm run db:types\`. Do not edit by hand.

${result.stdout}`, 'utf8')
  console.log(`tipe database ditulis ke ${path.relative(ROOT, out)}`)
} else {
  console.error(`Perintah tidak dikenal: ${command}`)
  process.exit(1)
}
