/**
 * Writes `supabase/seed.sql` from the file-based content the site shipped
 * with, so moving to the database loses nothing and retypes nothing.
 *
 *   npm run seed:generate
 *
 * Reads the TypeScript data modules and the MDX / C files beside them. The
 * data modules import `server-only`, so this runs under the `react-server`
 * condition (see the npm script), where that import is a no-op.
 *
 * After the first push the database is the source of truth; these files are
 * only the starting set.
 */

import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

import { challengeSources } from '../src/lib/data/challenges'
import { registrationSeed } from '../src/lib/data/gabung'
import { modulSources } from '../src/lib/data/modul'
import { newsSources } from '../src/lib/data/news'
import { winnerSources } from '../src/lib/data/winners'

const ROOT = path.resolve(import.meta.dirname, '..')
const content = async (...segments: string[]): Promise<string> =>
  (await readFile(path.join(ROOT, 'src', 'content', ...segments), 'utf8')).replace(/\r\n/g, '\n').trim()

/** Dollar-quoted literal. The tag is checked, never assumed absent. */
function text(value: string): string {
  const tag = '$ksp$'
  if (value.includes(tag)) throw new Error(`Seed value contains ${tag}: ${value.slice(0, 60)}`)
  return `${tag}${value}${tag}`
}

const nullable = (value: string | number | undefined | null): string =>
  value === undefined || value === null ? 'null' : typeof value === 'number' ? String(value) : text(value)

const textArray = (values: readonly string[]): string =>
  values.length === 0 ? `'{}'::text[]` : `array[${values.map(text).join(', ')}]::text[]`

const jsonb = (value: unknown): string => `${text(JSON.stringify(value))}::jsonb`

function insert(table: string, columns: string[], rows: string[][]): string {
  if (rows.length === 0) return ''
  const values = rows.map((row) => `  (${row.join(', ')})`).join(',\n')
  return `insert into public.${table} (${columns.join(', ')}) values\n${values};\n`
}

const sections: string[] = [
  '-- Generated by scripts/generate-seed.mts. Do not edit by hand.\n',
  // Re-runnable: clear in dependency order, then insert.
  'truncate public.winners, public.challenges, public.news_posts, public.modules, public.registration_rounds restart identity cascade;\n',
]

sections.push(
  insert(
    'modules',
    ['id', 'minggu', 'judul', 'rilis', 'tentor_pj', 'koordinator', 'ringkasan', 'berkas_url'],
    modulSources.map((modul) => [
      text(modul.id),
      String(modul.minggu),
      text(modul.judul),
      text(modul.rilis),
      textArray(modul.tentorPj),
      text(modul.koordinator),
      text(modul.ringkasan),
      nullable(modul.berkasUrl),
    ]),
  ),
)

const newsRows = await Promise.all(
  newsSources.map(async (post) => [
    text(post.id),
    text(post.slug),
    text(post.judul),
    text(post.tanggal),
    text(post.kategori),
    text(post.cover),
    text(post.excerpt),
    text(post.penulis),
    text(await content('news', `${post.slug}.mdx`)),
    textArray(post.tags),
  ]),
)
sections.push(
  insert('news_posts', ['id', 'slug', 'judul', 'tanggal', 'kategori', 'cover', 'excerpt', 'penulis', 'body_mdx', 'tags'], newsRows),
)

const challengeRows = await Promise.all(
  challengeSources.map(async (challenge) => [
    text(challenge.id),
    text(challenge.slug),
    String(challenge.minggu),
    text(challenge.judul),
    text(challenge.tanggalRilis),
    text(challenge.deadline),
    text(challenge.difficulty),
    textArray(challenge.topik),
    text(await content('challenges', `${challenge.slug}.mdx`)),
    textArray(challenge.constraints),
    jsonb(challenge.sampleIO),
    textArray(challenge.hintTerkunci),
    String(challenge.totalPeserta),
    textArray(challenge.tags),
  ]),
)
sections.push(
  insert(
    'challenges',
    [
      'id', 'slug', 'minggu', 'judul', 'tanggal_rilis', 'deadline', 'difficulty', 'topik',
      'deskripsi_mdx', 'constraints', 'sample_io', 'hint_terkunci', 'total_peserta', 'tags',
    ],
    challengeRows,
  ),
)

const winnerRows = await Promise.all(
  winnerSources.map(async (winner) => [
    text(winner.id),
    text(winner.slug),
    text(winner.nama),
    text(winner.foto),
    String(winner.angkatan),
    text(winner.challengeId),
    String(winner.minggu),
    text(winner.waktuSubmit),
    nullable(winner.runtimeMs),
    text(winner.pendekatan),
    text(await content('solutions', `${winner.id}.c`)),
    text(winner.quote),
    String(winner.totalMenang),
  ]),
)
sections.push(
  insert(
    'winners',
    [
      'id', 'slug', 'nama', 'foto', 'angkatan', 'challenge_id', 'minggu', 'waktu_submit',
      'runtime_ms', 'pendekatan', 'kode_solusi', 'quote', 'total_menang',
    ],
    winnerRows,
  ),
)

sections.push(insert('registration_rounds', ['buka', 'tutup'], [[text(registrationSeed.buka), text(registrationSeed.tutup)]]))

const out = path.join(ROOT, 'supabase', 'seed.sql')
await writeFile(out, sections.filter(Boolean).join('\n'), 'utf8')
console.log(
  `seed.sql: ${modulSources.length} modul, ${newsRows.length} berita, ${challengeRows.length} challenge, ${winnerRows.length} pemenang, 1 gelombang pendaftaran`,
)
